### ISSUE TITLE
[Feature Request] - AMD patches & quirks preset

### ISSUE THREAD

**Issue by fabiosun** [ic005k/OCAuxiliaryTools#107]
Hi @ic005k 
Could be possible to add some preset to Support AMD CPU kernel patches and eventually also quirks needed for different type of AMD Cpu available?
I could send you some proper plists for 4/8/12/24/32 cores cpu (Ryzen and Threadripper(X399-sTrx40))

Thank you

**Comment by ic005k** [comment]
Would love to have you contribute AMD related content. Please upload them as a package and I will add them to the new version of OCAT, thanks.

**Comment by ic005k** [comment]
OCAT uses an open architecture and these Quirks are preset in these files, you just fill in the format and OCAT will recognize them. For example:
https://github.com/ic005k/QtOpenCoreConfig/blob/master/Database/preset/ACPI-Quirks.txt

**Comment by ic005k** [comment]
As for the plist files, they are here.
https://github.com/ic005k/QtOpenCoreConfig/tree/master/Database/BaseConfigs

**Comment by ic005k** [comment]
Previously, as @5T33Z0 provided AMD-related content, but there may be some problems, and it was later removed inside OCAT.
https://github.com/ic005k/QtOpenCoreConfig/issues/97

**Comment by fabiosun** [comment]
Thank you for both links given
I mean a personalisation like this:
sTRX4-AMD 3970x
[sTRX4-AMD 3970x kernel patches.plist.zip](https://github.com/ic005k/QtOpenCoreConfig/files/7881961/sTRX4-AMD.3970x.kernel.patches.plist.zip)

**Comment by fabiosun** [comment]
because it is not possible to produce generic (and working for all) config,plist
But it is possible to produce perfect and working kernel patches section for every CPU available

**Comment by ic005k** [comment]
Agreed, I will put this file into the new version of OCAT, thanks for your contribution.
You can always provide new AMD related content.

**Comment by 5T33Z0** [comment]
Since this .plist **only** contains the Kernel > Patch Array, it's not wise to put them in the database as a base configs. Otherwise people try to boot with it. 

Maybe a sub-menu in the Kernel > Patch section to import these settings would be smarter.

**Comment by ic005k** [comment]
@5T33Z0 Thank you for your thoughtfulness. I'll put it in the database for now, and later I'll upgrade OCAT along your lines so that OCAT can import these patches.

**Comment by fabiosun** [comment]
@ic005k 
<img width="748" alt="Screenshot 2022-01-17 at 2 36 08 PM" src="https://user-images.githubusercontent.com/6358373/149778708-d863119c-8dcf-4c39-9f9b-d2547404747c.png">
Here could be a sub section like 
AMD Kernel patches
3970x
3960x
2990Wx
then:
Ryzen and lower:
16 cores
12 cores
8 cores
4 cores

Only for kernel patches section as a preset as I said on title of this (non) issue :)

**Comment by fabiosun** [comment]
I remark as before, it is not a full config.plist because is not possible to build a generic one working in all situation

**Comment by fabiosun** [comment]
[AMD_CPUs_Kernel Patches Section.zip](https://github.com/ic005k/QtOpenCoreConfig/files/7882297/AMD_CPUs_Kernel.Patches.Section.zip)
and these are the Kernel patches useful for all AMD Cpu available 
load them using a kernel patches preset could be the best and simple option for AMD Users
Others part of config.plist need a  proper setup for every motherboard and it is not possible to generalise
Thank you again for your efforts @ic005k

**Comment by ic005k** [comment]
@fabiosun  I will improve the OCAT and welcome more suggestions or ideas. Many thanks.

**Comment by fabiosun** [comment]
@ic005k is it correct in this way?
[ACPI-Quirks.txt](https://github.com/ic005k/QtOpenCoreConfig/files/7883661/ACPI-Quirks.txt)
all ACPI quirk are set OFF/false/NO

[Booter-Quirks.txt](https://github.com/ic005k/QtOpenCoreConfig/files/7883666/Booter-Quirks.txt)
Only booter quirk On/True/Yes declared

Thank you

**Comment by 5T33Z0** [comment]
I assume you want the content of these lists added to the existing ones and not replace them.

There's no point of adding an entry to ACPI without out settings.

**Comment by fabiosun** [comment]
for now I am only asking to the dev if is correct as I have done above
Trx40 users have all NO/False/Off in ACPI config.plist quirk section..
I do not want to delete anything 
If for CPU Trx40 Threadripper those settings are I a correct way for the app then @ic005k could use and append to complete list (or I can do also for my self)
is it correct for you this way to do?

**Comment by 5T33Z0** [comment]
Again: there's no need to add a line to ACPI Quirks text **if it does not suggest any settings1**

I also think the line for CPU should be shortened: AMD + CPU Model (# of Cores)

**Comment by fabiosun** [comment]
Sample.plist (ACPI quirk)
<img width="627" alt="Screenshot 2022-01-17 at 7 33 44 PM" src="https://user-images.githubusercontent.com/6358373/149822307-8128a717-c8d6-40f2-b452-c321e140e635.png">
If app take this if ACPI quirk are not declared is different from what I would like to have
I hope is now more clear for you

**Comment by 5T33Z0** [comment]
`ResetLogoStatus` is a default in the sample.plist and is purely cosmetic. Really doesn't matter if it is on or off n terms of functionality. It afects the way the Logo of mainboard verndor is handled and affects the  **BGRT.aml** table:

**BGRT.aml** form is the bootstrap graphics resource table.  The `Displayed` field of the tabled should = `0`. However, some vendors have written non-zero data to the `Displayed` entry for some reason, which may cause the screen refresh to fail during the boot phase. The patch works to make `Displayed` = `0`. Not all machines have this table

But: the way Quirk presets are handled right now, you cannot suggest disabling settings.

Since you say you can't build a working config based on generic settings, alll AMD users have to check the table manually any way!

**Comment by fabiosun** [comment]
I am searching to give help to complete some section in proper way based to my direct experience (I am talking only of a subject I know well)
Quoting OpenCore doc does not help me
In downloaded txt quirk file
if quirk is declared in txt means yes on its config plist option
if is not declared I assume it is taken from basic opencore sample.plist and I do not want this in a TRX40 config.plist

About AMD generic settings
Have you again some doubts?

I don't want to argue with you if it's possible
I would like to wait for an opinion from the dev
thank you!

**Comment by 5T33Z0** [comment]
In my experience, the value in the BRGT table is not `0` in almost all cases, so having this feature enabled by default does make sense. 

If you want to remove it from the sample.plist, I suggest you tell that to the OpenCore Dev Team to do that!

**Comment by fabiosun** [comment]
> If you want to remove it from the sample.plist, I suggest you tell that to the OpenCore Dev Team to do that!

Ok I could ask @downloadfritz
May I say to him you suggest to do this?

**Comment by 5T33Z0** [comment]
I suggest you get more acquainted with the ACPI tables of your system before you request to change any default features if you don't know how they work!

**Comment by fabiosun** [comment]
https://github.com/ic005k/QtOpenCoreConfig/issues/88

**Comment by ic005k** [comment]
> @ic005k is it correct in this way? [ACPI-Quirks.txt](https://github.com/ic005k/QtOpenCoreConfig/files/7883661/ACPI-Quirks.txt) all ACPI quirk are set OFF/false/NO
> 
> [Booter-Quirks.txt](https://github.com/ic005k/QtOpenCoreConfig/files/7883666/Booter-Quirks.txt) Only booter quirk On/True/Yes declared
> 
> [UEFI-Quirks.txt](https://github.com/ic005k/QtOpenCoreConfig/files/7883697/UEFI-Quirks.txt) Only UEFI quirk On/True/Yes declared
> 
> Thank you

Sorry, I didn't quite see what you meant? Could you expand on that in more detail? Thanks.
Also, the structure and format of these txt files is simply for ease of maintenance, and OCAT will automatically recognize these txt files.

**Comment by ic005k** [comment]
@fabiosun The kernel patch module of OCAT has been rewritten, you will see these AMD kernel patch files in the kernel patch screen, you are welcome to provide more kernel patch files anytime, thanks.

**Comment by fabiosun** [comment]
@ic005k 
Thanks for your usual kindness and availability.
This feature is very useful for users who want to configure their AMD CPU at kernel patch level

I report a small bug for this new feature introduced

if you click on a kernel patches preset (ie STRX4-AMD3970x kernel patches list and then if you click again on others Ryzen presets, app adds again the patches (i mean it appends newer to older)
it should delete previous patches
this is just to prevent user error

**Comment by fabiosun** [comment]
> Sorry, I didn't quite see what you meant? Could you expand on that in more detail? Thanks.
Also, the structure and format of these txt files is simply for ease of maintenance, and OCAT will automatically recognize these txt files.

I will try to explain better
From original preset in OCAT database I have this (for ACPI quirks):

CPU:macOS High Sierra
ACPI:ResetLogoStatus NormalizeHeaders
**Description**: Removes illegal characters from ACPI Table Headers (if present). Otherwise they cause a panic during boot in macOS High Sierra

this means that in config.plist two quirks will be flagged as Yes (ResetLogoStatus NormalizeHeaders) and maybe  the others that are not declared will be taken from the original sample.plist and will remain unchanged
In this specific case, the official sample.plist is done in this way:
<img width="602" alt="Screenshot 2022-01-18 at 8 13 04 AM" src="https://user-images.githubusercontent.com/6358373/149888517-2851cdd8-75ed-478d-abdc-a9a6a790ffab.png">

What happens and how do you configure the txt useful to OCAT in case I wanted to have all NO for these quirks like the image below?
<img width="609" alt="Screenshot 2022-01-18 at 8 15 46 AM" src="https://user-images.githubusercontent.com/6358373/149888774-45a97e6e-2c4e-4254-ad75-63cda37f644e.png">

Thank you as usual for your patience and time!

**Comment by ic005k** [comment]
> I report a small bug for this new feature introduced
> 
> if you click on a kernel patches preset (ie STRX4-AMD3970x kernel patches list and then if you click again on others Ryzen presets, app adds again the patches (i mean it appends newer to older) it should delete previous patches this is just to prevent user error

It is intentionally designed in such a way that OCAT does not actively change any of the user's data, meaning that it must be up to the user to decide whether or not to clean up old data, which is one of OCAT's principles in terms of maintaining transparency.
Otherwise, some users would say that OCAT likes to do magic.

**Comment by ic005k** [comment]
Just like the preselection of Quirks, some users, including @5T33Z0, have previously suggested that I change the status of Quirks directly, but I didn't take that suggestion and just bold italicized it to suggest that the user might need to select it that way, rather than directly doing it for them.

**Comment by 5T33Z0** [comment]
@fabiosun As I said earlier: the way Quirk presets are handled is to only highlight settings which should be enabled by the user indicated by _italics_. There's no indication for un-selecting features. I thought you would know how this works by now… And again: Leaving ResetLogoStatus enabled doesn't cause any harm.

**Comment by 5T33Z0** [comment]
@ic005k Maybe ~~strikethrough ~~ could implemented used to indicate features to un-select?

**Comment by fabiosun** [comment]
> > I report a small bug for this new feature introduced
> > if you click on a kernel patches preset (ie STRX4-AMD3970x kernel patches list and then if you click again on others Ryzen presets, app adds again the patches (i mean it appends newer to older) it should delete previous patches this is just to prevent user error
> 
> It is intentionally designed in such a way that OCAT does not actively change any of the user's data, meaning that it must be up to the user to decide whether or not to clean up old data, which is one of OCAT's principles in terms of maintaining transparency. Otherwise, some users would say that OCAT likes to do magic.

Thanks for this clarification

I am only talking about a way I am using now OCAT app
I open it 
I can choose a predefinite config.plist (useful for many users and I hope all database is tested and verified more than one people)
As TRX40 Amd user I can't have a predefinite config.plist (or entire EFi ) because every single AMD user could have or not different Bios and motherboard and these two elements change MMIO whitelist area which is essential to us for booting and to have some functionality working well (Sleep,Wake,Shutdown,restart)

Now @ic005k I have opened this "issue" if you see in the title I present a request as "Feature Request"
An I am also sorry if this is not the proper area to discuss of this (if you have a proper area to suggest to talk about this I will do)

now, a TRX40 users could use your beautiful app in this way:
open it
Add Kernel patches useful for his CPU (done yesterday)
Add all quirks useful for TRX40 (and this could be generalised with some presets (I hope))
And then he must calculate for his own entire MMIO whitelist (and here I can't find a way to generalise because too much variable as involved for this task)

PS 
I prefer talk to you and I do not answer to other because it is not acceptable aq user who says to read the doc or ask to Opencore devs

**Comment by fabiosun** [comment]
another way to use your brilliant app for a TRX40 user is to upgrade your working EFI to more modern versions of Opencore now that you have solved the problem of Data Hub and Custom Memory in the Platform section of the config.
So to option for us
Build a config.plist from scratch and also Update an old working one
Thank you

**Comment by fabiosun** [comment]
@ic005k 
I revised the part I had produced earlier by placing typos in the AMD preset names and adding comments in the config.plist for the configuration of the AMD Trx40 system, I also added the customization for the AMD CPU (3970x) at the end of the files
Also added 3 SSDT (not mandatory but functional)

If you think the product is correct, I can also propose other TRX40 and Ryzen configurations that are sure to work

[ACPI.zip](https://github.com/ic005k/QtOpenCoreConfig/files/7902843/ACPI.zip)
to add in OCAT ACPI folder

[MSI_TRX40_Pro_10G_Bios1.81-AMD 3970x.plist.zip](https://github.com/ic005k/QtOpenCoreConfig/files/7902847/MSI_TRX40_Pro_10G_Bios1.81-AMD.3970x.plist.zip)
To add in OCAT BasicConfigs folder

[preset.zip](https://github.com/ic005k/QtOpenCoreConfig/files/7902852/preset.zip)
OCAT Preset Folder
I have appended at the bottom of all quirk txt files, quirks advised to use for AMD trx40
Corrected some my typos in names of AMD kernel patches plist files

Thank you

**Comment by ic005k** [comment]
@fabiosun Thank you for your excellent work, this will be a boon for AMD users.

**Comment by fabiosun** [comment]
May I proceed to produce with other tested config?
Do you prefer a Pull request from macOS86.it?
Or posting here is better for you?
PS (Sorry no so confident in this matter here! :) )

**Comment by ic005k** [comment]
Also, I do not censor any content provided by users, so please feel free to provide whatever content you want, unless another user questions what you provide, in which case the other user can communicate with you directly.

**Comment by ic005k** [comment]
MSI_TRX40_Pro_10G_Bios1.81-AM【D 3】970x-SSDT-PLUG.aml
D and 3
This one has spaces in it, which is not allowed. In the next version, I will fix the configuration file for you.

**Comment by ic005k** [comment]
In fact, you just need to save the configuration file with OCAT, and these low-level errors will be fixed automatically.

**Comment by fabiosun** [comment]
@ic005k
<img width="601" alt="Screenshot 2022-01-20 at 5 31 03 PM" src="https://user-images.githubusercontent.com/6358373/150381096-105ac7da-52ff-4fd0-b66a-d8a8f20764eb.png">
renaming with 1_81 seems to pass that error?

**Comment by ic005k** [comment]
In your original configuration file, it is the space between "AMD" and "39" that causes this error.

**Comment by ic005k** [comment]
I don't know what tool you used to edit your original configuration file. The file name contains spaces, which is not allowed in OC.

**Comment by 5T33Z0** [comment]
It's also way too long for a name.  

.aml files are supposed to be kept as short as possible to avoid loading errors…

**Comment by ic005k** [comment]
When you use OCAT to create an EFI with your configuration file in the database, OCAT will automatically fix low-level errors in your configuration file, but will cause those aml files with spaces to not be copied into the EFI folder.
@5T33Z0 is an expert in this area, you can ask him more and learn from him.

**Comment by fabiosun** [comment]
Ok I will do in a future!
thanks

**Comment by fabiosun** [comment]
<img width="610" alt="Screenshot 2022-01-21 at 3 36 03 PM" src="https://user-images.githubusercontent.com/6358373/150545580-0371eaf5-36cb-465d-b8ee-c03067c61a80.png">
Hi @ic005k 
[Feature Request]
Could you add the preset button in this (MMIO) section of the app in the future?
It would help to reduce the number of complete config.plists for chipsets like sTrx40 that need to declare the MMIO whitelist after activating the corresponding quirk? (DevirtualizeMMIO)
In this case i could try to produce a config.plist or two which could help Strx40 users with all the existing bios and motherboards manufacturers available today
thank you as usual for your time and attention.

**Comment by ic005k** [comment]
You provide these files first, and I'll see how to integrate them inside OCAT.

**Comment by fabiosun** [comment]
Thank you
This is an example:
It is a complete MMIO Whitelist declared in a plist
[MSI_TRX40_Pro_10G_Bios1.81_MMIO.plist.zip](https://github.com/ic005k/QtOpenCoreConfig/files/7917779/MSI_TRX40_Pro_10G_Bios1.81_MMIO.plist.zip)

If the idea could be valid for you, It is possible to produce all manufactured motherboard MMIO preset (they are manufactured and Bios version related)

to be more complete, a TRX40 User need of some mandatory areas to be personalised.
1) Quirks
2) MMIO Whitelist (not the same for all also in some identical condition)
3) Kernel Patches (they are dependant from core numbers and now we have in the app as AMD Presets (Thank You)

Points 1) and 2) could be included in a generic PRESET customized for motherboard manufacturer ie:
MSI_Quirk_MMIO preset
(ie [MSI_Quirk_MMIO.plist.zip](https://github.com/ic005k/QtOpenCoreConfig/files/7917842/MSI_Quirk_MMIO.plist.zip))
ASUS_Quirk_MMIO preset
and so on

In [[macOS86.it](https://www.macos86.it/topic/3307-discussion-trx40-bare-metal-vanilla-patches/#comments)](url) international forum area we help and have helped for free many to have their configuration working

That's why I took the liberty of opening issue #88 and saying a few things!

Thanks again for your usual professionalism and availability

**Comment by ic005k** [comment]
![mmio](https://user-images.githubusercontent.com/25247437/150631047-696c47d6-a6e2-4ebc-8d98-423c519c6c69.png)

**Comment by ic005k** [comment]
You can make a basic profile for each possible model. Going through the presets is not a good way to go, because MMIO is a low frequency used module and there is absolutely no need to make a separate preset for a module that is used very infrequently.
In the meantime, I'd like to hear @5T33Z0's opinion.

**Comment by fabiosun** [comment]
Nevermind
Leave all as you think is good 👍 
Thank you

**Comment by 5T33Z0** [comment]
In my opionion, this approach is way too convoluted. Way too many pieces to puzzle together into a working AMD config. I don't see how anybody would understand it. It requires an extra manual just to understand the approach alone which defeats the purpose of the app.

Probably a different app is required which works in stages – similar to how OC Gen-X does it, but just for AMD specifically.

**Comment by fabiosun** [comment]
I disagree , but if ic005k's ​​opinion is this, I can't help but accept it, the only big difference is the peculiarity of MMIOs
The rest is easily solved with the patches inserted as plist and the quirks can be appended in the txt files already present
Then a question without controversy
Are you really convinced that all the configurations presented in BasicConfigs work for all users?

**Comment by 5T33Z0** [comment]
As for Intel, I am pretty sure unless you have an some weird ASUS X79 board which tend to have BIOS-based issues, these configs work for PCs if used in conjunction with the included `Instructions.md` which is included in the base configs folder to adjust certain parameters. 

The concept of having a base config is _not_ to have an out of the box solution for everybody but a starting point to get the system going including the correct ACPI files, settings, quirks as well as Framebuffers for different scenarios (on-board graphic used for driving a display or computational tasks).

As for AMD, I don't know since I don't have an AMD system. But I thinlk you have to decide whether to create one base config for each CPU family (and variants thereof) and Instructions to make it work or keep it completlyly individual without any base configs and just resolve all user requests in forums.

**Comment by fabiosun** [comment]
> @fabiosun The kernel patch module of OCAT has been rewritten, you will see these AMD kernel patch files in the kernel patch screen, you are welcome to provide more kernel patch files anytime, thanks.

Instructions.md should be updated if this OCAT rewritten part will be maintained in future.
With AMD kernel Patches Preset OCAT covers all existing AMD CPU, from High Sierra to latest Monterey and these have been provided here by me and are maintained by the AMD community:

![Screenshot 2022-01-24 at 7 54 27 AM](https://user-images.githubusercontent.com/6358373/150736071-e171ca60-f668-455a-9b26-3890ca45ab0b.png)

This part helps to set kernel patches for each type of CPU and to eliminate (in the case of sTRX4 CPU) any patches that are not useful.

Therefore, assuming that the solutions are not "out of box" working even for the Intel BasicConfigs and that it is enough to refer to a guide or indicate what is mandatory to change, most likely for AMD it is possible to use 2 or 3 basicconfig.plist and add in the dedicated files some quirks already present in TXT format in the app

**Comment by 5T33Z0** [comment]
The database should be cleaned once fabiosun is done. There is a duplicate MSI_TRX40_Pro_10G_Bios1.81-AMD 3970x.plist in the database and the kernel patch folder contains duplicates as well.

**Comment by fabiosun** [comment]
https://github.com/ic005k/QtOpenCoreConfig/pull/116
I see in new release the same file I have pull requested to delete in above closed pull request

In BasicConfig I see instead no duplicated related to AMD config

**Comment by fabiosun** [comment]
@ic005k based on Instructions.md in OCAT Database I have produced this preliminary file:

[Instructions_AMD_TRX40.md](https://github.com/ic005k/QtOpenCoreConfig/files/7928133/Instructions_AMD_TRX40.md)

It could  help for now sTrx4 Users and in a future all Ryzen users (inside also a bit of informations for them)

I have also put there some link of a couple of sources to understand better MMIO Whitelist area of the config 
Mandatory to understand how to have a working sTRX4 based PC

What do you think?
 
Thank you

**Comment by ic005k** [comment]
> @ic005k based on Instructions.md in OCAT Database I have produced this preliminary file:
> 
> [Instructions_AMD_TRX40.md](https://github.com/ic005k/QtOpenCoreConfig/files/7928133/Instructions_AMD_TRX40.md)
> 
> It could help for now sTrx4 Users and in a future all Ryzen users (inside also a bit of informations for them)
> 
> I have also put there some link of a couple of sources to understand better MMIO Whitelist area of the config Mandatory to understand how to have a working sTRX4 based PC
> 
> What do you think?
> 
> Thank you

Great, I've put it in the database, thanks for the great work you're doing for AMD.

https://github.com/ic005k/QtOpenCoreConfig/blob/master/Database/BaseConfigs/Instructions_AMD_TRX40.md

**Comment by fabiosun** [comment]
@ic005k 
It is a preliminary file
I have to add some instructions

**Comment by ic005k** [comment]
> @ic005k It is a preliminary file I have to add some instructions

It's okay, you can always upgrade these files.

**Comment by fabiosun** [comment]
@ic005k  hello

this pull request was merged : https://github.com/ic005k/QtOpenCoreConfig/pull/126
But I can't see in new OCAT release new preset for 3990x.

**Comment by ic005k** [comment]
> 



> this pull request was merged : #126
> But I can't see in new OCAT release new preset for 3990x.

I just checked and you seem to have pushed this file to the wrong place? You should push it to /Database/preset/Kernel-Patch/.
But you pushed it under /, which must not be visible in the kernel-patch list.
Currently it is here.
https://github.com/ic005k/QtOpenCoreConfig/blob/master/sTRX4-AMD%203990x%20kernel%20patches.plist

**Comment by ic005k** [comment]
@fabiosun Later, you can package the files here and I'll put them inside the GitHub project for you.

**Comment by fabiosun** [comment]
I did a pull request I hope to have adjusted a my error
Sorry for any inconvenience you have had for this!

**Comment by ic005k** [comment]
That's fine, you can always submit any changes you have, I have a positive attitude towards OCAT updates.
The vitality of an app lies in the continuous improvement and update.

**Comment by fabiosun** [comment]
@ic005k Do you like I will add here some idea (if it comes) for AMD features request?
Or is it better to close this and open another one if I need to ask others features?

**Comment by ic005k** [comment]
@fabiosun It's all right, but I think it's best to start a new topic, the current one is too long to reply to.
In fact, there is no need to ask my opinion on any of this, just do it according to your own heart.
We are all young people, no need to be constrained.
