### ISSUE TITLE
[Feature Request] Add option to use OpenCore DEBUG or RELEASE version

### ISSUE THREAD

**Issue by chriswayg** [ic005k/OCAuxiliaryTools#133]
Please add a menu option or a preference to use the OpenCore debug version of the current release when initially creating the EFI folder. - I might have missed it, but I believe that currently OCAuxiliaryTools creates the EFI with the RELEASE files and not the DEBUG files, without giving a choice. I would prefer to use the debug version when setting up a new hackintosh system. 

A feature to switch from DEBUG to RELEASE files of OpenCore and vice-versa would also be nice. This only applies to these files  AFAIK:

```
EFI/BOOT/BOOTx64.efi
EFI/OC/Drivers/OpenRuntime.efi
EFI/OC/OpenCore.efi
```

[OpenCore-0.7.7-DEBUG.zip](https://github.com/acidanthera/OpenCorePkg/releases/download/0.7.7/OpenCore-0.7.7-DEBUG.zip)

**Comment by ic005k** [comment]
I will consider this feature in a later version.

**Comment by 5T33Z0** [comment]
Although I appreciate to be able to install Debug builds I'd prefer a different approach for handling this instead of simply replacing the "Dev" mode by a Debug build. Otherwise you can only install the latest build as a Debug version. There's rarely any need for installing the debug version, while a lot of users use the Release versions of nightly builds on the regular. 

Therefore, I'd prefer some switches instead:

**Mode**: Official / Nightly
**Build**: Release / Debug

This way all use cases and possible combinations would be covered.

Thanks.

**Comment by ic005k** [comment]
I will take this into consideration, this should be the last feature of OCAT.
I will consider, how to implement these better.

**Comment by chriswayg** [comment]
> A feature to switch from DEBUG to RELEASE files of OpenCore and vice-versa would also be nice. 

I actually I noticed that I can already switch back-and-forth from the Official-RELEASE version to the Dev-DEBUG version with your current defaults, just by using the Synchronize feature.

> I'd prefer some switches instead:
>     _Mode: Official / Nightly_
>     _Build: Release / Debug_
> This way all use cases and possible combinations would be covered.

@5T33Z0 I agree to this proposal. This would enable the choices _for all possible use cases_. Personally I would prefer to use Official-RELEASE and Official-DEBUG, as I have had no need for the nightly DEV versions so far, but obviously use cases and preferences will vary.

**Comment by chriswayg** [comment]
> A feature to switch from DEBUG to RELEASE files of OpenCore and vice-versa would also be nice. 

Actually I noticed that I can already switch back-and-forth from the Official-RELEASE version to the Dev-DEBUG version with your current defaults, just by using the Synchronize feature.

> I'd prefer some switches instead:
>     _Mode: Official / Nightly_
>     _Build: Release / Debug_
> This way all use cases and possible combinations would be covered.

@5T33Z0 I agree to this proposal as it would enable all preferred workflows. Personally I would prefer to use Official-RELEASE and Official-DEBUG, as I have had no need for the nightly DEV versions so far, but obviously use cases and preferences will vary.

**Comment by ic005k** [comment]
The option of DEBUG has been added to the edit menu, feel free to test and give feedback on the problem.

**Comment by chriswayg** [comment]
> The option of DEBUG has been added to the edit menu

Works very nicely in enabling the four possible combinations and I used it already while testing some new hackintosh configs for my current system.

**Comment by ic005k** [comment]
@chriswayg @5T33Z0 

At present, the development version of the online upgrade has been supported, you can find a URL that provides the development version of OC, try this function. For example, the following URL.
https://github.com/dortania/build-repo

**Comment by ic005k** [comment]
@chriswayg @5T33Z0 @fabiosun 

Now, basically all the functions of OCAT are done. The only thing left to do is to keep optimizing and improving it.
You guys can always give feedback on any issues.

**Comment by 5T33Z0** [comment]
Thank you very much!

**Comment by chriswayg** [comment]
> At present, the development version of the online upgrade has been supported, you can find a URL that provides the development version of OC, try this function. For example, the following URL. https://github.com/dortania/build-repo

It works well with that url and downloads the current development version. Am I correct to assume, that it downloads the version shown in https://github.com/dortania/build-repo/releases at the top marked as 'Latest'?

I am just curious if there a file in OpenCore which actually shows the build number? I looked through the files downloaded today into `/Applications/OCAuxiliaryTools.app/Contents/MacOS/devDatabase`

and OpenCore does not actually appear to show the version number in any of the plaintext files. I do see the build-date when I actually boot the dev version, which is sufficient for my purposes.

**Comment by 5T33Z0** [comment]
Nope, it provides ALL nightly releases of the Acidanthera projects.

The link you used before was the right one. If I manually download nighly builds, I use this: https://dortania.github.io/builds/?product=OpenCorePkg&viewall=true
