### ISSUE TITLE
开发板的更新源怎么填写

### ISSUE THREAD

**Issue by w19996** [ic005k/OCAuxiliaryTools#138]
怎么我随便填一个什么内容都能成功更新数据库呢

**Comment by ic005k** [comment]
那可能是你没切换到开发版，很简单
1.切换到开发版
2.找一个提供OC开发版的GitHub网址，填上这个网址就可以了，比如下面这个
https://github.com/dortania/build-repo

**Comment by ic005k** [comment]
升级完成之后会有【开发版】之类的提示
这个功能才完成，可能也会存在bug，欢迎反馈问题

**Comment by w19996** [comment]
> 升级完成之后会有【开发版】之类的提示 这个功能才完成，可能也会存在bug，欢迎反馈问题
好的，谢谢
