### ISSUE TITLE
In the new version of OCAT file menu, there is a new "New Key Field", what is it for?

### ISSUE THREAD

**Issue by ic005k** [ic005k/OCAuxiliaryTools#141]
This function can be used to add one or more new fields to meet the needs of the OC configuration file if new options are added to the OC configuration file during the OC upgrade process, and OCAT does not have time to follow the upgrade.

**Comment by chriswayg** [comment]
When testing this feature, I added a new `TestNewKey`  `bool` field to the configuration. It obviously works, but now this key shows up every time I open the app and I do not know how to get rid of it or where to delete it. Also OC Validate complains about my  new key:

`OCS: No schema for TestNewKey at 6 index, context <Quirks>! Serialisation returns 1 error!`

Where is the file in which this change is configured, so I can reverse it?

**Comment by ic005k** [comment]
It's great to see you trying out the new features of OCAT.
Please right-click on the newly created field and select "Delete".

**Comment by 5T33Z0** [comment]
@ic005k Wow, this is a great feature to future-proof the app!

**Comment by ic005k** [comment]
Currently, this feature may no longer be needed, as OCAT has now added a module for intelligent recognition.

**Comment by chriswayg** [comment]
>Currently, this feature may no longer be needed, as OCAT has now added a module for intelligent recognition.

So how would a new field be added?

Do we just add it to the Config.plist? What types of fields can be added in this way?

**Comment by ic005k** [comment]
> 

Currently, this ability to add new fields is almost useless, and it will probably be deprecated outright in a later release.
For OCAT, you don't need to add any new fields manually, because OCAT has added a smart module to do this.

**Comment by chriswayg** [comment]
> > So how would a New Key Field be added in the current version?
> 
> @[chriswayg](https://github.com/chriswayg) Currently, this ability to add new fields is almost useless, and it will probably be deprecated outright in a later release. For OCAT, you don't need to add any new fields manually, because OCAT has added a smart module to do this.

Well I am not sure, that this always works. When upgrading from 0.7.8 to 0.7.9 the `LogModules` was added automagically by OCAT. But in other cases when opening a Config.plist, I had an error from OCvalidate that `LogModules` was missing. What should we do in such cases inside OCAT?

**Comment by ic005k** [comment]
> What should we do in such cases inside OCAT?

Save the Config.plist and the error message will be corrected automatically.
