### ISSUE TITLE
Open config 右键显示版本错误 

### ISSUE THREAD

**Issue by iaihc** [ic005k/OCAuxiliaryTools#142]
从077版本改版后，配置工具，右键打开菜单又错误了，不显示 OCAuxiliaryTools 版本了

**Comment by ic005k** [comment]
已加入bug追踪系统，感谢反馈

**Comment by ic005k** [comment]
这个貌似不是bug，我这边刚测试了下，没问题呀，这是个常见动作，要是有问题，肯定很多人反馈
是不你系统层面的事？
建议重建缓存并修复权限试试？

**Comment by ic005k** [comment]
关注中。。。

**Comment by iaihc** [comment]
开发人员，可能很少人像我这样使用 配置工具，因为OC的版本关系，通常我会保留1-2个OC版本，那么就需要适配的工具去配置，那么，当打开一个config.plist文件的时候，如 OCAuxiliaryTools 提示软件版本最好，以前的可以，自从升级到了支持 078和077最后几个版本后，这个功能消失了，导致不得以，我把OCAuxiliaryTools 低版本的改名了，这样以区别同一台机器有两个版本的OCAuxiliaryTools 配置工具问题，但对于最新的，只有OCAuxiliaryTools 这一个右键提示了。虽说大部分人不影响，但对于软件版本，打开右键config选择版本最好有提示保留。我非常希望你能解决

**Comment by iaihc** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ic005k/OCAuxiliaryTools"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年2月8日(星期二) 下午2:21
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ic005k/OCAuxiliaryTools] Open config 右键显示版本错误  (Issue #142)





 
关注中。。。
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android. 
You are receiving this because you authored the thread.Message ID: ***@***.***&gt;




如上图，其实我用了一个20220081才能显示右键版本，最后的 077版本支持的：OCAT_Mac 20220135&nbsp;反而右键出错了，更别说最新的OCAT_Mac 20220142版本，我估计，当出现20220099以后版本，这个提示，其实是OCAT_Mac 20220142&nbsp;版本的右键。也就是这种错乱，让我非常难以接受


希望开发人员，一定要把这个右键搞好，OCAT_Mac 20220135&nbsp;这个版本我保留，只能把它改名才行，如果不改名，那么也不显示版本

**Comment by iaihc** [comment]
这是使用一个老版本的 077支持的工具和078最新的工具右键情况，能提示版本，但提示077版本正确，但是078版本不正确。



仔细看这张图，这是v20200135&nbsp;支持oc077，和&nbsp;v20220142版本共存情况，右键只有一个版本提示了，不得以，我只能把&nbsp;v20220135的工具改名来区分版本


如下图：



这张截图，右键这选中这个是我改名的，而最新的版本是只有一个右键提示了。


综上所述，右键菜单提示版本错误，多版本会有这个问题。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ic005k/OCAuxiliaryTools"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年2月8日(星期二) 下午2:21
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ic005k/OCAuxiliaryTools] Open config 右键显示版本错误  (Issue #142)





 
关注中。。。
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
