### ISSUE TITLE
OCAT SystemInfo: macserial using serial of active system rather than serial of Config.plist? Check serial online?

### ISSUE THREAD

**Issue by chriswayg** [ic005k/OCAuxiliaryTools#143]
### Inquiry

What is the purpose of `macserial` using the serial of the active system on which OCAT is running rather than using the serial of the loaded Config.plist?

In _OCAT -> PlatformInfo -> SystemInfo_ i see the output of the macserial utility. 

As a user I expected it to use the serial I set in _PlatformInfo -> Generic_, as this would give me some information about the serial I am using in my Config.plist. I suppose you had a reason for using the system serial, but I never had a use-case for that yet.

### Feature Request
On a related matter, it would be nice to have a button somewhere in the PlatformInfo section of OCAT linking to the Apple [Check Your Service and Support Coverage](https://checkcoverage.apple.com) page where we can make sure that the generated serial has not been used on a real Mac. I think the link format for submitting the serial rarely ever changes:

Example: https://checkcoverage.apple.com/?sn=C02C30JEPN5T

**Comment by ic005k** [comment]
System information is a real thing, and the serial number inside the configuration file you opened, if it is not running on a real machine, then please ask how to generate system information?
Querying serial number is a good idea, I will add this feature, thanks.

**Comment by ic005k** [comment]
By the way, there is a question that I need to clarify.
Is it considered a violation to explicitly direct a user in an app to go to Apple's website to look up a serial number that may not exist? Or is there any legal risk? Thanks.
If there is any legal risk or violation, I will remove the serial number lookup feature.
I personally feel that adding this feature seems a bit inappropriate.

**Comment by chriswayg** [comment]
>  Is it considered a violation to explicitly direct a user in an app to go to Apple's website to look up a serial number that may not exist? Or is there any legal risk? Thanks. If there is any legal risk or violation, I will remove the serial number lookup feature. 

Personally, I do not think there is a legal violation for using their website to look up a serial number from an app, but IANAL ;-) - I have seen such functionality in other similar GUI apps with a 'Check Coverage' button, which forwards the serial using the link syntax I used above. Then the user only needs to solve the Captcha. I don't think that Apple ever complained, as these apps have been around for years.

I believe, that this functionality actually protects Apple, the owners of the real serial and the hackintosh community. If OCAT users fail to check their serial and accidentally use an active serial number your app created, it could actually cause more problems for Apple and the hackintosh community, as some people's Apple IDs may get blocked. The url opens in a user's browser, so the actual request from their database is done by the user not done by your app.

**Comment by ic005k** [comment]
> * Rename the SystemInfo Tab to Serialnfo Tab (because it basically calls macserial), and use the serial from the Config.plist in the PlatformInfo section.

You are a very meticulous person and the first to question this detail, thanks.
In fact, I basically didn't think hard about this module when I was working on it before.
I am very much in favor of changing the system information to serial number information.
Feel free to find more questions or suggestions.

**Comment by ic005k** [comment]
Feature added.
