### ISSUE TITLE
[UI enhancement request] Dynamical tab

### ISSUE THREAD

**Issue by fabiosun** [ic005k/OCAuxiliaryTools#146]
Hi @ic005k first of all thank you for constant daily update to improve OCAT.

I would like to ask a chance to increase or decrease dynamically interface tab in some section like Kernel/patch
See picture below
<img width="1356" alt="Screenshot 2022-02-09 at 2 47 53 PM" src="https://user-images.githubusercontent.com/6358373/153214645-3be03741-9cad-41b1-976c-84de2dfa4c8b.png">

**Comment by ic005k** [comment]
Do you mean you can change the column width of the table with the mouse?

**Comment by fabiosun** [comment]
Thank you!

**Comment by fabiosun** [comment]
@ic005k some problem in this feature but happy you added it

https://user-images.githubusercontent.com/6358373/153770111-dd26f719-168e-4885-a6ec-a77179091553.mp4

**Comment by ic005k** [comment]
Please uncheck "Automatic column width" in the right-click menu.
