### ISSUE TITLE
建议增加MOD版OC的编辑功能

### ISSUE THREAD

**Issue by w19996** [ic005k/OCAuxiliaryTools#15]

**Comment by ic005k** [comment]
MOD版，我记得貌似这个项目已经停止了吧，好长时间都没人维护了。能否给个链接？

**Comment by w19996** [comment]
> MOD版，我记得貌似这个项目已经停止了吧，好长时间都没人维护了。能否给个链接？

远景有人维护
http://bbs.pcbeta.com/viewthread-1838814-1-2.html

**Comment by ic005k** [comment]
好的，我先去看看

**Comment by ic005k** [comment]
我看了下，OCC貌似可以支持这个MOD版本的OC，所以我就不再重复这个功能了。建议直接采用OCC来编辑MOD版本。
其实在我没有写这个OCAT之前，都是使用OCC，也蛮好用的。

**Comment by btwise** [comment]
> 我看了下，OCC貌似可以支持这个MOD版本的OC，所以我就不再重复这个功能了。建议直接采用OCC来编辑MOD版本。
> 其实在我没有写这个OCAT之前，都是使用OCC，也蛮好用的。

是的，是我鼓捣的😁

**Comment by ic005k** [comment]
根据用户需求，目前OCAT已支持各种OC衍生版，欢迎测试。
具体操作步骤：https://github.com/ic005k/OCAuxiliaryTools/issues/203

**Comment by ic005k** [comment]
请注意，OCAT支持的各种OC衍生版是不区分OC版本的，全部采用智能适配的方式，也就是说，你可以选择任何一个OC的衍生版使用。

**Comment by w19996** [comment]
> 请注意，OCAT支持的各种OC衍生版是不区分OC版本的，全部采用智能适配的方式，也就是说，你可以选择任何一个OC的衍生版使用。

好的，我试一下

**Comment by ic005k** [comment]
> 好的，我试一下

好，欢迎任何反馈

**Comment by AlanSachin** [comment]
> > 好的，我试一下
> 
> 好，欢迎任何反馈
http://bbs.pcbeta.com/viewthread-1838814-1-2.html
OC 0.8.0 MOD版使用最新版OCAT，序列号以及MLB不能生成

**Comment by ic005k** [comment]
> 序列号以及MLB不能生成

不能生成的原因，可能是这个包里面没有包含macserial这个文件，你检查看看或者请联系该包的原始作者。
OCAT生成序列号是完全采用OC官方的macserial文件，而不是OCAT自行生成。
