### ISSUE TITLE
Online update check for OpenCore files in Sync Window not working correctly (DEV).

### ISSUE THREAD

**Issue by 5T33Z0** [ic005k/OCAuxiliaryTools#150]
I've noticed that when using the Sync function, the OpenCore files (Dev Mode, Release version) used are not from the latest available commit. While checking for kext updates performs an online check, OpenCore files are not checked online but are  stored locally instead.

Used OpenCore version in 20220145: https://github.com/acidanthera/OpenCorePkg/actions/runs/1808597752/
Currently latest build: https://github.com/acidanthera/OpenCorePkg/actions/runs/1832366171

Please integrate an online update for OpenCore files as well, if possible.

Thanks

**Comment by ic005k** [comment]
?
Currently all OpenCore is available online for automatic updates. If you are using the development version of OC, please customize the update source. The official Actions development version does not support anonymous downloads and cannot be used as an update source for the OC development version.
There is a button on top of the Sync OC button that is for updating OC.

**Comment by ic005k** [comment]
I don't quite understand what you mean, is the update OpenCore button not found? Or is there a glitch in the app?

**Comment by 5T33Z0** [comment]
Like I said: it is not using the latest commit. It's an older version.

Where can I customize the update source? 

The builds linked on the Dortania site don't require a login: https://dortania.github.io/builds/?product=OpenCorePkg&viewall=true

**Comment by ic005k** [comment]
The update source of the OC development version can be customized inside the preference settings.

**Comment by 5T33Z0** [comment]
I see. There was no repo selected in the dropdown menu. I didn't know that you have to _manually_ select a mirror after switching to dev mode. Thanks.

**Comment by ic005k** [comment]
Frankly speaking, this source: https://github.com/dortania/build-repo is not only releasing the development version of OC, it is also rolling out the development version of other kext.
So, when it releases a development version of kext, OCAT can't update the development version of OC.
For example, currently it does not release the development version of OC, but VirtualSMC e6d31c5: https://github.com/dortania/build-repo/releases
So, there is really no particularly good source for updating the OC development version.
Also this source does not provide Linux related files, in fact the official development version of the source is the best and most comprehensive, but does not support anonymous downloads. The official OC development version contains the files needed for the 3 platforms and is very comprehensive.
You can also look for other sources to see if there are any suitable ones, for example, try the following source: https://github.com/bugprogrammer/HackinPlugins

**Comment by ic005k** [comment]
Also, you can see which file the source is publishing by clicking on the "Source" link in the upper right corner of the sync window.

**Comment by ic005k** [comment]
I mainly don't have much time, otherwise I would consider building my own update source for OC devs to provide the most comprehensive OC devs including Linux.
However, considering the environment and not wasting energy, there is no need to duplicate the construction of more OC development version update sources.
Of course, if there are other OC enthusiasts who do so, I have no objection.

**Comment by ic005k** [comment]
Simply put, only this source: https://github.com/dortania/build-repo/releases
is being released for OC development, OCAT can be updated to the development version of OC.
In this way, you should be able to understand it.

**Comment by ic005k** [comment]
For: https://github.com/dortania/build-repo
Currently, there are 3 solutions.
1. you can suggest the author of this site to make a separate channel for the development version of OC and support Linux system. This is the best solution now.
2. If the author is not willing to do so, then OCAT can use sniffing technology to get the latest development version of OC on this site. The reason why OCAT is currently reluctant to use sniffing techniques to get the development version available on this site is that it does not integrate the OC files for Linux, it is not perfect, and OCAT is not willing to do too much.
3. Look for a more perfect URL that offers OC development version.

**Comment by 5T33Z0** [comment]
After updating OCAT (20220165) I get more errors
![Bildschirmfoto 2022-02-17 um 08 25 40](https://user-images.githubusercontent.com/76865553/154428326-d638810b-a29b-4460-ae3d-b8dccdec0738.png)
Using the "Ugrade Packages function" and "Get OpenCore" functions don't fix it. Manually adding a "DevDatabase" folder also doesn't work. 
How do I fix this?

**Comment by ic005k** [comment]
Very easy, the steps are as follows.
1. Change the update source of the OC development version to.
https://github.com/bugprogrammer/HackinPlugins
2. Switch to the development version in the edit menu
3. Click "Get OpenCore" in the window of the synchronized OC.

**Comment by ic005k** [comment]
The reason for this problem is that the OC development version of the source https://github.com/dortania/build-repo is currently not on the OpenCore channel.

**Comment by 5T33Z0** [comment]
Okay, thanks. Then I am using  https://github.com/bugprogrammer/HackinPlugins for now since I haven't found another alternative yet.

**Comment by ic005k** [comment]
By the way, the user Database automatically generated by OCAT is located in the Database and devDatabase under the Home root directory.

**Comment by 5T33Z0** [comment]
After downloading Dev builds, the same Warning Window about missing windows files always pops up twice:

![Bildschirmfoto 2022-02-25 um 09 03 06](https://user-images.githubusercontent.com/76865553/155678531-efe54156-c82b-4869-9839-fe329d2afbee.png)

After hitting "Ok" it pops up again:

![Bildschirmfoto 2022-02-25 um 09 03 13](https://user-images.githubusercontent.com/76865553/155678566-b4d227df-4bf4-4d8a-aed8-33335537ae84.png)

Can you fix this, so it only appears ones?

**Comment by ic005k** [comment]
Instead of Windows popping up the window twice, Windows and Linux each popped up once, with the second time being a window prompt for Linux.
This source only contains the Mac version, Windows and Linux are not included.
You might as well download the latest development version here and import it into OCAT: https://github.com/acidanthera/OpenCorePkg/actions

**Comment by ic005k** [comment]
Currently, there is no perfect update source for the OC development version, so if you are interested, you may want to build a perfect update source for the OC development version.

**Comment by ic005k** [comment]
Some users have suggested to me that it is possible to update Kexts to the latest development version, which is something that can't be done perfectly, because without a stable update source, none of this can be done.

**Comment by 5T33Z0** [comment]
> You might as well download the latest development version here and import it into OCAT: https://github.com/acidanthera/OpenCorePkg/actions

How can I import it into OCAT?

**Comment by ic005k** [comment]
The reason why I took the time to add an "Import" button inside OCAT is to make it easier for users to use the official download of the perfect OC development version of the Zip file from OC.

**Comment by ic005k** [comment]
For example, if you download this file.
https://github.com/acidanthera/OpenCorePkg/suites/5432074279/artifacts/172182740

In OCAT's Sync OC window, there is an "Import" button next to the update source of the OC development version, click this button and select the file you just downloaded.

**Comment by 5T33Z0** [comment]
Ah, ok. Thanks.

**Comment by ic005k** [comment]
Hmm, remember to download this file: macOS XCODE5 Artifacts 
It is the most comprehensive and includes files with Windows and Linux.
