### ISSUE TITLE
关于 OCAuxiliaryTools多版本共存问题和打开Config.plist文件右键提示版本问题

### ISSUE THREAD

**Issue by iaihc** [ic005k/OCAuxiliaryTools#151]
我的电脑上需要 OC077和OC078两个版本共存，我在我的一个文件夹放了一个OC077版本，应用程序目录放OCAuxiliaryTools最新版本，原来的情况是，当我打开OC目录中的Config.plist右键打开的时候，会有版本提示打开工具的版本，可是最近更新全乱套了。

希望管理员，能认真考虑多版本共存问题。

**Comment by ic005k** [comment]
关于你提到的问题，其实OCAT一直都没有刻意地去做这个事情，版本控制系统一直都没做更改，还是原来的版本控制模块。
至于你那边为什么会出现这个现象，最近等我完成手头事情，我会去分析的。

**Comment by ic005k** [comment]
目前，新版的OCAT可以智能适应多个版本的OC，不再存在OCAT和某个OC版本对应的问题了

**Comment by iaihc** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ic005k/OCAuxiliaryTools"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年2月15日(星期二) 上午9:31
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ic005k/OCAuxiliaryTools] 关于 OCAuxiliaryTools多版本共存问题和打开Config.plist文件右键提示版本问题 (Issue #151)





 
目前，新版的OCAT可以智能适应多个版本的OC，不再存在OCAT和某个OC版本对应的问题了
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android. 
You are receiving this because you authored the thread.Message ID: ***@***.***&gt;




亲爱的开发者，在意思和理解上，你可能仍和我的理解有偏差。




假如：我是帮用户远程安装系统，当然，我明白，如果把用户的OC版本也升级同步到最新版本，这没什么问题。

我的电脑上留有大量的不同版本的配置和引导，简单来说，我要编辑OC0.77版本的，和同时编辑另一套OC0.78版本的，我希望你以前开发的支持OC0.77的版本，打开OC0.77的工具，OC0.78打开OC0.78的工具

当打开Config.plist的时候，右键提示能像以前一样。

OCAuxiliaryTools(20220099-OC0.7.7)
OCAuxiliaryTools(20220097-OC0.7.7)

我现在使用的是OC0.77这个202220097这个版本，放在OC0.77版本工具下，把OC0.78的工具放在了应用程序目录，这样右键提示就像上面这两行样式。这里第一行是打开应用程序目录的工具，实际打开的是OC0.78最新版本，第二行打开的是使用OC0.77工具打开的。

我提交的改进意见，希望你把最新的，提示变成：

OCAuxiliaryTools(20220156-OC0.7.8)

OCAuxiliaryTools(20220097-OC0.7.7)

这样显示的。但实际情况是，使用OC0.77工具版本&nbsp;OCAT_Mac 20220135&nbsp;这个版本的时候，如果机器上有两个工具，实际右键菜单只有

OCAuxiliaryTools

这样的提示了，不管使用OCAT_Mac 20220135这个工具还是使用应用程序中的20200156这个版本打开Config工具，实际提示都是OC0.78版本，这样没办法区分打开的版本了。这让我很烦恼

对于开发人员，希望你体谅我吧，帮我想想办法吧。




黑苹果江波

2022年2月15日提交

**Comment by ic005k** [comment]
抱歉，你提到的这个是OCAT的旧理念，OCAT的新理念是一个版本搞定所有的OC
所以，很抱歉地告诉你，这个肯定是回不去了，因为一个OCAT对应一个OC版本那是非常不科学的
目前和将来的OCAT只是内置某个OC的基础版本，已不再和某个OC版本进行绑定了

**Comment by iaihc** [comment]
那更好，我学会适应。那么，这里能提示吗？
如在菜单栏中，选择不同版本，然后联网下载相应版本，如和开发版本一样，适配所有版本。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年2月15日(星期二) 上午9:58
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [ic005k/OCAuxiliaryTools] 关于 OCAuxiliaryTools多版本共存问题和打开Config.plist文件右键提示版本问题 (Issue #151)





 
抱歉，你提到的这个是OCAT的旧理念，OCAT的新理念是一个版本搞定所有的OC
 所以，很抱歉地告诉你，这个肯定是回不去了，因为一个OCAT对应一个OC版本那是非常不科学的
 目前和将来的OCAT只是内置某个OC的基础版本，已不再和某个OC版本进行绑定了
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by ic005k** [comment]
目前，如果你要在OCAT里面使用某个OC版本，在同步OC界面选择版本号，在线获取它就可以了
这是非常科学的方式

**Comment by ic005k** [comment]
在线获取某个OC之后，同步它，你的EFI就到了你选择的OC版本了，非常简单

**Comment by iaihc** [comment]
右键，提示你的&nbsp;版本号总行吧：OCAuxiliaryTools （v20220146&nbsp;OC 0.78）






------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年2月15日(星期二) 上午9:58
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [ic005k/OCAuxiliaryTools] 关于 OCAuxiliaryTools多版本共存问题和打开Config.plist文件右键提示版本问题 (Issue #151)





 
抱歉，你提到的这个是OCAT的旧理念，OCAT的新理念是一个版本搞定所有的OC
 所以，很抱歉地告诉你，这个肯定是回不去了，因为一个OCAT对应一个OC版本那是非常不科学的
 目前和将来的OCAT只是内置某个OC的基础版本，已不再和某个OC版本进行绑定了
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by ic005k** [comment]
这个版本号问题，我肯定会研究的，但不是现在，等我不忙的时候吧，毕竟这是极个别现象，可能需要花些时间
有时候，看起来越是简单的问题，可能解决起来并不那么简单

**Comment by iaihc** [comment]
超级好，一个版本，我测试搞定&nbsp;多个版本，右键提示版本号，请开发人员改下，这个不难。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年2月15日(星期二) 上午10:01
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [ic005k/OCAuxiliaryTools] 关于 OCAuxiliaryTools多版本共存问题和打开Config.plist文件右键提示版本问题 (Issue #151)





 
在线获取某个OC之后，同步它，你的EFI就到了你选择的OC版本了，非常简单
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
