### ISSUE TITLE
目前没有更新可用，或者请检查OpenCore开发版的更新源

### ISSUE THREAD

**Issue by iaihc** [ic005k/OCAuxiliaryTools#156]
当使用最新的版本，更新的时候，会有这提示，这个应该是，https://github.com/dortania/build-repo 下的更新源第一个不是 OpenCore的原因，推荐工具开发人员，能手动定义开发版更新源。或仅本地更新源一次。

**Comment by ic005k** [comment]
这个是可以手动定义的，是允许用户输入数据的。

**Comment by ic005k** [comment]
比如试下这个源：https://github.com/bugprogrammer/HackinPlugins

**Comment by ic005k** [comment]
我记得一开始，OCAT就支持手动定义源，不知道你那边没法手动定义的具体原因，可提供OCAT的版本，我核查一下。

**Comment by ic005k** [comment]
目前，开发版的本地更新源，不再提供了，没多大实际意义，反而增加了维护成本

**Comment by ic005k** [comment]
目前，我还没有发现比较完美的OC开发版更新源，如果你有其它源，不妨推荐一下
其实在最开始设计这个开发版本的更新源时，我的初衷是让用户自己解决这个问题，后来有不少用户问，所以APP里附加了一个源，权当测试使用吧

**Comment by iaihc** [comment]
感谢反馈，不过我已经很满足了，感谢开发人员的努力。每日更新开发版并不必须。希望下次更新软件的时候附带开发版，这样省得更新失败。你们开发工具更新很快，这样已经很好了。

**Comment by iaihc** [comment]
感谢反馈，不过我已经很满足了，感谢开发人员的努力。每日更新开发版并不必须。希望下次更新软件的时候附带开发版，这样省得更新失败。你们开发工具更新很快，这样已经很好了。

**Comment by 505e** [comment]
还是希望下次更新软件的时候附带开发版。
如果自己手工导入的话，是不是可以参照以前一样，在“显示包内容”的相关目录里，加上devDatabase目录？

**Comment by ic005k** [comment]
> 在“显示包内容”的相关目录里，加上devDatabase目录

在你的用户所在的根目录下放入devDatabase目录即可，注意是完整的开发版目录。
OCAT的程序逻辑发生了很大的改变，抱歉的是不会在自带开发版了
其实你在线更新一下开发版，3秒就搞定了，何必手动导入这么麻烦呢

**Comment by ic005k** [comment]
整个过程就3秒钟就完成了，非常非常简单
