### ISSUE TITLE
OCAT Latest versions

### ISSUE THREAD

**Issue by esafeddie** [ic005k/OCAuxiliaryTools#158]
I really don't know what is going on, I don't know if it is a bug within OCAT not being able to get the latest OC nightly version or the problem is with GitHub site. I have tried alternative sites given by OCAT in the drop down list and they are either void or comes up empty. I have spent quite a bit of time trying to figure it out but I am perplex as to why it has gone from a must have to a complex problem. I have given up for the moment after spending a considerable amount of time trying to figure what is going on
![Screenshot 2022-02-17 at 6 23 44 pm](https://user-images.githubusercontent.com/7919587/154552212-b6fbf62f-997f-47e8-a052-da2843f0364b.png)
![Screenshot 2022-02-17 at 6 49 20 pm](https://user-images.githubusercontent.com/7919587/154552253-357b26da-0845-4bf7-b39a-a914b38c1fb0.png)
.

**Comment by ic005k** [comment]
This is a very, very simple and easy problem to solve. Please see here for details: https://github.com/ic005k/OCAuxiliaryTools/issues/150.

**Comment by ic005k** [comment]
And here: https://github.com/ic005k/OCAuxiliaryTools/issues/157

**Comment by ic005k** [comment]
The update source of OC development version is user-defined. Just find an available update source.

**Comment by ic005k** [comment]
There may be some update sources that have not been discovered by us. If you find it, please feel free to share it.

**Comment by esafeddie** [comment]
@ic005k - Problem solved, thanks for pointing me in the right direction.
