### ISSUE TITLE
关于kext源的设置

### ISSUE THREAD

**Issue by k2y1982** [ic005k/OCAuxiliaryTools#159]
![QQ20220218-092710](https://user-images.githubusercontent.com/5109711/154599990-0d546ca2-b27c-4638-9d7f-6fe370a00796.png)
官方源的版本总是要慢一步，我想自己建个仓库，试了一下，默认的网址删除后，一点检查更新，又加回来了。根本没有连接我设置的网址，可能是仓库里路径和文件格式没有按要求来吧？具体路径或文件格式，软件里是怎么要求的呢？

**Comment by k2y1982** [comment]
https://github.com/k2y1982/ASUS-B360M-OpenCore/tree/master/%E9%A9%B1%E5%8A%A8

我仓库里有zip的包。

**Comment by ic005k** [comment]
这个格式就是各个kext驱动的主页，就像OC开发版的更新源一样。
你这个仓库貌似没有发行页面？这对OCAT来说，目前可能是没法下载的
要像这样，比如下面的链接：
https://github.com/acidanthera/Lilu/releases/tag/1.6.0

**Comment by ic005k** [comment]
你如果有时间，还不如建一个完善的OC开发版的仓库，这是目前最缺的一块资源
你可能也发现了，目前的OC开发版的更新源，多多少少都不全面，不少缺少linux文件就是缺少windows文件等等
你如果能建一个跟OC官方提供的开发版一样全面的OC开发版的源，我想肯定会受欢迎的

**Comment by ic005k** [comment]
还有，kexts的最新版，感兴趣的人不多，最感兴趣的是OC的开发版，这个呼声比较高

**Comment by ic005k** [comment]
> 默认的网址删除后，一点检查更新，又加回来了

你可以在这个文件上修改默认网址，具体文件示意如下：
https://github.com/ic005k/OCAuxiliaryTools/blob/master/Database/preset/KextUrl.txt

**Comment by ic005k** [comment]
> 不知道078正式版的.linux放在079开发版里有用没有

如果OC的配置文件结构一旦发生了变化，就不可用了
这些文件都是跟OC的版本紧密相连的
