### ISSUE TITLE
可以考虑做一个检查配置的 GitHub action

### ISSUE THREAD

**Issue by Goooler** [ic005k/OCAuxiliaryTools#160]
如题，是否可以考虑做一个 action 支持在 GitHub 仓库中提交和 PR 的时候检查配置文件，这样可能更方便检查代码？

**Comment by ic005k** [comment]
能否具体一些？
不知道这个有没有实际需求

**Comment by Goooler** [comment]
就是我可以在黑苹果配置文件的仓库里面添加一个 CI 配置，用上这个 action，这个 action 用来检查配置文件是否正确，类似于 OCAT 在本地做的工作。这样会方便仓库的维护者审核 PR 和 push
