### ISSUE TITLE
移除了开发版的检查后，根本没法更新到开发版了

### ISSUE THREAD

**Issue by k2y1982** [ic005k/OCAuxiliaryTools#161]
![QQ20220218-121824](https://user-images.githubusercontent.com/5109711/154616985-ae2904f3-fb09-4518-92a9-0b20f23a7ded.png)
我打开老版本后，同步是灰色的，编辑里也是灰色的，没法更新了。
169里移除没有开发版数据提示可以有，170的不能同步有点头痛。

**Comment by ic005k** [comment]
你用最新的170版本，直接选源就可以了，更加方便了

**Comment by ic005k** [comment]
是灰色的原因，是你没有打开真正的EFI文件夹，你可能只是随便打开了一个plist文件

**Comment by ic005k** [comment]
要有EFI文件夹的文件结构，同步按钮才可以亮起，否则是灰的

**Comment by ic005k** [comment]
切换到开发版后，170版本在同步窗口里面可以直接选源，也可以输入源，比之前的版本要直观很多

**Comment by ic005k** [comment]
要是你打开的文件不在一个EFI结构里面，同步是没有任何意义的，因为OCAT不知道往哪里同步，没有同步目标了，所以是灰的

**Comment by ic005k** [comment]
这个设计应该是非常浅显和直白的，可能还是我设计方面有问题，导致你存在这些疑问？

**Comment by ic005k** [comment]
目前，OCAT的代码总量差不多有两万行了，这么大的代码量，肯定会有很多问题，频繁地更新是为了尽快地修复这些问题
当然，核心问题目前是很少的，都是些小问题，所以请记得一定要随时更新OCAT

**Comment by k2y1982** [comment]
我有点想当然的以为随便点开一个plist，就能更新了。。。没意识到路径的问题。改成/efi/oc 就没问题了。
