### ISSUE TITLE
Airportitlwm Kext update

### ISSUE THREAD

**Issue by dipakvz** [ic005k/OCAuxiliaryTools#164]
Recently you have added link to update Airportitlwm Kext.

out tool is updating to Alpha version of this kext, it should check for last stable version only and kext should update with stable version only.

**Comment by ic005k** [comment]
> kext should update with stable version only.

Yes, for kexts, OCAT only gets the stable version, not the development version or the debug version.

**Comment by ic005k** [comment]
As for the information you gave me, I will look into it later. Thank you.

**Comment by ic005k** [comment]
I did some research. There is nothing wrong with the Url itself. The current version is 2.1.0. Instead, the version of the file in OCAT's database is 2.2.0. I will delete this file from OCAT's database.Moreover, this file is too large, which takes up a lot of space in the database, resulting in the distribution package of OCAT being too large.
