### ISSUE TITLE
数据库的存储位置

### ISSUE THREAD

**Issue by w19996** [ic005k/OCAuxiliaryTools#166]
我发现OCAT会在C:\User\***\文件夹中创建四个文件夹.config,Database,devDatabase和tempocat来存放OCAT的数据，这几个文件夹可不可以放到OCAuxiliaryTools.exe所在的文件夹，OCAT的这些文件夹放到一起也比较方便管理，mac的这些文件夹的位置我还没注意，总之希望这些文件夹，都放到OCAT所在的目录，不知道实现起来容不容易

**Comment by ic005k** [comment]
之前就是放在一起的，那是非常不科学的，饱受诟病，所以最近才下定决心重新设计和规划，目前的这种方式是最科学的。
为什么呢？
1.如果放在一起，每次OCAT更新的时候都会覆盖这些内容，而且在各个平台里面路径长短不一，特别是在Mac里面，那个路径是非常长的，不便管理。
2.Linux下自身的数据库目录不可写，这是Appimage的硬伤。
3.如果你喜欢使用某个版本的OC，比如0.7.5，但OCAT自带的版本为0.7.8，这样每次升级的时候，OCAT都会覆盖你使用的0.7.5的数据库，所以自动产生用户数据库是最合理和科学的。这样无论OCAT如何升级，都不会影响你目前正在使用的OC数据库。

**Comment by ic005k** [comment]
这几个文件夹的作用分别是：
1..config是配置文件目录，这是每个系统的标配。
2.Database,devDatabase分别为OC的用户正式版数据库和开发版数据库，OCAT不会更改这两个目录里面的内容，如果你使用的是OC0.6.3，那么除非你自己更新它，OCAT的升级时不会影响到它的。
3.tempocat这是个临时目录，供OCAT升级和Kext升级使用的，升级完成后OCAT启动的时候会自动删除这个目录。

**Comment by w19996** [comment]
> 这几个文件夹的作用分别是：
> 1..config是配置文件目录，这是每个系统的标配。
> 2.Database,devDatabase分别为OC的用户正式版数据库和开发版数据库，OCAT不会更改这两个目录里面的内容，如果你使用的是OC0.6.3，那么除非你自己更新它，OCAT的升级时不会影响到它的。
> 3.tempocat这是个临时目录，供OCAT升级和Kext升级使用的，升级完成后OCAT启动的时候会自动删除这个目录。
> 

原来是这样，谢谢解答，但是我在windows中在线下载VoodooI2C.kext并不能自动添加进cnofig而且在EFI\OC\Kexts中也没有这个kext的存在，因为以前OCAT数据库中自带这个kext所以能够添加成功，但是我全新下载了最新版，数据库中没有这个kext，所以在线下载，但没有添加成功

**Comment by ic005k** [comment]
之前的老版本OCAT是一个OCAT版本对应一个OC版本，现在新版的OCAT是一个OCAT版本搞定所有的OC版本，真正做到了All in one，这是OCAT的新理念。之前的理念是非常不科学的，你在使用某个版本的OC的时候，还需要找一个与之对应版本的OCAT，非常不人性化，目前的新版OCAT，它总是能智能适应各个版本的OC，你只需要一个OCAT就可以管理不同版本的OC，这是非常科学的，再加上用户数据库的概念，就非常科学合理了。

**Comment by ic005k** [comment]
> 在线下载VoodooI2C.kext并不能自动添加进cnofig而且在EFI\OC\Kexts中也没有这个kext的存在

这是个bug，下个版本将修复它。

**Comment by ic005k** [comment]
我希望你们发现更多的问题，这样OCAT很快就能做到零bug了。

**Comment by w19996** [comment]
> 之前的老版本OCAT是一个OCAT版本对应一个OC版本，现在新版的OCAT是一个OCAT版本搞定所有的OC版本，真正做到了All in one，这是OCAT的新理念。之前的理念是非常不科学的，你在使用某个版本的OC的时候，还需要找一个与之对应版本的OCAT，非常不人性化，目前的新版OCAT，它总是能智能适应各个版本的OC，你只需要一个OCAT就可以管理不同版本的OC，这是非常科学的，再加上用户数据库的概念，就非常科学合理了。

如果在未来OC更改了配置文件结构，增加或减少了某些内容，也会不用更新OCAT而自动适应吗

**Comment by ic005k** [comment]
> 如果在未来OC更改了配置文件结构，增加或减少了某些内容，也会不用更新OCAT而自动适应吗

是的，比如目前的开发版0.7.9新增了内容，OCAT就已经智能适应了，OCAT并没有为0.7.9专门做针对性的升级。
你可以在OC的正式版和开发版来回切换一下就能体会到，而且这个自适应是实时的，不用重新再启动OCAT。

**Comment by w19996** [comment]
> 我希望你们发现更多的问题，这样OCAT很快就能做到零bug了。

HoRNDIS9.2.kext在GitHub是pkg，EFICheckDisabler.kext是我在国外论坛上找到的，这两个也不大，能不能放到数据库中

**Comment by w19996** [comment]
> > 如果在未来OC更改了配置文件结构，增加或减少了某些内容，也会不用更新OCAT而自动适应吗
> 
> 是的，比如目前的开发版0.7.9新增了内容，OCAT就已经智能适应了，OCAT并没有为0.7.9专门做针对性的升级。
> 你可以在OC的正式版和开发版来回切换一下就能体会到，而且这个自适应是实时的，不用重新再启动OCAT。

那就太棒了！

**Comment by ic005k** [comment]
> HoRNDIS9.2.kext在GitHub是pkg，EFICheckDisabler.kext是我在国外论坛上找到的，这两个也不大，能不能放到数据库中

采用新方式重新分发它即可，因为目前已经没人维护OCAT自带的数据了，OCAT自带的数据库将越来越老旧。

**Comment by ic005k** [comment]
> 那就太棒了！

目前OCAT里面可以下载使用从0.6.2到最新版

**Comment by ic005k** [comment]
> HoRNDIS9.2.kext在GitHub是pkg，EFICheckDisabler.kext

如果你有时间，可在你的github上分发它，并将它的网址放入OCAT的Kexts列表里面就可以自动在线获得它了，这就是新方式。
你随时都可以维护这个文件，其实之前OCAT数据库里面自带的Kexts很多都是N年前的东西，没时间维护和更新它，所以目前采用在线的方式更科学。

**Comment by ic005k** [comment]
还有，比如你的机型的USB的定制等等，你都可以通过GitHub分发它，之后再放到OCAT的Kexts网址列表里，分享给其他用户。

**Comment by w19996** [comment]
> 还有，比如你的机型的USB的定制等等，你都可以通过GitHub分发它，之后再放到OCAT的Kexts网址列表里，分享给其他用户。

明白了，谢谢，在线更新确实更好

**Comment by ic005k** [comment]
我主要是没太多时间，我做了个HoRNDIS的分发例子，https://github.com/ic005k/HoRNDIS
Kexts升级网址分别填写：
HoRNDIS9.2.kext      https://github.com/ic005k/HoRNDIS
你以后就这样做可以了，很简单。

**Comment by w19996** [comment]
> 我主要是没太多时间，我做了个HoRNDIS的分发例子，https://github.com/ic005k/HoRNDIS Kexts升级网址分别填写： HoRNDIS9.2.kext https://github.com/ic005k/HoRNDIS 你以后就这样做可以了，很简单。

好的，我也刚把我机型所需的一些kext做好

**Comment by ic005k** [comment]
好，可随时推送给我，如果你有足够的时间，OCAT的Kexts升级网址的管理希望你多参与

**Comment by w19996** [comment]
> 好，可随时推送给我，如果你有足够的时间，OCAT的Kexts升级网址的管理希望你多参与

好的，没问题

**Comment by ic005k** [comment]
嗯嗯，我回头有时间的话，会重新设计下OCAT的Kexts升级网址管理，比如加上搜索功能、过滤器等等

**Comment by w19996** [comment]
> 嗯嗯，我回头有时间的话，会重新设计下OCAT的Kexts升级网址管理，比如加上搜索功能、过滤器等等

那就更方便了，越来越完美

**Comment by londbell** [comment]
我需要运行两个ocat（在两个文件夹里）来对比不同的efi配置，蛋疼的是这两个efi的oc版本不一样，按照现在ocat config的位置，每次我变更oc版本，另外一个ocat会一样迁移过去；为什么不把config放置在ocat文件下面，这样是不是更好一些呢

**Comment by ic005k** [comment]
> 我需要运行两个ocat（在两个文件夹里）来对比不同的efi配置

无需运行多个OCAT,只需在现有的OCAT上新建窗口（文件主菜单下）即可对比多个配置文件。

**Comment by londbell** [comment]
> > 我需要运行两个ocat（在两个文件夹里）来对比不同的efi配置
> 
> 无需运行多个OCAT,只需在现有的OCAT上新建窗口（文件主菜单下）即可对比多个配置文件。

我知道可以新建窗口，但这样不是我想使用的场景。我要对比的两份config的OC版本是不同的，所以我找到了一个办法来绕过home的config，这样也足够了，应该只有我才有这种小众需求

![Snipaste_2023-12-10_16-57-33](https://github.com/ic005k/OCAuxiliaryTools/assets/7590762/0ce52ac7-d8d6-437c-9c20-b9d2d2914be9)
