### ISSUE TITLE
kexts更新问题

### ISSUE THREAD

**Issue by w19996** [ic005k/OCAuxiliaryTools#168]
![截屏2022-02-20 下午12 55 20](https://user-images.githubusercontent.com/54472022/154828972-c432656c-e6c7-46ba-9d71-b8d07d42f47b.png)
这个页面，点击下载所有的kext到用户数据库，每次下载到第二个都会提示网络或网址错误，我把第二个链接删掉，下面的kext也有的会这样提示，应该不是网络的问题，因为并不是所有的都这样提示，但我看了下链接也应该没有问题啊

**Comment by w19996** [comment]
我的配置需要用到VoodooI2CHID.kext，但是在kext升级网址里加上VoodooI2CHID.kext的链接https://github.com/VoodooI2C/VoodooI2C每次更新到VoodooI2CHID.kext就会提示网络或网址错误，这个链接应该是没错的吧和VoodooI2C.kext的链接一样，但更新VoodooI2C.kext时就不会报错

**Comment by w19996** [comment]
![1](https://user-images.githubusercontent.com/54472022/154830051-fca917e8-a7f8-4736-a9e0-b11071ebb98e.png)
还有这里，不同的颜色代表什么意思色

**Comment by ic005k** [comment]
VoodooI2C已经包含了有VoodooI2CHID.kext，所以你不用单独为VoodooI2CHID.kext再提供网址了
这些颜色分别代表OC的核心文件、驱动文件、工具，这三种类型的文件

**Comment by w19996** [comment]
> VoodooI2C已经包含了有VoodooI2CHID.kext，所以你不用单独为VoodooI2CHID.kext再提供网址了 这些颜色分别代表OC的核心文件、驱动文件、工具，这三种类型的文件

我需要用到BlueToolFixup.kext但用不到BrcmPatchRAM.kext，而BrcmPatchRAM又包含了BlueToolFixup.kext，但kextsurl有BrcmPatchRAM.kext没有BlueToolFixup.kext，这种情况怎么办

**Comment by ic005k** [comment]
> 我需要用到BlueToolFixup.kext但用不到BrcmPatchRAM.kext，而BrcmPatchRAM又包含了BlueToolFixup.kext，但kextsurl有BrcmPatchRAM.kext没有BlueToolFixup.kext，这种情况怎么办

你添加它们的网址，有重复不要紧，OCAT应该能自动识别的，你试下

**Comment by w19996** [comment]
> > 我需要用到BlueToolFixup.kext但用不到BrcmPatchRAM.kext，而BrcmPatchRAM又包含了BlueToolFixup.kext，但kextsurl有BrcmPatchRAM.kext没有BlueToolFixup.kext，这种情况怎么办
> 
> 你添加它们的网址，有重复不要紧，OCAT应该能自动识别的，你试下

VoodooI2CHID.kext我是添加了网址的，但每次更新到VoodooI2CHID.kext就会提示网络或网址错误，BlueToolFixup.kext我也添加了，BlueToolFixup.kext可以更新，但是我在下载所有的kext但用户数据库这个选项中BrcmPatchRAM.kext好像又是不能更新的，会提示错误

**Comment by ic005k** [comment]
> VoodooI2CHID.kext我是添加了网址的，但每次更新到VoodooI2CHID.kext就会提示网络或网址错误

这个不用添加，删除它，否则有冲突

至于BrcmPatchRAM.kext我回头试下看

**Comment by ic005k** [comment]
我试了下BrcmPatchRAM.kext是可以更新的
你打开tempocat目录，里面可以看到哪些文件被下载下来了

**Comment by w19996** [comment]
> > VoodooI2CHID.kext我是添加了网址的，但每次更新到VoodooI2CHID.kext就会提示网络或网址错误
> 
> 这个不用添加，删除它，否则有冲突
> 
> 至于BrcmPatchRAM.kext我回头试下看

你可以在偏好设置中试一下下载所有的Kext到用户数据库，不知道为什么我这里有好多kext都会提示网络或网址错误

**Comment by ic005k** [comment]
好的，我一会儿试下

**Comment by ic005k** [comment]
你选择爬取网页源代码的模式看看，访问API有次数限制，应该就是这个原因

**Comment by ic005k** [comment]
访问API每小时的次数不能太多，否则就不让你连接了
如果大量更新，最好选择爬取网页源代码，这个没有任何限制

**Comment by w19996** [comment]
> 访问API每小时的次数不能太多，否则就不让你连接了
> 如果大量更新，最好选择爬取网页源代码，这个没有任何限制

好的

**Comment by w19996** [comment]
> 访问API每小时的次数不能太多，否则就不让你连接了
> 如果大量更新，最好选择爬取网页源代码，这个没有任何限制

确实换成爬取网页源代码模式好多了，但还有一些报错

**Comment by ic005k** [comment]
我刚才测试了一下，除了你添加的VoodooI2CHID.kext有问题，其它都正常。
OCAT最新的178版本

**Comment by ic005k** [comment]
VoodooI2CHID.kext下个版本中删除它就可以了

**Comment by w19996** [comment]
> 我刚才测试了一下，除了你添加的VoodooI2CHID.kext有问题，其它都正常。
> OCAT最新的178版本

那可能是我网络问题了，VoodooI2CHID.kext刚才我提交PR删了

**Comment by ic005k** [comment]
如果在国内，安装这个可稳定访问github：https://gitee.com/docmirror/dev-sidecar

**Comment by w19996** [comment]
> 如果在国内，安装这个可稳定访问github：https://gitee.com/docmirror/dev-sidecar

好的，我试一下

**Comment by ic005k** [comment]
完美，目前来说好像也没什么东西要做的了

**Comment by w19996** [comment]
> 完美，目前来说好像也没什么东西要做的了

数据库生成EFI后，如果有缺少的kext可以加个按钮跳转到kext更新页面去

**Comment by ic005k** [comment]
> 数据库生成EFI后，如果有缺少的kext可以加个按钮跳转到kext更新页面去

这个可以考虑，先记下来
有什么想法或创意可随时留言
