### ISSUE TITLE
Update Kext to Dev Version

### ISSUE THREAD

**Issue by mateusangelo** [ic005k/OCAuxiliaryTools#169]
On the version 20220177 i can't update the kext for the dev version... When change to development version, 
It would be interesting to migrate the kext to the development version.
I don't remember exactly, but in a previous version it updated the kext to the dev version.

**Comment by ic005k** [comment]
OCAT has never been able to update Kexts to DEV version. Previously, there was a bug in OCAT's database, and the file was wrong.The DEV version of Kexts doesn't seem to be of great interest to users, and there is no website for automatic download.Therefore, OCAT does not have this function at present.

**Comment by mateusangelo** [comment]
ok,
