### ISSUE TITLE
Please move working directories to a grouped location instead of user's Home directory

### ISSUE THREAD

**Issue by mackonsti** [ic005k/OCAuxiliaryTools#172]
Hello @ic005k and thanks for your continuing work.

Please, is it possible to group the downloaded/created folders for use by OCAuxiliaryTools to a nice location that is indicative of the tool as well as easy to clean-up/remove when eneded?

I see that there are folders such as "Database" and "devDatabase" created in my home folder which is not _my_ preference.

I see that your tool creates a folder in `~/.config/OCAuxiliaryTools/` for its `OCAuxiliaryTools.ini` file.

I can think of a couple folders suggestions, that could be easily recognisable and possibly removed via some menu (for a clean restart?)

Possible folder to consider:

1. A hidden folder on user's home directory such has `.ocat` or `.ocauxiliarytols` and inside you place those two database folders.

2. Or a folder inside an (existing) folder on user's home directory such has `.local/share/` then `OCAuxiliaryTools` for your database files, inside.

This `.local/share/` folder is created by some other software too and it's likely it also exists on the user's home directory.

This is of course if you want to avoid creating an official path, like all Mac software, in the user's Library and Application Support folders i..e `~/Library/Application Support/OCAuxiliaryTools/`

Together with the database folder you can include a temporary folder for the updates of the tool (not sure where you store it, today?)

I remain available for any comments or information, **thank you for your consideration.**

**Comment by ic005k** [comment]
The folders used by OCAT are described in great detail here. Please see here: https://github.com/ic005k/OCAuxiliaryTools/issues/166.

**Comment by ic005k** [comment]
I am very glad to see your professional advice, but I really don't know how to put these folders better. It is not only convenient for users to open and use, but also beautiful. At the same time, it has consistent performance under Windows, Mac and Linux systems.OCAT is a cross-platform APP, so please give me your most professional advice, thank you very much.

**Comment by mackonsti** [comment]
Hi @ic005k thanks, I did not see #166 as I do not speak the language.

However, is there _no way_ to detect MacOS version of the app, and set a "source" or "base" path for all files involved? This means, you set a start path and after that, anything added goes under that main base folder/path.

I am not sure how Qt works to be honest, perhaps some tweaking or reading is necessary. But other Qt applications such as **AviDeMux** seem to use such a path on user space, namely `.avidemux` on user's home path (on MacOS).

"Officially" any support files are supposed to go to `~/Library/Application Support/` + name of tool, as you know. But there are some other tools for Hackintosh that bypass this, obviously.

How does it work in Windows? You create these folders under `C:\Users\MacKonsti\` for example?

Please, I suggest you try to discover the way to change these locations _if you have some free time to study_ and once you can move these for the MacOS release, I would be more than happy to discuss or propose a more 'clean' location. What do you think? 😄 

Many thanks.

**Comment by ic005k** [comment]
As you said, if OCAT is only for Mac, then I will place these folders in the standard way of Mac.But the headache is to consider Windows and Linux, especially Linux. If OCAT plans folders for these three platforms separately, I believe I have absolutely no strength to maintain them. For me, easy maintenance is a very important thing.I believe you definitely have a good idea. Look forward to it.

**Comment by ic005k** [comment]
It doesn't matter. When you have a good idea, you can always tell me. Thank you.Or you can use OCAT under Windows and Linux to see if there is a better way to place these folders.I am willing to listen to any suggestions you have. Thank you.

**Comment by ic005k** [comment]
@5T33Z0 is an experienced IT practitioner. I want to listen to his opinions. Welcome @5T33Z0 to join this discussion.Or any user who has any opinions about this can join this discussion, especially the users of Linux community. Thank you.

**Comment by 5T33Z0** [comment]
I just accidentally by accident that OCAT creates the "Database" and "devDatabase" Folders in the Home Folder now in macOS. And I am not a fan of it either and got to side with @mackonsti  on the matter. That's what the Application Support Folder is for. Either that or in the App Package Folder instead (as it was before). 

Anyway, in my experience with macOS, `~/Library/Application Support/OCAuxiliaryTools/` is the way to go in macOS. As for other OSes, I don't know. In Windows, I think  `C:\Users\{Your User Name}\AppData\Roaming` is used for that. 

By the way: I am NOT an IT expert, nor working in IT.

**Comment by ic005k** [comment]
> 1. A hidden folder on user's home directory such has `.ocat` or `.ocauxiliarytols` and inside you place those two database folders.

I decided to take your advice and use “.ocat” in the home directory, which can balance all systems. Thank you very much for your advice.

**Comment by mackonsti** [comment]
Thank you for listening and being open to suggestions.
I think an added feature would be to check for the existing locations and move all inside?
This is so that next update that implements the folder `.ocat` in the home directory does not leave behind residual files/folders such as `Database` and `devDatabase` etc. 😄 
Just a thought....

**Comment by ic005k** [comment]
> Thank you for listening and being open to suggestions. I think an added feature would be to check for the existing locations and move all inside? This is so that next update that implements the folder `.ocat` in the home directory does not leave behind residual files/folders such as `Database` and `devDatabase` etc. 😄 Just a thought.... Moreover, a menu entry to "clean" database would also come handy, if you think this is needed (it will delete folders and restart app, maybe?)

For the commercial APP I work in, I often do this. I will do an automatic data migration so that the user's previous data can smoothly transition to the new directory.But for an open source APP, the main function is perfect, and other details don't need to be considered so carefully.

**Comment by ic005k** [comment]
> There was also another one I found called "tempocat"

This directory is a temporary directory for upgrading and downloading, and OCAT will automatically delete it the next time it starts.

**Comment by ic005k** [comment]
@mackonsti @5T33Z0 Welcome to provide more good ideas, thank you.

**Comment by mackonsti** [comment]
> I will do an automatic data migration so that the user's previous data can smoothly transition to the new directory.

Just remember that not everyone updates when you push a new version so this "migration" should happen for some time more, I mean, leave it as part of the app for some more time. Thanks

**Comment by chriswayg** [comment]
I likewise think, that “.ocat” in the home directory is a good location for these files.

> ic005k wrote:
> For the commercial APP I work in, I often do this. I will do an automatic data migration so that the user's previous data can smoothly transition to the new directory.But for an open source APP, the main function is perfect, and other details don't need to be considered so carefully.

@ic005k I actually agree that automatic migration of data for a hackintosh app is not a necessary feature. We all know how to remove directories that are not used any more. Testing this migration feature across three platforms seems an unnecessary hassle burdening the developer. 

Just write a note on the Github repo page Readme once certain directories are not used any more, that they can be deleted.
