### ISSUE TITLE
Online AMD information link is dead

### ISSUE THREAD

**Issue by fabiosun** [ic005k/OCAuxiliaryTools#188]
Hi @ic005k 
we changed name of online AMD instruction file
It need to be updated in app
Now if you click on online button it has a 404 not found error page
<img width="325" alt="Screenshot 2022-02-21 at 9 01 43 AM" src="https://user-images.githubusercontent.com/6358373/154912975-202eb979-817b-4223-b46c-f30a1a6848d7.png">

**Comment by ic005k** [comment]
Okay, received.

**Comment by fabiosun** [comment]
Thank you
