### ISSUE TITLE
UEFI UI Scale

### ISSUE THREAD

**Issue by fabiosun** [ic005k/OCAuxiliaryTools#197]
Hello @ic005k 
From some recent Opencore releases UIScale parameter has changed its position from **NVRAM/4D1EDE05-38C7-4A6A-9CC6-4BCCA8B38C14** to **UEFi/Output** config.plist section:

<img width="739" alt="Screenshot 2022-02-27 at 9 10 15 AM" src="https://user-images.githubusercontent.com/6358373/155874402-230f90de-7724-4c3c-9e43-f46d86c6e10b.png">

In Nvram OCAT preset it maintains old position (NVRAM/4D1EDE05-38C7-4A6A-9CC6-4BCCA8B38C14)
![UISCALE-Nvram](https://user-images.githubusercontent.com/6358373/155874386-026feccf-ee6e-421e-bfb5-cd51e0d19c2c.jpg)

**Comment by ic005k** [comment]
Thanks for reminding me.
There is an "edit preset file" in the "edit" menu of OCAT. If you have time, you can also participate in editing and modifying preset files. Thank you.

**Comment by ic005k** [comment]
This preset file is actually stripped out of the Config.plist file.
In fact, I really don't know how many people are using these presets, it seems to me that users are not interested in these presets?

**Comment by ic005k** [comment]
By the way, the "Kernel" inside can be ignored, it is now an independent module.

**Comment by fabiosun** [comment]
Personally for me it is not useful, but I am trying to build a config.plist from scratch and I am using all options your app has to build a new config.plist (comparing with 078 release of Opencore)

**Comment by fabiosun** [comment]
I also do not understand these two:
<img width="775" alt="Screenshot 2022-02-27 at 10 55 25 AM" src="https://user-images.githubusercontent.com/6358373/155877729-eb6de9b5-2342-4b37-9e22-48710eab7e7e.png">

without any properties declared

**Comment by ic005k** [comment]
There is no need to declare an attribute. Its format is:
xxx1 ｜ xxx2
xxx1 is an attribute of a device.
xxx2 is a description of this attribute.

**Comment by ic005k** [comment]
I don't think you need to spend time on it because I don't think many people use it.Later, OCAT may also remove this preset function.
