### ISSUE TITLE
未启用？

### ISSUE THREAD

**Issue by Lostiz** [ic005k/OCAuxiliaryTools#204]
![image](https://user-images.githubusercontent.com/99953892/156758450-b774e217-b871-4467-b829-ef562eb427e0.png)
灰色块如何解决？

**Comment by ic005k** [comment]
灰色代表Kexts升级网址里面没有这个kext的网址。
你自己在偏好设置里面添加它的网址就可以了。

**Comment by ic005k** [comment]
OCAT罗列的kexts网址只是常见的，并没有覆盖到所有的kext，没有的，你可以自己添加。

**Comment by Lostiz** [comment]
好的谢谢了
