### ISSUE TITLE
关于更新数据库

### ISSUE THREAD

**Issue by w19996** [ic005k/OCAuxiliaryTools#205]
在更换数据库的OC版本时，如果数据库中没有对应的版本，要先打开一个EFI文件，或者先生成一个EFI文件，然后才能点击"升级OpenCore和Kexts“按钮来更新数据库，可不可以设置一个单独的按钮，或者更改一下逻辑，不需要先打开一个EFI文件才能点击这个按钮来更新数据库，因为我比较喜欢直接打开OCAT而不是通过双击config.plist来打开OCAT

**Comment by ic005k** [comment]
这是肯定可以改变的，目前只是时间有限，为了省事，将这些东西和OC同步放在了一起，后面可能会做些改变的，比如分开它们等等。
如果你有好的创意，也可以详细说下，直接给出UI交互上的设计建议。

**Comment by w19996** [comment]
在工具栏设置一个单独的按钮”更改OpenCore版本“点击之后弹出一个窗口显示这两部分内容
![截屏2022-03-04 20 48 55](https://user-images.githubusercontent.com/54472022/156766743-3b2c560f-4fe8-47b7-a73c-f8461644344e.png)
![截屏2022-03-04 20 48 01](https://user-images.githubusercontent.com/54472022/156766757-bcfa64c3-73d9-4970-a4f3-0037a4737552.png)

**Comment by ic005k** [comment]
你提的这种方案我有考虑过，当然是可以的。
但有一个问题就是，OC同步窗口里面同样要重复一个这样的设置，为什么呢？
因为很多用户的使用习惯是选择或更新OC版本后，会有一个同步的步骤，如果将选择或更新OC的版本和同步窗口分开的话，
这样很多用户又会觉得这不是一个一气呵成的过程。
因为OCAT的设计理念是管理EFI文件夹，所以所有的动作都是围绕EFI这个目录结构来展开的。
如果不判断EFI目录结构的完整性，那么升级kexts的来源和同步OC的目标将不可知。
当然这个EFI目录并不一定指你正在使用的ESP分区里面的EFI，它是指任何一个EFI，比如桌面、我的文档等等位置。

**Comment by ic005k** [comment]
我目前测试OCAT的习惯是，我会老是自动打开比如桌面上某个EFI文件夹里面的配置文件，用它来进行测试。
自动打开只需在偏好设置里面勾上“自动打开上次打开的文件”即可。

**Comment by ic005k** [comment]
还有，我后面的开发计划是使OCAT变得越来越简单，不增加任何多余的功能，更近一步地优化现有的UI和用户交互。
总之，它将来会简单的不能再简单。

**Comment by ic005k** [comment]
当然，也希望你们随时提供各种想法和创意

**Comment by w19996** [comment]
> 我目前测试OCAT的习惯是，我会老是自动打开比如桌面上某个EFI文件夹里面的配置文件，用它来进行测试。
> 自动打开只需在偏好设置里面勾上“自动打开上次打开的文件”即可。

我的习惯是直接打开OCAT更改OC版本(导入开发版压缩包），然后再去打开配置文件，所以感觉不能直接更改OC版本不方便

**Comment by ic005k** [comment]
> 我的习惯是直接打开OCAT更改OC版本(导入开发版压缩包），然后再去打开配置文件，所以感觉不能直接更改OC版本不方便

这个问题已记录，不过在没有找到特别理想的方案之前，可能会一直维持目前的操作过程，就是先打开EFI里面的配置文件，再升级或者选择OC版本。
同时，如果其他用户看到这里，我也想听听他们的意见。

**Comment by ic005k** [comment]
该问题已解决，请升级到最新的版本，有任何问题，可随时发帖。
