### ISSUE TITLE
OC 0.7.9

### ISSUE THREAD

**Issue by ahnaf2012** [ic005k/OCAuxiliaryTools#207]
Needs to be updated for OpenCore version 0.7.9

**Comment by ic005k** [comment]
This is no longer necessary, as OCAT has adopted intelligent adaptation, as described here.
https://github.com/ic005k/OCAuxiliaryTools/issues/195

**Comment by ic005k** [comment]
In "Upgrade OC and Kexts UI", you only need to select "Latest Version", then "Get OpenCore", it will automatically update to OC0.7.9, and intelligently adapt to the parameters of 0.7.9.
Then you sync OC and save the Config.plist and you're done.

**Comment by chriswayg** [comment]
> In "Upgrade OC and Kexts UI", you only need to select "Latest Version", then "Get OpenCore", it will automatically update to OC0.7.9, and intelligently adapt to the parameters of 0.7.9. Then you sync OC and save the Config.plist and you're done.

This is really cool? How does it do this?

I was also wondering, if something was wrong, because the way the app works in this regard had changed. - 
I will add that to the documentation, as its not immediately obvious when looking for 0.7.9.

**Comment by ic005k** [comment]
> This is really cool? How does it do this?
> 
> I was also wondering, if something was wrong, because the way the app works in this regard had changed: It was not immediately obvious to me when looking for 0.7.9.
> 
> I have already added your explanation to the documentation.

This is a very scientific way, it solves the errors that can be brought by manual processing, please believe that this is the right way.
It is a very good idea to add this operation inside the OCAT document you wrote, and thanks again for your contribution to OCAT.

**Comment by amervelic** [comment]
> In "Upgrade OC and Kexts UI", you only need to select "Latest Version", then "Get OpenCore", it will automatically update to OC0.7.9, and intelligently adapt to the parameters of 0.7.9. Then you sync OC and save the Config.plist and you're done.
not true latest version is 0.7.8 and not 0.7.9

**Comment by ic005k** [comment]
> not true latest version is 0.7.8 and not 0.7.9

Sorry, I didn't quite see your point.
In the OpenCore version drop-down list box, there are many OC versions to choose from, such as 0.6.2, 0.7.5, the first entry is "Latest Version", you check this, then get OpenCore, you will get the latest version of OpenCore. I don't know if you can understand this.

**Comment by Vorshim92** [comment]
You have to select Latest Version and then click on Get Opencore to update to 0.7.9 
![image](https://user-images.githubusercontent.com/7747380/159178365-960be202-3ccb-4587-bbe3-bbbb13defbea.png)
