### ISSUE TITLE
OCS: Missing key LogModules, context <Debug>! Serialisation returns 1 error!

### ISSUE THREAD

**Issue by ghsssss** [ic005k/OCAuxiliaryTools#209]
这是我升级oc0.7.9的报错，不知道咋解决

**Comment by ghsssss** [comment]
@ic005k

**Comment by ghsssss** [comment]
[config.plist.zip](https://github.com/ic005k/OCAuxiliaryTools/files/8205876/config.plist.zip)
这是我的config

**Comment by ic005k** [comment]
参见这个帖子：https://github.com/ic005k/OCAuxiliaryTools/issues/207

**Comment by ic005k** [comment]
在“升级 OC 和 Kexts UI”中，只需选择“最新版本”，然后选择“获取 OpenCore”，就会自动更新到 OC0.7.9，并智能适配 0.7.9 的参数。
然后你同步 OC 并保存 Config.plist，完成。

**Comment by ic005k** [comment]
你检查下上面的步骤，非常简单

**Comment by ic005k** [comment]
你是不是没有保存配置文件呢？
保存一下配置文件，这个提示就会自动消失了

**Comment by ghsssss** [comment]
老哥，我肯定是点完保存报的错误呀- - @ic005k

**Comment by ic005k** [comment]
> 点完保存报的错误

可能是你OC数据库没有升级到0.7.9，先升级OC数据库到0.7.9看看？

**Comment by ic005k** [comment]
如果还是不行的话，那就奇怪了，其实也没什么呀，过程非常简单的

**Comment by ghsssss** [comment]
https://bbs.pcbeta.com/viewthread-1922875-1-1.html
