### ISSUE TITLE
建议"包含Resources目录"设置为默认未选中，或者可以记住选中状态

### ISSUE THREAD

**Issue by w19996** [ic005k/OCAuxiliaryTools#210]
如果用OCAT来升级正在使用的EFI的话，一般都是有自己的主题的，而包含Resources目录默认是选中的，如果不小心没有取消勾选，那么点击同步的时候，自己的主题也被替换了

**Comment by ic005k** [comment]
ok，下个版本将改为记忆选择状态

**Comment by ic005k** [comment]
已更新。
