### ISSUE TITLE
OCAT detected by Windows 11 as potential security threat

### ISSUE THREAD

**Issue by 5T33Z0** [ic005k/OCAuxiliaryTools#213]
![Screenshot 2022-03-12 132357](https://user-images.githubusercontent.com/76865553/158017891-294913d2-8f1d-4ba4-aabc-fa2ea588288d.png)

**Comment by ic005k** [comment]
There is nothing wrong with this, see here for details.
https://github.com/ic005k/OCAuxiliaryTools/issues/106
