### ISSUE TITLE
OCat param

### ISSUE THREAD

**Issue by adirrenato** [ic005k/OCAuxiliaryTools#214]
Why in DeviceProperties doesn't have Boolean in Data Type?

**Comment by ic005k** [comment]
Currently, as far as I know, it seems that Boolean variables are not used in device properties.
But this needs further confirmation that the variable is really needed inside the device properties.
No user has ever mentioned this issue before, so I'll keep an eye on it.

**Comment by adirrenato** [comment]
I was following this link https://dortania.github.io/OpenCore-Install-Guide/extras/spoof.html#windows-gpu-selection

Propertree exemple 
![ProperTree](https://user-images.githubusercontent.com/100114552/158870537-010d593a-5e17-4386-bf4a-e6ea5667cf8e.png)

Sorry my bad English! :(

**Comment by ic005k** [comment]
Oh, understand.
Instead of using a boolean variable directly in general, it can be implemented in the following form, e.g.
 | disable-external-gpu | Data | 01000000 |

**Comment by adirrenato** [comment]
All right, thank you. It's working!
