### ISSUE TITLE
Auto Column Width problem

### ISSUE THREAD

**Issue by fabiosun** [ic005k/OCAuxiliaryTools#216]
https://user-images.githubusercontent.com/6358373/159006892-ff68835b-6e8f-411c-a8c5-b18f8e292ed4.mp4

@ic005k a little problem in OSX app

**Comment by ic005k** [comment]
Oh, for the single column, it's fixed and can't be changed.
It's not a bug, it's part of the program's design philosophy. I may make adjustments to this.
