### ISSUE TITLE
建议一个小改进

### ISSUE THREAD

**Issue by w19996** [ic005k/OCAuxiliaryTools#217]
![截屏2022-03-18 21 50 41](https://user-images.githubusercontent.com/54472022/159015423-6fe98fdf-4d22-4efc-b7eb-af41cb373571.png)
建议在这个页面右半部分也增加一个右击预置选项，来单独增加一些键值

**Comment by ic005k** [comment]
这个功能是有的，但不是非常完善
比如你选中“7C436110-AB2A-4BBB-A880-FE41995C9F82”，在右边的“+”键上单击鼠标右键，就出来内容了。
不过，貌似用户们对预置不怎么感兴趣，几乎都不用这些功能，我也不知道为什么。所以预置功能一直保留，但也不再做过多的内容了。

**Comment by w19996** [comment]
> 这个功能是有的，但不是非常完善
> 比如你选中“7C436110-AB2A-4BBB-A880-FE41995C9F82”，在右边的“+”键上单击鼠标右键，就出来内容了。
> 不过，貌似用户们对预置不怎么感兴趣，几乎都不用这些功能，我也不知道为什么。所以预置功能一直保留，但也不再做过多的内容了。

明白了
