### ISSUE TITLE
请更新 OpenCore0.80开发版新添加的参数

### ISSUE THREAD

**Issue by iaihc** [ic005k/OCAuxiliaryTools#219]
请更新 OpenCore0.80开发版新添加的参数

**Comment by ic005k** [comment]
现在都是智能添加的，你只需获取最新的0.8.0开发版，保存配置文件即可

**Comment by ic005k** [comment]
OCAT早都改为全智能的方式，不再采用和某个OC版本挂钩的非常不科学的实施方式

**Comment by ic005k** [comment]
也就是说，OCAT几乎可以不用升级了，它完全自适应当前、过去或将来的OC版本
