### ISSUE TITLE
EFI文件夹内OC版本检测

### ISSUE THREAD

**Issue by w19996** [ic005k/OCAuxiliaryTools#220]
如果打开的EFI文件夹与内OC的版本与OCAT数据库内版本不对应，是不是可以考虑增加一个弹窗提示，以防止用户只更改了配置文件而没有更新对应的OC主程序

**Comment by ic005k** [comment]
这个功能其实我早就想做，但一直受限，没法精准实现它。
为什么呢？因为OC并不提供静态版本显示功能，也就是说，如果OC不运行，目前来说你是无法精确知道它的版本。
简单点讲，就是你无法从OC提供的现有文件中，查询到它们的版本信息，所以你提到的这个功能暂时就无法完美实现了。
如果OC弄一个比如文本文件来显示OC的版本，那这个事情就很好办了，APP直接查询这个文本文件的内容就可以知道目前OC的版本号了。
如果你有好的创意或想法，可随时留言。

**Comment by w19996** [comment]
> 这个功能其实我早就想做，但一直受限，没法精准实现它。
> 为什么呢？因为OC并不提供静态版本显示功能，也就是说，如果OC不运行，目前来说你是无法精确知道它的版本。
> 简单点讲，就是你无法从OC提供的现有文件中，查询到它们的版本信息，所以你提到的这个功能暂时就无法完美实现了。
> 如果OC弄一个比如文本文件来显示OC的版本，那这个事情就很好办了，APP直接查询这个文本文件的内容就可以知道目前OC的版本号了。
> 如果你有好的创意或想法，可随时留言。
> 

就是必须用OC启动系统才能检测OC的版本，对吧

**Comment by ic005k** [comment]
> 就是必须用OC启动系统才能检测OC的版本，对吧

是的，截至目前是这样的。
