### ISSUE TITLE
New Dictionary `Misc/Serial` in latest OC build

### ISSUE THREAD

**Issue by 5T33Z0** [ic005k/OCAuxiliaryTools#221]
![Bildschirmfoto 2022-04-01 um 06 15 13](https://user-images.githubusercontent.com/76865553/161194315-11f749eb-615b-4ff8-b176-21b217f51eb1.png)

OCAT can't handle it and returns config errors. I think an update is necessary to integrade it.

**Comment by ic005k** [comment]
Okay, I will update it.
