### ISSUE TITLE
Newer versions of OC 0.7.9 and greater

### ISSUE THREAD

**Issue by irishetcher** [ic005k/OCAuxiliaryTools#223]
Hi,

This isn't an issue as such but when I open OCAT it doesn't seem detect that OC 0.7.9 has been released since 7th March. The latest in the drop down select is 0.7.8. Does this mean that this tool is no longer supported?

**Comment by fabiosun** [comment]
<img width="225" alt="Screenshot 2022-04-14 at 4 17 15 PM" src="https://user-images.githubusercontent.com/6358373/163409776-10f2dd9d-5241-45f8-8cb5-bba9d84917fc.png">
light up this as shown in picture
then click on get open core

**Comment by irishetcher** [comment]
Cheers,  I was having one of blank moments and just looking for numbers.

**Comment by fabiosun** [comment]
hi
doing as I said before updates your database (open core) then then you reopen OCAT you should see also 079 in open core list
