### ISSUE TITLE
真的好久没更新了，期待1.0.0版本

### ISSUE THREAD

**Issue by kevon2019** [ic005k/OCAuxiliaryTools#224]
真的好久没更新了，期待1.0.0版本

**Comment by ic005k** [comment]
首先，感谢关注。
OCAT现在采用的是智能适应OC的版本，所以不再需要像之前那样频繁地更新了。
之前，OCAT的算法不科学，只要OC有点小变化，OCAT必须跟着更新，这是非常不科学的。
自从OCAT采用智能适应OC版本的算法之后，基本上只要OC没有特别大的变化，OCAT是不用更新的。
这就是新版OCAT带来的变化。
也就是说，无论OC升级到哪个版本，OCAT均能智能适应它，几乎做到了以不变胜万变，OCAT不用再频繁更新了。
关于OCAT的版本，它是以年份加上迭代的次数作为版本号，不采用类似的1.0.0等传统版本样式，这只是为了和OC的版本做个区别。
