### ISSUE TITLE
OC 081: changes in OC validate produce warning

### ISSUE THREAD

**Issue by 5T33Z0** [ic005k/OCAuxiliaryTools#225]
In OC 081 dev version, ocvalidate was changed. It now always puts a compatibility info on the screen. 

This message ("NOTE: This version of ocvalidate is only compatible with OpenCore version 0.8.1!") creates an issue warning in OCAT even though there are no issues in the config:

![Bildschirmfoto 2022-04-19 um 07 56 39](https://user-images.githubusercontent.com/76865553/163935935-28aa6dce-a2f0-4f93-b8b9-9cc2849570d4.png)

**Comment by ic005k** [comment]
I have noticed this phenomenon, and it may be a temporary problem.
I will be watching to see if master will make a merge and change this. Otherwise I will upgrade OCAT, please don't worry.

**Comment by ic005k** [comment]
It has been updated regarding the content you mentioned.

**Comment by 5T33Z0** [comment]
Thanks a lot!
