### ISSUE TITLE
OC validate

### ISSUE THREAD

**Issue by esafeddie** [ic005k/OCAuxiliaryTools#226]
Is this message necessary seeing that the version shown is 0.8.1? Prior to the latest OCAT update, the 'Tick Mark' symbol in the Menu would show in red accompanied with the message, now the 'Tick' now it's shown as normal but the message still pops up
![Screenshot 2022-04-19 at 4 45 29 pm](https://user-images.githubusercontent.com/7919587/164045344-18171af3-8ffd-4780-a36a-fbff9fc2a1ca.png)
.

**Comment by ic005k** [comment]
Sorry, I didn't quite understand what you meant.
Do you mean to add this message (in red) to the result prompt UI for OC validation?
However, the current logic is that if the OC version matches exactly, the validation will not prompt any problems, while the red exclamation mark on the toolbar will not appear.
Perhaps this validation message needs to be redesigned or improved, I will consider it, thanks for the suggestion.

**Comment by esafeddie** [comment]
What I mean is, although I am running the latest Nightly commit 0.8.1, when I check with the built in OC validate of OCAT, that message pops up which to my way of thinking it shouldn't as the Opencore 0.8.1 that I'm running is the correct one.

**Comment by esafeddie** [comment]
The reported Bug is within OC commit it self and not OCAT.
