### ISSUE TITLE
Uwamson.A!ml

### ISSUE THREAD

**Issue by foylaou** [ic005k/OCAuxiliaryTools#230]
Uwamson 是一種極具威脅性的惡意軟件，被歸類為特洛伊木馬程序。 根據攻擊者的具體目標，特洛伊木馬可以對受感染的系統執行多種侵入性和惡意操作。 Uwamson 可能負責啟動鍵盤記錄程序，捕獲鍵盤和鼠標輸入，控制系統的麥克風和攝像頭，進行任意屏幕截圖和其他間諜活動。

**Comment by foylaou** [comment]
OCAT-Win64\@OCAT.exe

**Comment by ic005k** [comment]
详情见这里：https://github.com/ic005k/OCAuxiliaryTools/issues/103

**Comment by ic005k** [comment]
还有这里：https://github.com/ic005k/OCAuxiliaryTools/issues/106

**Comment by ic005k** [comment]
如果你不需要这个功能的话，完全可以删掉这个文件，上面提供的链接，就是这个文件的来龙去脉。

**Comment by ic005k** [comment]
至于为什么bat转化成exe后会出现这个现象，你可以搜索下，网上有非常多的答案，这里不再赘述
