### ISSUE TITLE
[Suggestion] Update Readme with proper description

### ISSUE THREAD

**Issue by 5T33Z0** [ic005k/OCAuxiliaryTools#231]
# OpenCore Auxiliary Tools (OCAT)

![GUI](https://user-images.githubusercontent.com/76865553/165901706-abbccb4a-89bc-4b03-b6e5-f52dcb10b53c.png)

## About
OpenCore Auxiliary Tools is a GUI-based Configurator for editing `config.plist` files for Acidanthera's OpenCore Boot Manager.

Unlike other Configurator apps, OCAT doesn't mess up the config if the Devs of OpenCore add new features/keys to the config file structure. Instead, it adapts and integrates them in the interface automatically.

## Features

Besides beeing a plist Configurator it can do much more:

* Mount the EFI partion and automatically open the config.plist
* Update and migrate configs to the latest specs simply by clicking on the "Save" button. No more copying of keys and manually validtaing the config is required (huge timesaver).
* Automatically performs config validatation and points to possible conflicts/configuration issues.
* Sync Feature: check for and apply updates for OpenCore, Resources and Kext with a few clicks
* Select between Official/Dev Release and Debug builds of OpenCore
* Dropdown Menus with suggested for Quirks for Intel and AMD CPUs
* Preset Menus for ACPI, Kernel and other lists.
* Editable list with URLs of Kext Repos
* Integrated ASCII < > HEX Converter 
* Database with complete base configs for Intel and AMD CPUs based on Dortania's OpenCore Install Guide
* Ability to generate EFI folders from a config with a single click
* Ability to Create EFI folder Backups

## Guides
… Paste the existing Info here…

**Comment by ic005k** [comment]
Thank you so much, you're awesome!
I will add these to the Readme.

**Comment by 5T33Z0** [comment]
Glad you like it. I made a mistake, though:

"Dropdown Menus with suggested for Quirks for Intel and AMD CPUs"

Instead , it should say:

"Dropdown Menus with suggested Quirks for Intel and AMD CPUs"
