### ISSUE TITLE
20220208 for oc0.8.1开发版稍有问题请修复

### ISSUE THREAD

**Issue by jhsvip** [ic005k/OCAuxiliaryTools#237]
OCS: Missing key AllowNvramReset, context <Security>!
OCS: Missing key AllowToggleSip, context <Security>!
Serialisation returns 2 errors!

这两个选项已经在0.8.1被删除，请修复。

**Comment by ic005k** [comment]
你只需点击一下“保存”按钮，它就自动修复了，不需要人工升级软件来修复这些内容，因为目前的OCAT是智能适应OC版本的，请知悉。

**Comment by jhsvip** [comment]
> 你只需点击一下“保存”按钮，它就自动修复了，不需要人工升级软件来修复这些内容，因为目前的OCAT是智能适应OC版本的，请知悉。

感谢回复，您误解了我的意思，OC最新开发版0.8.1已经去除了那两个选项，如果使用ocat保存后，oc启动会报那两个key的错。我只是引用了一下ocat自动排错😝。

**Comment by ic005k** [comment]
> 如果使用ocat保存后，oc启动会报那两个key的错。

如果你不同步到OC0.8.1的话，无论如何它都会报这个错误。
我不知道你是否已将OC同步到了0.8.1？你采用OCAT将你目前的OC同步升级到0.8.1就没问题了。

**Comment by ic005k** [comment]
你可能仅仅是保存了配置文件（升级配置文件），但没有升级OC？
使用OCAT非常简单，1.选择OC版本，获取它。2.同步OC（升级OC）。3.保存配置文件（升级配置文件）

**Comment by jhsvip** [comment]
> 你可能仅仅是保存了配置文件（升级配置文件），但没有升级OC？
> 使用OCAT非常简单，1.选择OC版本，获取它。2.同步OC（升级OC）。3.保存配置文件（升级配置文件）
> 

您好，已经升级至最新0.8.1  2022-06-04  版本

**Comment by ic005k** [comment]
> 已经升级至最新0.8.1 2022-06-04 版本

这就有点奇怪了。无论如何，已纳入bug追踪系统，我会持续关注并留意这个问题的。
有任何线索，请随时留言。

**Comment by jhsvip** [comment]
> > 已经升级至最新0.8.1 2022-06-04 版本
> 
> 这就有点奇怪了。无论如何，已纳入bug追踪系统，我会持续关注并留意这个问题的。
> 有任何线索，请随时留言。

感谢

可能我表达的不是太清楚 
就是我用ocat保存以后  会自动添加这两个选项：
AllowNvramReset
AllowToggleSip
这时候
启动oc界面会报错  
我手动修改config.plist 删除这俩选项后 就正常了，一旦使用ocat编辑cofig，它会自动加入这两个多余的（已被OC作者移除的）quirks

**Comment by ic005k** [comment]
这个是你的配置文件和OC版本不匹配导致的，你用OCAT同步下就应该没问题了。

**Comment by ic005k** [comment]
比如，你的OC配置文件版本是080，但你的OC版本是081，这样就导致二者的版本不匹配。
OCAT提供了同步OC的功能，就是为了解决这个问题的，很简单的。

**Comment by jhsvip** [comment]
> 比如，你的OC配置文件版本是080，但你的OC版本是081，这样就导致二者的版本不匹配。
> OCAT提供了同步OC的功能，就是为了解决这个问题的，很简单的。

是的 确实是不匹配造成的，应该是我使用了太新的oc版本 请大佬及时跟进ocat的更新哦！😝

**Comment by ic005k** [comment]
OCAT不用更新的，你只需在OCAT里面获取你想使用的OC版本即可。

**Comment by ic005k** [comment]
OCAT的机制是智能的，它几乎可以获取并使用任何版本的OC，它不存在着和某个OC版本绑定的问题。
具体可以多在网上搜索相关教程或者阅读下OCAT的使用教程（目前暂时只有英文版）。
其实这一切都非常非常非常简单。

**Comment by jhsvip** [comment]
非常赞同大神，我有时间再研究一下。

**Comment by jhsvip** [comment]
> OCAT的机制是智能的，它几乎可以获取并使用任何版本的OC，它不存在着和某个OC版本绑定的问题。
> 具体可以多在网上搜索相关教程或者阅读下OCAT的使用教程（目前暂时只有英文版）。
> 其实这一切都非常非常非常简单。
在ocat中重新同步了一下 问题解决了
