### ISSUE TITLE
没办法升级MACos13，另外OC引导有0.8.2的开发版了么，听说8.1的正式版来了

### ISSUE THREAD

**Issue by kevon2019** [ic005k/OCAuxiliaryTools#238]
没办法升级MACos13，另外OC引导有0.8.2的开发版了么，听说8.1的正式版来了

**Comment by llity** [comment]
无法获取更新呢

**Comment by ic005k** [comment]
0.8.2估计得过几天才会在0.8.1的基础上有真正的变化
你可以关注这里，也就是OCAT的OpenCore工厂菜单
https://github.com/acidanthera/OpenCorePkg/actions
