### ISSUE TITLE
启动项里没有了Reset NVRAM

### ISSUE THREAD

**Issue by benladengtd** [ic005k/OCAuxiliaryTools#239]
升级了正式0.8.1版本后启动项里不显示Reset NVRAM图标了，之前其它版本升级都没这个问题不知道什么原因导致。升级前有这样的提示OCS: No schema for AllowNvramReset at 0 index, context <Security>! OCS: No schema for AllowToggleSip at 2 index, context <Security>!

**Comment by benladengtd** [comment]
After upgrading the official version 0.8.1, the Reset NVRAM icon is no longer displayed in the startup item. Other versions have not been upgraded before. I don't know why. There is such a prompt before the upgrade  OCS: No schema for AllowNvramReset at 0 index, context ! OCS: No schema for AllowToggleSip at 2 index, context !

**Comment by ic005k** [comment]
嗯，搞不好这个估计是OC官方去掉了吧，我最近很忙，没来得及关注这些
不过，你可以通过OCAT帮助菜单里面的“OpenCore版本差异说明”，你搜索下“Reset NVRAM”，看看是不是官方有改动

**Comment by ic005k** [comment]
“Reset NVRAM”在0.8.1已弃用，我刚看了下版本差异说明

**Comment by LoveGlaze** [comment]
需要自己添加Drivers里面的ResetNvramEntry.efi，就有了

**Comment by benladengtd** [comment]
感谢各位回复在OC\drivers文件夹里添加ResetNvramEnty.efi和ToggleSipEntry.efi两个驱动并启用就解决了
