### ISSUE TITLE
Mount ESP Windown Bug in macOS Ventura

### ISSUE THREAD

**Issue by 5T33Z0** [ic005k/OCAuxiliaryTools#241]
In macOS 13, the "Mount ESP partition" window won't close after mounting the partition. The [X} icon to close it also doesn't work.

**Comment by ic005k** [comment]
Okay, received.
However, this will have to wait until I upgrade to 13. I think I will upgrade to 13 as soon as possible, thanks for the feedback.

**Comment by 5T33Z0** [comment]
No problem. It's a minor issue anyway. Users can just move the window out of the way.

**Comment by ic005k** [comment]
It has been updated, please upgrade to the latest version.

**Comment by 5T33Z0** [comment]
Thanks. It works!
