### ISSUE TITLE
V20220210 release (AMD Problem)

### ISSUE THREAD

**Issue by fabiosun** [ic005k/OCAuxiliaryTools#245]
@ic005k Hi
I did an error in a pull request
I have corrected with another one but release of OCAT has my error in it!
I am Sorry for my error but  it is a problem for AMD user 
if you can release corrected one also for us

My error was to put outside preset folder and preset updated for macOS Ventura

Forgive me again!

**Comment by ic005k** [comment]
Oh, it's okay.
You can tell your friends or users, and if they are in a hurry, they can all download the latest OCAT here:.
https://github.com/ic005k/OCAuxiliaryTools/actions

I will also post the latest official version of OCAT in a timely manner.
