### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Blurayx** [ic005k/OCAuxiliaryTools#246]
Hi,
Will you be updating to 0.8.1?

Thanks

**Comment by ic005k** [comment]
You can choose any OC version, including the latest version, in the following way, which is very simple

https://github.com/ic005k/OCAuxiliaryTools/issues/223

**Comment by ic005k** [comment]
To make it simple, it means that OCAT is not tied to any OC version, and you can simply select your preferred OC version through OCAT.

**Comment by Blurayx** [comment]
Thanks for your reply.
 I can only see 0.7.8 in the dropdown menu.

**Comment by ic005k** [comment]
https://github.com/ic005k/OCAuxiliaryTools/issues/223#issuecomment-1099234975

**Comment by ic005k** [comment]
Latest Version = 0.8.1 ... 0.8.2 ... 0.8.3 ... 0.9.0 or 2.0.0 ......

**Comment by lucky13820** [comment]
I used the latest version option, it still only updates to 0.7.8, not 0.8.1. Not sure what I'm doing wrong.
