### ISSUE TITLE
Scanning Kext folder 

### ISSUE THREAD

**Issue by retrohog** [ic005k/OCAuxiliaryTools#248]
A very strange bug whenever I try to scan my kext on windows it started to create so many folders inside the kext folder and after sometimes the windows gets soft reboot. It just keep creating folders and folders.

**Comment by ic005k** [comment]
Can you provide me with the exact steps to follow? Thank you.

**Comment by ic005k** [comment]
OCAT doesn't have the ability to scan kexts, I really didn't understand what you meant, sorry.

**Comment by retrohog** [comment]
When I select the choose folder in OCAT Kexts menu located in right side bottom ( = ) Symbol button, then it just starts creating multiple folders inside it and stops when windows freeze or crash

**Comment by ic005k** [comment]
For Kext, under Windows, it is a folder, you just need to select this folder with the same name as Kext to add this Kext to the table.
If possible, could you record a video file of your operation, I would like to see how it is really a phenomenon?

**Comment by ic005k** [comment]
By the way, under Windows, if you add Kext by "+", only one Kext can be added at a time, it does not support multiple selection.
If you want to add more than one Kext, you can multi-select these Kext and drag them directly to the inside of the table.

**Comment by ic005k** [comment]
And, may I ask what version of Windwos you are using, Win7 or Win10 or Win11?
