### ISSUE TITLE
挂载并打开配置文件好像不能用了

### ISSUE THREAD

**Issue by w19996** [ic005k/OCAuxiliaryTools#249]
点击并输入密码之后并不能打开配置文件

**Comment by w19996** [comment]
并且出现了这个提示

![截屏2022-06-13 00 06 51](https://user-images.githubusercontent.com/54472022/173242438-4653b460-3ae0-41a8-b546-459b8660cd63.png)

**Comment by ic005k** [comment]
你可能需要将“允许从以下位置下载App”改为“任何来源”？以允许第三方的app正常运行。

**Comment by w19996** [comment]
> 

”挂载并打开配置文件“仍然是不起作用，点击后只能挂载ESP分区，并不能直接打开配置文件

**Comment by ic005k** [comment]
已纳入bug追踪系统。
目前来说，为什么在你那边会不正常，原因暂时不可知，我会持续关注并分析这个问题的
如有任何线索，请随时提供

**Comment by w19996** [comment]
> 已纳入bug追踪系统。
> 目前来说，为什么在你那边会不正常，原因暂时不可知，我会持续关注并分析这个问题的
> 如有任何线索，请随时提供

解决了，EFI分区没有卷标就不能打开，把EFI分区分卷标设置成EFI就可以挂载并打开了，不知道这算不算个bug

**Comment by ic005k** [comment]
> 解决了，EFI分区没有卷标就不能打开，把EFI分区分卷标设置成EFI就可以挂载并打开了，不知道这算不算个bug

也可以算bug，但我目前没测试过，如果去打开一个没有卷标的分区里面的文件，会不会有问题，后面有空我会试下

**Comment by w19996** [comment]
> > 解决了，EFI分区没有卷标就不能打开，把EFI分区分卷标设置成EFI就可以挂载并打开了，不知道这算不算个bug
> 
> 也可以算bug，但我目前没测试过，如果去打开一个没有卷标的分区里面的文件，会不会有问题，后面有空我会试下

还有再提个建议，如果EFI分区已经挂载，在点击挂载并打开配置文件按钮时，能不能不输入密码，而是直接打开配置文件

**Comment by ic005k** [comment]
> 还有再提个建议，如果EFI分区已经挂载，在点击挂载并打开配置文件按钮时，能不能不输入密码，而是直接打开配置文件

可能不会考虑这个功能，因为你已经挂载了ESP，那么就可以随时通过“访达”访问它，完全没必要再回到OCAT访问它，这是没有效率的
还有就是挂载ESP是个使用频率很低的功能，因为用户都是将OC放在一个随时可见的FAT32分区里面，可随时对OC进行维护而不用挂载ESP之类的繁琐过程，包括在Win等平台都可随时访问

**Comment by ic005k** [comment]
估计是没有人愿意去使用ESP分区来存放OC，太麻烦，每次维护OC都得挂载它

**Comment by w19996** [comment]
> 估计是没有人愿意去使用ESP分区来存放OC，太麻烦，每次维护OC都得挂载它

好的，辛苦

**Comment by WaterSunMount** [comment]
> > 解决了，EFI分区没有卷标就不能打开，把EFI分区分卷标设置成EFI就可以挂载并打开了，不知道这算不算个bug
> 
> 也可以算bug，但我目前没测试过，如果去打开一个没有卷标的分区里面的文件，会不会有问题，后面有空我会试下

我目前也遇到这个问题了,我也设置了efi卷标信息,期待您的回复
<img width="710" alt="image" src="https://github.com/ic005k/OCAuxiliaryTools/assets/75781948/7a84d4d7-00ae-434f-adaa-57221b228f9f">
