### ISSUE TITLE
Update DEV kexts not working + confusing UI

### ISSUE THREAD

**Issue by MrBananaPants** [ic005k/OCAuxiliaryTools#251]
When I enable "OpenCore DEV" and open the kexts update menu, it doesn't check for new DEV versions of the kexts:
![image](https://user-images.githubusercontent.com/41532982/173898370-34c12311-bc2f-4a52-9fbd-cfb9d0165ea6.png)
You can see that the available version is lower than the current version even though DEV is enabled. Clicking "check for kexts updates" and "update kexts" doesn't install the latest available DEV build.

Another issue is that I find the kext and OpenCore update menu very confusing and not user-friendly.
Why do I have to do like 5 steps, download upgrade packages, get like 7 error messages,... just to install the newest DEV version of the kexts and OpenCore files?

Can you please simplify the process so there are just 2 buttons for kexts and 2 buttons for OpenCore (so 4 in total): 1 button to check if there is a newer version available (which updates the color of the files) and another button to install the newer files.

The kexts buttons are how it should be: just a button to check for updates and another button to install the new updates.
But why make the OpenCore update section so complicated? I have completely read the [documentation](https://github.com/5T33Z0/OC-Little-Translated/blob/main/D_Updating_OpenCore/README.md) but it's still really confusing. What does the "Get OpenCore" and "Start sync" button do? Why does the "Start sync" button completely close the update menu?

Just make the OpenCore update process the same as the kext update process (which is currently not working in DEV mode).

**Comment by ic005k** [comment]
> When I enable "OpenCore DEV" and open the kexts update menu, it doesn't check for new DEV versions of the kexts:

OCAT itself does not have this feature.
The reason for this is very simple: there is no update source for the development version of kexts, and only the stable version is officially released by the respective kexts.

**Comment by ic005k** [comment]
For OCAT, I am very happy to keep improving it and I will take into account the suggestions you mentioned.
If you have any questions or ideas, please feel free to let me know.
Thank you very much.

**Comment by ic005k** [comment]
Also, because the operation of OCAT is so simple that you will know it as soon as you try it, I will not go over the operation steps.

**Comment by ic005k** [comment]
Regarding the "confusing UI", could you please provide a design drawing of the user UI? I would be very happy to improve it. Thanks again.

**Comment by MrBananaPants** [comment]
> The reason for this is very simple: there is no update source for the development version of kexts, and only the stable version is officially released by the respective kexts.

Why not just download the latest build from [here](https://dortania.github.io/builds/)? It has the latest DEV builds of all the kexts (both release and debug builds).

About the "confusion UI", I just mean the two buttons to download and "install" the latest OpenCore version. Why not make it the same process as the kexts? So just a button to check if there's a new OpenCore version available and a second button that "installs" that version and updates the config.plist?

**Comment by ic005k** [comment]
> Why not just download the latest build from [here](https://dortania.github.io/builds/)?

Sorry, from a technical point of view, I haven't found a way or method to get them automatically yet, if you have a good implementation idea, please let me know, thanks.
Also, the main positioning of OCAT is based on the stable version of OC and Kexts, not the development version. So OCAT will not do too many features on the development version of Kexts or OC.
If you are a loyal user of the dev version, please come and do the Kexts update manually, OCAT may not consider the automatic update of the Kexts dev version.

**Comment by ic005k** [comment]
> About the "confusion UI", I just mean the two buttons to download and "install" the latest OpenCore version. Why not make it the same process as the kexts? So just a button to check if there's a new OpenCore version available and a second button that "installs" that version and updates the config.plist?

There are many times when we may need to help a user with something and simply want to upgrade the OC (the latest version of the previous OC is already available), so it is a very good idea to separate these two steps (getting the OC and synchronizing the OC).

**Comment by MrBananaPants** [comment]
> if you have a good implementation idea, please let me know, thanks.

I actually have found a really easy way to get the latest kext DEV build including the hash.
The following URL gives you a JSON file that contains everything you need: [https://raw.githubusercontent.com/dortania/build-repo/builds/config.json](https://raw.githubusercontent.com/dortania/build-repo/builds/config.json)

It includes info like the date the kext was built and committed, direct download links for both the release and debug version, the hash, commit message, version number,...

If you just compare the current kext hash with the hash of the latest build from that JSON file, you know there's a newer version available of that kext.

**Comment by ic005k** [comment]
> I actually have found a really easy way to get the latest kext DEV build including the hash.
> The following URL gives you a JSON file that contains everything you need: https://raw.githubusercontent.com/dortania/build-repo/builds/config.json

Oh, that's a good idea.
But one question is, what to do with these Kexts if OCAT switches to the stable version, is to download the stable Kexts again and I don't know what the user should do at this point?

**Comment by ic005k** [comment]
There is also the question of whether this website: https://dortania.github.io/builds/ will be as permanent as Kexts' official website. If OCAT does all this well, but this site stops serving, all the time is wasted.
So, there is some uncertainty here.

**Comment by ic005k** [comment]
You are a very thoughtful person and I will think about these issues while making the implementation accordingly.

**Comment by MrBananaPants** [comment]
> There is also the question of whether this website: https://dortania.github.io/builds/ will be as permanent as Kexts' official website.

I don't think you should worry about that. The website is completely automated and there's no user action required. And if it ever stops working, you just lose the ability to download the latest dev kexts automatically. You said not a lot of users are using the DEV kexts so only a very small amount of users will be affected.

**Comment by MrBananaPants** [comment]
If you need any help with the implementation, let me know! I don't have any experience with C++ (only Python and JavaScript since it's my first year of programming) but I can help with the thought process of implementing the feature.

**Comment by ic005k** [comment]
Features have been added, please upgrade to the latest version. Please feel free to let me know if you have any questions or ideas.

**Comment by MrBananaPants** [comment]
I just tested it out and it works great!
![image](https://user-images.githubusercontent.com/41532982/174288953-2f215e5b-2a33-425a-8ca4-5b68e63a4a17.png)

Thank you for implementing this feature!
