### ISSUE TITLE
Kext Update issue when using nghtly builds

### ISSUE THREAD

**Issue by 5T33Z0** [ic005k/OCAuxiliaryTools#252]
The Kext Updater actually shows newer kexts as outdated:

![Bildschirmfoto 2022-06-17 um 18 46 27](https://user-images.githubusercontent.com/76865553/174341886-862163a8-ddd7-486f-9f1a-9a6c99f2e375.png)

And when you "update" them, they are actually downgraded:

![Bildschirmfoto 2022-06-17 um 18 48 54](https://user-images.githubusercontent.com/76865553/174342082-6e53efa9-8ecf-49cf-a9fb-f24e328198ef.png)

That's not good. Especially if you are working with macOS Ventura. Please include a rule that newer kexts won't be downgraded.

Thanks.

**Comment by MrBananaPants** [comment]
It's because you don't have the "DEV" checkbox enabled next to the "settings" button and above the "update kexts" button.
I was also confused at first because I didn't see the checkbox.

**Comment by 5T33Z0** [comment]
Can you see the title of the Window? It clearly says "DEV"!

**Comment by MrBananaPants** [comment]
Yes I know but that's not the checkbox I'm talking about. I'm talking about this checkbox:
![annotely_image](https://user-images.githubusercontent.com/41532982/174353161-aa2b534f-4fa4-4bdd-9276-434dfa8eae2e.png)

**Comment by MrBananaPants** [comment]
But it is also useful that the dev version of OpenCore is not linked to the dev version of the kexts. Let's say you have updated a kext to the latest stable version but it's giving you some issues. You can then download the latest dev version of that kext (that might fix the issue) without having to use the latest dev version of OpenCore.

**Comment by 5T33Z0** [comment]
Ahh, ok. Sorry, my bad. You're right!

Probably a compromise to be able to use nightly builds of OpenCore with official kext releases. Still not a fan, though ;)
