### ISSUE TITLE
开发版更新Kexts报错

### ISSUE THREAD

**Issue by tc414103685** [ic005k/OCAuxiliaryTools#253]
Kexts选择开发版后提示失败，实际上已经下载了，ocat已升级到最新版
![image](https://user-images.githubusercontent.com/25275402/174425883-945bcae7-400c-4edd-92ee-e4f924720850.png)
![image](https://user-images.githubusercontent.com/25275402/174425936-6f7c31ec-acea-4652-b349-2ba24151cc3d.png)

**Comment by ic005k** [comment]
这个原因可能是你那边的网络环境没法全部访问github的缘故，比如访问下面这个文件：https://raw.githubusercontent.com/dortania/build-repo/builds/config.json

最简单的解决办法之一，安装个“开发者边车”，网址：https://github.com/docmirror/dev-sidecar

也就是说，你虽然能正常访问github的网页，但不代表能全部访问，这可能就是出现这个现象的原因。
无论如何，期待你的后续反馈。

**Comment by ic005k** [comment]
它的工作原理是先从这里 https://raw.githubusercontent.com/dortania/build-repo/builds/config.json 读取kexts开发版各个kexts的索引，以获取下载信息，如果这个索引读取不到的话，那么后面就无从谈起。

**Comment by tc414103685** [comment]
> 它的工作原理是先从这里 https://raw.githubusercontent.com/dortania/build-repo/builds/config.json 读取kexts开发版各个kexts的索引，以获取下载信息，如果这个索引读取不到的话，那么后面就无从谈起。
解决了，谢谢

**Comment by zhaozhon** [comment]
你是中国人吗，中文很好，还是你用的翻译？

**Comment by zhaozhon** [comment]
> 它的工作原理是先从这里 https://raw.githubusercontent.com/dortania/build-repo/builds/config.json 读取kexts开发版各个kexts的索引，以获取下载信息，如果这个索引读取不到的话，那么后面就无从谈起。

你是中国人吗，中文很好，还是你用的翻译？

**Comment by tc414103685** [comment]
> > 它的工作原理是先从[https://raw.githubusercontent.com/dortania/build-re/builds/config](https://raw.githubusercontent.com/dortania/build-repo/builds/config.json)到的话，那么后面就没有从谈起。
> 
> 你是中国人吗，中文很好，还是你用的翻译？

是的，中国人
