### ISSUE TITLE
Timestamp of .kexts not changed after updating 

### ISSUE THREAD

**Issue by 5T33Z0** [ic005k/OCAuxiliaryTools#257]
I've noticed that the date of of .kext isn't changed after updating. It only shows the date from when the kext file was created in the folder:

![Bildschirmfoto 2022-06-25 um 00 19 15](https://user-images.githubusercontent.com/76865553/175703148-42013864-ba5e-4427-bfa6-0229ca8f7bd0.png)

But inside the package, the actual file is up to date:

![Bildschirmfoto 2022-06-25 um 00 22 06](https://user-images.githubusercontent.com/76865553/175705447-09507592-55dd-4531-bf99-a09602b32ba2.png)

This really confused me. I though the kext wasn't updated. Is there a way to update  the timestamp of the .kext as well?

**Comment by ic005k** [comment]
This seems to be a problem with the macOS system display, which doesn't seem to actually or correctly display the timestamp of the binary file inside. You can view the binary file inside and it's timestamp is the real file modification time.
I don't know what this is about, but at least it's happening on my end too at the moment, with 13.0 Beta (22A5286j).

**Comment by ic005k** [comment]
If you are also using macOS13, I suspect this is a bug in the system display?

**Comment by ic005k** [comment]
But this is only a display problem, the file itself works fine and does not affect other aspects.

**Comment by 5T33Z0** [comment]
These screenshots are from Catalina. I guess the .kext metadata isn't updated as well. This is also the case with Big Sur and Monterey. I think this is a general macOS issue.

I'd suggest that the update script deletes the .kext completely before adding the updated file. Then the timestamp would always be correct.

**Comment by ic005k** [comment]
I've tested this, and deleting it completely doesn't display the timestamp of the binary file inside properly, at least on my end macOS13 does.
macOS should have a command to refresh the system cache or something, I forget exactly, after running this command seems to be normal, it seems to be related to the system cache, you can research to see.
However, this doesn't affect the file anyway because OCAT doesn't use the timestamp to determine if the file is different, but the md5 value to determine if the file is different.

**Comment by ic005k** [comment]
> I guess the .kext metadata isn't updated as well.

The metadata (the binary inside the package) has been updated, you can check it out, it's fine.

**Comment by 5T33Z0** [comment]
This is not about the binary, I know that is fine

Users don't need to see the timestamp of the binary _inside_, they need to know the one of the .kext on the _outside_. And since OCAT uses md5 checksum it doesn't really matter if the timestamp inside is correct you might as well just let it delete the file so the date is updated.

**Comment by ic005k** [comment]
This has nothing to do with deleting files or OCAT, you copy a kext file manually and it shows the same result.
And OCAT itself uses a full overwrite mechanism, which means that you delete it and then copy it, without keeping any of the old content.
At its root, this seems to be a feature of macOS, a phenomenon that exists in many kext, only few people pay attention to it.
