### ISSUE TITLE
AirportItlwm Alpha version showing in kext update

### ISSUE THREAD

**Issue by dipakvz** [ic005k/OCAuxiliaryTools#260]
in kext update, AirportItlwm Alpha version showing instead of stable version

**Comment by ic005k** [comment]
This is a known problem. For "AirportItlwm", it is recommended that you update it manually. At present, there will be some problems with automatic updating. It seems that AirportItlwm has different versions for different macOS systems, so OCAT didn't judge whether these "AirportItlwm" versions are consistent with the version of AirportItlwm you are using.So, it's best to update AirportItlwm manually, thank you.
