### ISSUE TITLE
提示内容错位

### ISSUE THREAD

**Issue by cike-567** [ic005k/OCAuxiliaryTools#264]
具体情况如图

<img width="653" alt="image" src="https://user-images.githubusercontent.com/68531942/178173245-c40aac61-3855-4488-9083-d021ab2215ae.png">

出现提示之后，鼠标移动窗口，提示发生错位。提示的部分需要改改，出现时间可以加快一点，一般来说鼠标脱离选项之后，提示会立马消失。提示停留一段时间，会遮挡其他内容，其他软件的窗口也会被遮挡。

**Comment by ic005k** [comment]
> 出现提示之后，鼠标移动窗口，提示发生错位

是的，出现提示，当你移动窗口时，目前并没有采用提示跟随的机制。

**Comment by ic005k** [comment]
> 出现时间可以加快一点

之前有用户建议，当在一个条目上停顿3s左右，自动出现提示。

**Comment by ic005k** [comment]
> 一般来说鼠标脱离选项之后，提示会立马消失。提示停留一段时间，会遮挡其他内容，其他软件的窗口也会被遮挡。

OCAT会自动计算提示内容的大小并结合人们阅读的平均速度，采用自动消失的机制。
如果你想让其快速消失，只需用鼠标单击提示框即可，mac下也可以单击提示框之外的任何窗口空白位置。

**Comment by ic005k** [comment]
总之，这块的内容，后面有时间会进行优化的。欢迎更多的问题或建议。

**Comment by ic005k** [comment]
还有，目前来说提示内容可能过于陈旧，因为没有太多时间来随时更新它。
OCAT采用开放式的提示结构，如果大家有时间，可以对提示的内容随时进行更新，这个文件位于：
https://github.com/ic005k/OCAuxiliaryTools/blob/master/Database/preset/toolTip.txt
可参考里面现有的内容，其语法结构和格式也非常简单。

**Comment by cike-567** [comment]
我认为，提示这个东西，召之即来，挥之既去就好。有需要的人，会仔细查看，鼠标放到文字上一会就出现提示，远离文字则立即消失。提示的内容确实有些问题，有时间我修改一下。

**Comment by ic005k** [comment]
其实最开始，我是没有设计悬浮提示的，我认为完全没这个必要，如果你需要提示，鼠标右键选“提示”即可，看完随时可关闭提示。
后来有用户建议，才重新设计了悬浮提示，这块我可能不会再来回更改了，后面我可能会加个选项，是否允许出现悬浮提示，或者也可能会去掉悬浮提示功能，我始终认为悬浮提示是多此一举。

**Comment by cike-567** [comment]
这种文字特别多的，悬浮提示确实是多此一举。我觉得，有一个专门看提示的部分就好了，通过右键菜单查看提示，次数多了，有些繁琐。

**Comment by ic005k** [comment]
> 有一个专门看提示的部分就好了

最好最简单的就是OCAT的帮助菜单选择“OpenCore文档“，所有的提示全部来自它，都是从它里面摘出来的，这种手动摘录，可见工作量之大，所以后面我就不热衷搞这些提示了，因为一直没有找到合适的自动化方法，手动摘录太不科学了，太枯燥、太无聊，纯体力劳动。
所以如果你有新的创意或自动化的方法，请随时留言。

**Comment by ic005k** [comment]
其实，对于提示这个功能，可能是我的一厢情愿，据我所知国外大部分用户都是直接看OpenCore文档
再加上当时设计OCAT的时候，有些想当然，堆砌了一些无用的功能，比如功能提示、导入导出等等，既然做了，后面就一直没删除它们，聊胜于无吧

**Comment by cike-567** [comment]
没有相当的基础看不明白 OpenCore 文档，英文的更搞不懂，对一般人来说简直和天书一样。有个能看懂的文章或者之类的东西就不错了。我本来打算写一篇的，但是自从我显卡换了之后，无法驱动，就一直没有动笔。自动化可以看看 power automate 或者 python 的某些库。

**Comment by ic005k** [comment]
OC说明文档的中文化刚开始时还是有很多人在翻译和整理，后来大多数都没有继续跟进，你不妨在网上搜索下看看，应该还有些不算太新的中文资料，如果你有时间和兴趣，不妨继续完善这些内容，我相信对于部分用户来说，这些中文资料还是很有必要的。

**Comment by cike-567** [comment]
已经在干了，https://github.com/SukkaW/OpenCore-Document-zh_Hans

版本落后有点多

**Comment by ic005k** [comment]
到时将成型之后的链接给我，我会将它放到OCAT的帮助菜单里面。

**Comment by cike-567** [comment]
文档内容更新已经做完了。就等合并分支了。文档采用 markdown 编写，提示的内容可以从里面提取，如果这个功能还要做的话。

https://github.com/SukkaW/OpenCore-Document-zh_Hans

**Comment by ic005k** [comment]
厉害，如果中文文档足够完善，则着实不再需要那些只言片语的提示信息了。有进展或更新，随时通知。

**Comment by ic005k** [comment]
除了oc的官方文档，还有一个oc资源，大多数人都有参考这个资源：https://github.com/dortania/OpenCore-Install-Guide

**Comment by cike-567** [comment]
分支已经同步。dortania 这个我当作做为官方文档的补充在看，除了是英文的，其他都还好。适合小白安装系统做参考。
设备那一块可以右键增加预设好的属性（设备id、型号之类的），方便添加。nvram也是一样。

**Comment by cike-567** [comment]
目前文档更新到 0.8.2，当作参考完全可以了。部分选项，官方也没说清楚，配合其他资料一起看最好。gui 能不能换一换，看着好老，和我这 win 11 的风格差别好大。

**Comment by ic005k** [comment]
好，回头有时间，我会整合这些资源的，请在相关的文档中署上你的名字，为节省时间和精力，OCAT将不再为这些外部资源署名，请知悉。
对于UI，主要是缺乏美工，如果你有美工基础或兴趣，欢迎为OCAT设计一套皮肤。

**Comment by cike-567** [comment]
设计 UI 不在我的知识范围内，我感兴趣，该如何做。

**Comment by ic005k** [comment]
> 我感兴趣，该如何做。

这个我也说不好，UI设计是一个细分领域，和编码关系不太大，可以说UI及用户交互完全是独立于编码的另外一个领域了，很专业的，你可以看看公司里那些专业的UI设计师，这里面涉及到很多知识，比如美术、人机交互等等。
这样说吧，比如Apple就是先进行UI和交互设计，之后才是基于这些顶层设计的编码，就像建筑一样，先设计外观，之后才是力学结构，力学结构是为外观服务的，软件领域其实也一样。
如果你没有美术基础，我觉着还是不用花时间在这上面了，这些对我们来说，可能比较复杂，就像win和mac相比，总觉得差点什么，并不是win的技术不如mac，而是设计，mac的设计确实是用了心的。

**Comment by cike-567** [comment]
我花点时间搓了一个未完成品。

<img width="634" alt="image" src="https://user-images.githubusercontent.com/68531942/180700854-33787b2f-1c73-4c6b-8de8-f8aa2be498d9.png">

**Comment by ic005k** [comment]
简体中文参考手册在最新的OCAT中已加入帮助菜单中。
至于其它方面的内容，比如UI等内容的更新，我会定期收集相关信息，你可随时在此添加你的任何建议或创意。
