### ISSUE TITLE
windows下把桌面路径改成D盘，数据库中双击生成的EFI文件夹和备份文件夹还是会在C盘Users内生成

### ISSUE THREAD

**Issue by w19996** [ic005k/OCAuxiliaryTools#269]
OCAT并没有检测到桌面路径已经更改了，其他软件都可以检测到桌面路径变成D盘了，这个可以改进一下吗
PS:根据注册表  HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\Shell Folders\\Desktop的键值可以知道桌面路径，提供一下这个信息不知道有没有用

**Comment by ic005k** [comment]
OCAT只使用home作为默认路径存储你上面提到的内容，为了在所有的系统上实现完全一致的文件管理，这是固定不变的，无论是Linux还是Mac，都是采用home目录这个固定的路径。
建议你将整个home目录改到D盘，不知道结果如何?
这些都是小问题，有空我会找个Windows试下看看，有任何发现或问题，可随时留言。
