### ISSUE TITLE
Themes

### ISSUE THREAD

**Issue by Drk152** [ic005k/OCAuxiliaryTools#274]
please add support themes edit

**Comment by ic005k** [comment]
Ok, but for this, I don't know what kind of features you guys need? Can you tell me your idea or design? Thanks.

**Comment by ic005k** [comment]
Ok, but for this, I don't know what kind of features you guys need? Can you tell me your idea or design? Thanks.

**Comment by Drk152** [comment]
You can add the function of OpenCore Configurator themes at present.
OCATools is the most convenient for windows use every.
fix mouse preview prompts bug.
![20220729124250](https://user-images.githubusercontent.com/110192509/181684364-d53372aa-db0d-4c84-be43-01e09f108e3c.png)

**Comment by ic005k** [comment]
Okay, I'll think about it.
For the "Hover Tip", please turn it on in Preferences in the main menu.
