### ISSUE TITLE
UEFI/Drivers: "LoadEarly" Settings are not applied

### ISSUE THREAD

**Issue by 5T33Z0** [ic005k/OCAuxiliaryTools#275]
I've noticed that when changing the settings for UEFI/Drivers/LoadEarly from true to false, the settings are not applied to the file. It looks like they are applie in the GUI, but they are not.

**GUI after applying settings:**
![Before](https://user-images.githubusercontent.com/76865553/181686154-45cbdf5f-43de-48ce-8049-bb91347915c0.png)

**Opening the config in a plist editor after saving in OCAT:**
![Bildschirmfoto 2022-07-29 um 06 57 42](https://user-images.githubusercontent.com/76865553/181685751-6e74b579-d020-4856-a0d0-46263e822aea.png)

**After closing and pening the config again in OCAT**:
![Bildschirmfoto 2022-07-29 um 06 49 56](https://user-images.githubusercontent.com/76865553/181686102-33d3c407-10bc-478a-9485-4ef619aeef82.png)

**Comment by ic005k** [comment]
Oh, it seems OC has been upgraded again, for "LoadEarly", the selection with mouse may not work, but the manual input always works, please input "true" or "false" manually ".
For mouse click to switch between "true" and "false", I will upgrade OCAT to fix it, thanks for the feedback.

**Comment by 5T33Z0** [comment]
Thanks for the tip. I see there's a new release available "20220229", but the Assets only contains the Source Code

**Comment by ic005k** [comment]
> but the Assets only contains the Source Code

GitHub is still in the process of auto-compiling, and it is estimated that the app will be automatically released in 5 minutes, so please wait.

**Comment by 5T33Z0** [comment]
Ah, ok. Cool
