### ISSUE TITLE
Issue with failsafe definition Drivers->LoadEarly 

### ISSUE THREAD

**Issue by vandroiy2013** [ic005k/OCAuxiliaryTools#276]
Hi. During update 0.8.2 -> 0.8.3 LoadEarly is set to True for all existing drivers in config.plist while it should be False in most cases. Also OpenCore documentation defines False as failsafe for this entry. 

Thanks
<img width="1337" alt="Знімок екрана 2022-08-01 о 17 08 32" src="https://user-images.githubusercontent.com/8144780/182167634-16c487d3-d43d-4170-bb1c-a0797ea3345c.png">

**Comment by vit9696** [comment]
Just to make it clear, it is most likely an error to set it true for almost all these drivers, so it is quite worrying.

**Comment by ic005k** [comment]
First, thanks for the feedback.
These settings are not artificial, they are the default behavior of OCAT to initialize boolean values, which means that OCAT initializes all boolean values with "true" by default.
However, it doesn't matter, I can artificially initialize these values to "false" in a later version.

**Comment by ic005k** [comment]
Of course, in the end, it is up to you to decide which values need to be set to "true" and which values need to be set to "false".

**Comment by ic005k** [comment]
OCAT has been updated. Feel free to ask any more questions or suggestions you may have, thank you.

**Comment by vandroiy2013** [comment]
@ic005k Thanks.
