### ISSUE TITLE
这里是不是显示不全

### ISSUE THREAD

**Issue by w19996** [ic005k/OCAuxiliaryTools#277]
![截屏2022-08-02 12 07 50](https://user-images.githubusercontent.com/54472022/182289998-d943fb77-3b53-44c6-9414-7c019e28ea10.png)

**Comment by ic005k** [comment]
这应该是一个历史遗留问题，当时记得是用来显示NVRAM里面的变量“SystemAudioVolume”的值，后面OC几经升级，这个功能应该是没什么意义了，我回头考察下，可能会去掉它。
该问题已记录，感谢反馈，欢迎发现更多的问题。

**Comment by ic005k** [comment]
此问题在新版本20220231中已被修复，请更新到最新版本。

**Comment by w19996** [comment]
> 此问题在新版本20220231中已被修复，请更新到最新版本。

收到
