### ISSUE TITLE
Question about opencore mod version

### ISSUE THREAD

**Issue by xuandung38** [ic005k/OCAuxiliaryTools#282]
Do you planning for OCAT to support the opencore mod version ?

**Comment by ic005k** [comment]
This has long been able to be supported,please see here: https://github.com/ic005k/OCAuxiliaryTools/issues/203

**Comment by ic005k** [comment]
If you have an update source for a derivative version of OC, you can even update it online by simply replacing "https://github.com/dortania/build-repo" with your update source.

**Comment by xuandung38** [comment]
Thank you so much
