### ISSUE TITLE
无法更新开发版Kexts

### ISSUE THREAD

**Issue by laobamac** [ic005k/OCAuxiliaryTools#286]
There seems to be no such problem in other versions of Windows, but only the stable version Kexts can be used in Windows11Beta. When viewing the development version, the situation shown in the following figure appears, which seems to indicate that "the file cannot be created". Running in administrator mode still can't be solved. A similar situation occurred in Ventura. Ask for help! Thank you very much (_P.S.: I like this software very much, and it would be even more perfect if it could add the Mod version of OpenCore_)

![image](https://user-images.githubusercontent.com/107761278/188044466-7981be83-9f34-4213-a72f-26992e0740d2.png)

`File Creation failed C:\Users\USER_NAME\temp`

Looking forward to your reply.

**Comment by ic005k** [comment]
Please see here:
https://github.com/ic005k/OCAuxiliaryTools/issues/253

**Comment by ic005k** [comment]
> if it could add the Mod version of OpenCore

Please see here:
https://github.com/ic005k/OCAuxiliaryTools/issues/203

**Comment by laobamac** [comment]
> 请参阅此处：
> #253
Thank you very much. After some attempts, I successfully obtained the development version of kexts

**Comment by laobamac** [comment]
> > 如果可以添加OpenCore的Mod版本
> 
> 请参阅此处： #203

Thanks for telling me!
