### ISSUE TITLE
Can't get OpenCore last version (0.8.4)

### ISSUE THREAD

**Issue by SquarePeace** [ic005k/OCAuxiliaryTools#288]
My opencore EFI is 0.8.3, im trying to get last version (0.8.4), but return this message:

![image](https://user-images.githubusercontent.com/56805541/188932094-d60f0b6b-2e67-480d-a9de-afb660f489cf.png)

**Comment by ic005k** [comment]
Please see here:
https://github.com/ic005k/OCAuxiliaryTools/issues/246

**Comment by ic005k** [comment]
If the problem still occurs, please try a few more times to troubleshoot the network.

**Comment by SquarePeace** [comment]
Still same after several attempts
