### ISSUE TITLE
网络或网址错误

### ISSUE THREAD

**Issue by starlifezzz** [ic005k/OCAuxiliaryTools#292]
错误信息：

网络或网址错误！或者GitHub API已达到每小时的访问次数（一般情况下每小时60次），请稍后再试

机型  imapro 1.1
         monterry 12.6
oct版本 最新20220325

上上个版本是可以github下载的。现在无论翻墙与否，都会报这个错，切换另外一个爬取网页源代码，点击更新，没有更新进度条
🙏🏻

**Comment by ic005k** [comment]
> 或者GitHub API已达到每小时的访问次数（一般情况下每小时60次）

可能是这个原因，你过一个小时之后再试就应该没问题了。

**Comment by ic005k** [comment]
> 切换另外一个爬取网页源代码

目前这个功能基本上废掉了，因为就在近期，GitHub做了很大的调整：网页源代码中不再包含文件的下载链接，所以“爬取网页源代码”基本失效，保留这个选项的原因是为了观察GitHub后续的改变，如果始终不在源代码中提供下载的链接，后面OCAT肯定会删除这个选项的。

**Comment by ic005k** [comment]
> 无论翻墙与否

目前的OCAT对这个做了很多改进，基本上不再需要翻墙了，你只需在设置里面选择一个可用的“下载镜像服务器”即可，你可试下。

**Comment by ic005k** [comment]
有任何问题或想法，请随时留言。

**Comment by starlifezzz** [comment]
> 有任何问题或想法，请随时留言。

感谢解惑🙏🏻，我再试试，已经很好用拉
