### ISSUE TITLE
OCAT repeatedly crashes on Ventura

### ISSUE THREAD

**Issue by pnxl** [ic005k/OCAuxiliaryTools#303]
Issue name is self explanatory; OCAT won't launch and repeatedly crashes

https://user-images.githubusercontent.com/66474423/202864486-672cfce3-c6fd-44b3-a931-ece2fbdc6cd9.mov

## What happens when executing

**When running the binary in Terminal, the output is as follows:**
```shell
jason@iMac ~ % /Applications/OCAuxiliaryTools.app/Contents/MacOS/OCAuxiliaryTools ; exit;

QMetaObject::connectSlotsByName: No matching signal for on_chkSmartKey_clicked(bool)
"Kernel" --> "Scheme" Ok...
"NVRAM" --> "" Ok...
"PlatformInfo" --> "PlatformNVRAM" Ok...
"UEFI" --> "APFS" Ok...
Serial-Custom 0
Assertion failed: (result), function NSISIconImageRepGetCGImage, file NSISIconImageRep.m, line 102.
zsh: abort      /Applications/OCAuxiliaryTools.app/Contents/MacOS/OCAuxiliaryTools

Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Process completed]
```

**And viewing the 'Report to Apple' logs..**
[OCAT-ReportToApple.log](https://github.com/ic005k/OCAuxiliaryTools/files/10047657/OCAT-ReportToApple.log)

## The system environment is as follows
**System specifications**
* Core i5-8400
* UHD Graphics 630
* 12 GB DDR4 RAM

**Software environment**
* OC 0.8.6
* macOS 13.0.1
* Fresh install, no modifications
* SIP is disabled

**Comment by ic005k** [comment]
Roger that. Checking is under way. Thanks for your feedback.

**Comment by ic005k** [comment]
Sorry, so far, I haven't found the root cause of this problem.
Is there a problem with the downloaded file?
Can you download OCAT again and see if it works?

**Comment by pnxl** [comment]
Hi there, horribly sorry for the incredibly late response; have been busy for the past couple weeks.
Issue seems to be gone now, then again I'm trying this on a different Hackintosh, as I don't have the same one anymore - I did have the same issues with other applications on that Hackintosh.

No worries then, no issue here - it seems like. Happy holidays and merry Christmas!
