### ISSUE TITLE
您好，麻烦适配一下 0.8.7 谢谢

### ISSUE THREAD

**Issue by iferret** [ic005k/OCAuxiliaryTools#305]
<img width="876" alt="截屏2022-11-22 07 59 17" src="https://user-images.githubusercontent.com/54018634/203182088-cb979f88-500e-49df-80ae-0f76cea6012e.png">

**Comment by ic005k** [comment]
0.8.7？这个是开发版吧，你切换到开发版通道获取OC就可以了，OCAT会自动适配的，如果保存配置文件的时候出现红色的感叹号，你按照提示修改下值就可以了，很简单的。

**Comment by ic005k** [comment]
ShowPicker=Always  0.8.7
ShowPicker="true.    0.8.7之前的版本

这个数据类型产生了变化（布尔到字符串或字符串到布尔），你手动改下就可以了
OCAT目前不会在这块做自动化处理的，但它自动提供了输入框供使用者填入或勾选

等OC的结构调整稳定一些再做自动化处理

**Comment by ic005k** [comment]
目前对“值”对自动化处理有些风险，因为它在下个环节可能又变了，所以暂时没必要。但你要知道如何去填写这个值，看错误提示就可以了，非常简单。

**Comment by iferret** [comment]
谢谢

**Comment by remyxo** [comment]
确实在最后时刻又变回BOOL值了，增加了HibernateSkipsPicker来辅助ShowPicker=TRUE。

**Comment by ic005k** [comment]
> 确实在最后时刻又变回BOOL值了，增加了HibernateSkipsPicker来辅助ShowPicker=TRUE。

是的，所以一般没必要对值进行自动化处理
