### ISSUE TITLE
Error occurred when OCAT updated OC-Mod

### ISSUE THREAD

**Issue by wjz304** [ic005k/OCAuxiliaryTools#306]
Hi, ic005k!
一个 brother 在使用OCAT 更新我的 OC-Mod 时反馈了一个问题， 我开始以为他是操作问题，所以我经过测试找到一种更新的方式，
https://github.com/wjz304/OpenCore_NO_ACPI_Build/issues/3#issuecomment-1321519481

但是他依旧不好使，我重新审视了他的问题，感觉他应该是 OCAT设置的问题。
所以我进行一次反馈，
他的问题：
https://github.com/wjz304/OpenCore_NO_ACPI_Build/issues/3#issue-1457063258

**Comment by ic005k** [comment]
在线更新MOD版？这个方式自始至终没有经过OCAT的验证和测试，OCAT目前只支持对MOD版本本地文件的导入，在线更新从来没测试过，可能会有bug。我回头有空测试下，感谢反馈。

**Comment by wjz304** [comment]
感谢回复。
1. 关于导入链接同步的问题 正如 我在我的issue上所回复， 在很久之前确实是好使的。大概是 0.8.3 版本左右的时候，希望对你有帮助。

2.另外就是这位哥们的问题，我没有出现过类似的弹窗，和下载文件大小0的问题，似乎和 mod 并没有关系。
![image](https://user-images.githubusercontent.com/5615843/203240269-b06655b6-2a9f-4f70-bdb3-a3d97e6a2f82.png)

**Comment by ic005k** [comment]
好的，以上内容已收到。我会在空闲的时候进行逐一分析的，有任何问题或建议请随时留言。

**Comment by ic005k** [comment]
已在最新版的OCAT中正式支持MOD版本的在线更新，欢迎升级到最新版进行测试。
发现任何问题请随时跟帖说明。

**Comment by wjz304** [comment]
收到！我给他们说明一下！
