### ISSUE TITLE
为何同步0.8.6，0.8.5等都没问题，同步最新版（0.8.7）就报错？

### ISSUE THREAD

**Issue by remyxo** [ic005k/OCAuxiliaryTools#313]
报错信息：
”网络或网址错误！
或者Github API已达到每小时的访问次数（一般情况下每小时60次），请稍后再试。“
刚上班就发现OpenCore发布啦最新版0.8.7，用OCAT同步最新版，报错，应该没有达到60次。关键是同步低版本没问题。

**Comment by ic005k** [comment]
我刚通过OCAT成功升级到了OC0.8.7正式版，是没问题的
至于你那边出现的问题，我已记录，后面会进行跟踪分析，有任何其它线索，请随时提供

**Comment by ic005k** [comment]
还有，能否将你同步的界面截图给我看看？

**Comment by ic005k** [comment]
如果下载0.8.5等没问题的话，这个就跟每小时次数限制无关了，要是到达次数的话，0.8.5也是没法获取到的
获取最新版，也不需要什么网址，OCAT能自动检测到最新版的oc网址，所以这个问题非常奇怪

**Comment by ic005k** [comment]
出现这个提示后，0.8.5等老版本也同样是没法获取的，包括Kexts升级也没法下载，因为访问次数到了

**Comment by remyxo** [comment]
<img width="833" alt="截屏2022-12-07 11 35 39" src="https://user-images.githubusercontent.com/37561550/206082205-23d7a566-4ec9-4b81-bcb7-6d24240ff7dd.png">
上面是同步最新版报错。
<img width="871" alt="截屏2022-12-07 11 36 02" src="https://user-images.githubusercontent.com/37561550/206082305-91adb2ef-d8b0-4e18-8bd8-69032870d08e.png">
上图是随后改为同步0.7.1，成功。

**Comment by remyxo** [comment]
但是奇怪的是，我去做了一下核酸检测，预计半小时多一点，回来就可以同步了。

**Comment by ic005k** [comment]
> 但是奇怪的是，我去做了一下核酸检测，预计半小时多一点，回来就可以同步了。

呵呵，可能还是OC那边站点的问题，有任何问题，可随时留言
