### ISSUE TITLE
在帮助下选择更新最新版OCAT，依旧还是0.7.8版本，删除重下github最新版依旧还是0.7.8，有什么办法解决？

### ISSUE THREAD

**Issue by ZerototoFive** [ic005k/OCAuxiliaryTools#316]

**Comment by ic005k** [comment]
在升级OC和Kexts的界面，选“最新版”，点击“获取OpenCore”就可以了

**Comment by CLCK0622** [comment]
> 在升级OC和Kexts的界面，选“最新版”，点击“获取OpenCore”就可以了
> 
> #311

你好 这样下载完仍然是0.7.8 有办法解决吗 同样方法在黑果下正常
