### ISSUE TITLE
不维护了吗？怎么几个月都没更新了一直是0.7.8

### ISSUE THREAD

**Issue by tsepangching** [ic005k/OCAuxiliaryTools#317]
怎么几个月都没更新了一直是0.7.8不维护了吗？

**Comment by ic005k** [comment]
0.7.8之后都是采取在线自动获取OC的方式，这不需要维护的，没太明白你的意思，是不知道如何在线更新OC？请看下面
https://github.com/ic005k/OCAuxiliaryTools/issues/316#issuecomment-1344984774

OCAT自身是不需要频繁维护的，它的设计理念是智能和自动化，请知悉

**Comment by xkrfer** [comment]
点击获取opencore，就能看到新的了
