### ISSUE TITLE
[Suggestion] Add link for `CryptexFixup.kext` to Kext Upgrade URL list

### ISSUE THREAD

**Issue by 5T33Z0** [ic005k/OCAuxiliaryTools#319]
Kext Name | Source URL
-----------|-------------
CryptexFixup.kext |  https://github.com/acidanthera/CryptexFixup

This a relatively new Kext which is required for booting macOS Ventura on legacy hardware which lacks AVX2.0 CPU Instructions (Sandy/Ivy Bridge).

**Comment by ic005k** [comment]
Ok, we'll add it in the next release.
Thanks for the offer.

**Comment by ic005k** [comment]
The above content has been added, please upgrade to the latest version.
Also, delete the $HOME/.ocat directory and open the latest version of OCAT for these files to take effect.

**Comment by 5T33Z0** [comment]
Thank you!
