### ISSUE TITLE
获取不到OC新版本

### ISSUE THREAD

**Issue by jasonziai** [ic005k/OCAuxiliaryTools#320]
ocat版本为最新的20220238，已轻功。在升级oc和kext里选择最新版获取，最高只能到0.8.5，目前应该是0.8.7 。已尝试完全卸载并重装，仍然只有0.8.5 。另外开发版可以获取到0.8.8版，只出现我在macbook pro m1pro上，反而在黑苹果的机子上正常。

**Comment by ic005k** [comment]
已记录。
建议换个时间段再试下看看，很有可能是Github那边的偶发性问题（网络），关注中...


> 已轻功

OCAT已针对访问github困难等问题做了很多优化，先不要科学上网试试看。

**Comment by jasonziai** [comment]
谢谢答复。
感觉不是网络问题。我黑白苹果相同的网络状态同时获取，科学同时开关，黑果没问题，但是白果就是不行。

**Comment by ic005k** [comment]
> 但是白果就是不行

这个我暂时也不清楚问题到底出在哪里，但空闲的时候我会分析下的
有任何进展或线索，请随时留言

**Comment by cytown** [comment]
选择latest，然后重新sync一下就能获取到最新的了。我这里是0.8.8

**Comment by jasonziai** [comment]
> 选择latest，然后重新sync一下就能获取到最新的了。我这里是0.8.8

常规是这样获取的，问题是我白果就是获取不到，最新版只能获取到0.8.5。黑果上没问题

**Comment by ic005k** [comment]
> 问题是我白果就是获取不到

关闭OCAT，删除$HOME/.ocat目录（回到初始化状态），再打开OCAT重新获取OC和Kexts看看？

**Comment by jasonziai** [comment]
> > 问题是我白果就是获取不到
> 
> 关闭OCAT，删除$HOME/.ocat目录（回到初始化状态），再打开OCAT重新获取OC和Kexts看看？

见笑了。$HOME是指什么路径，不太理解没找到。

**Comment by ic005k** [comment]
> $HOME是指什么路径

就是主目录，比如你打开“文档”，这个“文档”目录的父目录就是

**Comment by CLCK0622** [comment]
> 已记录。 建议换个时间段再试下看看，很有可能是Github那边的偶发性问题（网络），关注中...
> 
> > 已轻功
> 
> OCAT已针对访问github困难等问题做了很多优化，先不要科学上网试试看。

同样的问题 是在win11上出现的 最新只有0.7.8 但是黑果正常

**Comment by CLCK0622** [comment]
而且开发版本可以正常获取

**Comment by CLCK0622** [comment]
> > 同样的问题 是在win11上出现的 最新只有0.7.8 但是黑果正常
> 
> 这真是个奇怪的问题，坦率地讲，目前我真不知道问题的根源。 无论如何，我会持续关注这个问题的，如果你们那边有任何线索，请随时提供，谢谢。

哦你好，现在弄好了，只需要把自己的代理全部关掉就好了，走直连可以解决，但是需要多试几次就行了，感谢！

**Comment by jasonziai** [comment]
试了关闭所有代理，并且清理dns缓存，彻底删除软件，问题依旧。我在获取最新版的时候，获取进度条显示都不太正常。录制了一段视频麻烦大佬看看。

https://user-images.githubusercontent.com/32826629/214898045-4d8e5f07-1e50-4218-b6c3-6cf84e56bdae.mov

**Comment by CLCK0622** [comment]
> 试了关闭所有代理，并且清理dns缓存，彻底删除软件，问题依旧。我在获取最新版的时候，获取进度条显示都不太正常。录制了一段视频麻烦大佬看看。
> 
>  2023-01-27.00.47.05.mov

进度条速度没问题 我的也是这样 最新版的爬取可以多试几次 毕竟国内直连越来越难
对了 如果是急用可以切换开发版来配置 应该是肯定能爬到的 我之前就是这样应急

**Comment by ic005k** [comment]
@jasonziai @CLCK0622 借助FastGithub获取最新版，应该是没有任何问题，如果是开发版的话，可能存在些访问障碍。你们不妨试试：

https://github.com/dotnetcore/FastGithub

**Comment by Kenoncloud** [comment]
> > 问题是我白果就是获取不到
> 
> 关闭OCAT，删除$HOME/.ocat目录（回到初始化状态），再打开OCAT重新获取OC和Kexts看看？

实际上是.config目录

**Comment by fengci** [comment]
![image](https://user-images.githubusercontent.com/13860628/215959561-ce05ace9-560a-43c1-85f3-63c45c62e6b0.png)
试过[FastGithub](https://github.com/dotnetcore/FastGithub)更新不到最新版。

这是我抓包响应的HTML内容
[releases.html.zip](https://github.com/ic005k/OCAuxiliaryTools/files/10534245/releases.html.zip)

**Comment by fengci** [comment]
> > > 问题是我白果就是获取不到
> > 
> > 
> > 关闭OCAT，删除$HOME/.ocat目录（回到初始化状态），再打开OCAT重新获取OC和Kexts看看？
> 
> 实际上是.config目录

删除 `$HOME/.config/OCAuxiliaryTools`,重新打开软件更新，就正常了。

**Comment by ic005k** [comment]
> 删除 `$HOME/.config/OCAuxiliaryTools`,重新打开软件更新，就正常了。

这个里面记录的是“偏好设置”里面的内容，看来还是你那边相关设置出了问题，之前应该让你贴下“偏好设置”就应该能排除这个问题了。

**Comment by jasonziai** [comment]
> > 删除 `$HOME/.config/OCAuxiliaryTools`,重新打开软件更新，就正常了。
> 
> 这个里面记录的是“偏好设置”里面的内容，看来还是你那边相关设置出了问题，之前应该让你贴下“偏好设置”就应该能排除这个问题了。
我按@fengci 的做法问题也解决了。操作前顺手在偏好设置里截了张图，没有改过设置，都是默认的。
谢谢各位的帮助！
<img width="782" alt="截屏2023-02-01 21 09 16" src="https://user-images.githubusercontent.com/32826629/216053134-6de12ad8-8f2d-4561-b981-46b6f440ab21.png">

**Comment by jasonziai** [comment]
> > 删除 `$HOME/.config/OCAuxiliaryTools`,重新打开软件更新，就正常了。
> 
> 这个里面记录的是“偏好设置”里面的内容，看来还是你那边相关设置出了问题，之前应该让你贴下“偏好设置”就应该能排除这个问题了。

我按@fengci 的做法问题也解决了。操作前顺手在偏好设置里截了张图，没有改过设置，都是默认的。
谢谢各位的帮助！
<img width="782" alt="截屏2023-02-01 21 09 16" src="https://user-images.githubusercontent.com/32826629/216053472-6202d748-9ca0-4ba5-8044-e0133118d62a.png">

**Comment by ic005k** [comment]
> 操作前顺手在偏好设置里截了张图

截图很明显，“访问Github API...”这个选项貌似没点上？你对比一下看看，应该就是这个问题。

**Comment by jasonziai** [comment]
> > 操作前顺手在偏好设置里截了张图
> 
> 截图很明显，“访问Github API...”这个选项貌似没点上？你对比一下看看，应该就是这个问题。

还真是哦，多谢多谢！

**Comment by ic005k** [comment]
> > 操作前顺手在偏好设置里截了张图
> 
> 截图很明显，“访问Github API...”这个选项貌似没点上？你对比一下看看，应该就是这个问题。
还有之前的代理无法访问了，新代理才可以正常访问，总之你对比下现在正常情况下的设置和之前的截图

**Comment by fengci** [comment]
> > > 操作前顺手在偏好设置里截了张图
> 
> > 
> 
> > 截图很明显，“访问Github API...”这个选项貌似没点上？你对比一下看看，应该就是这个问题。
> 
> 还有之前的代理无法访问了，新代理才可以正常访问，总之你对比下现在正常情况下的设置和之前的截图
> 
> 
> 
> 

我删除文件夹后，代理两个选项是同时选中了，现在去不掉，但没影响使用
