### ISSUE TITLE
麻烦适配 0.8.8  .contentVisibility 文件， 谢谢

### ISSUE THREAD

**Issue by iferret** [ic005k/OCAuxiliaryTools#322]
<img width="763" alt="截屏2023-01-03 13 17 46" src="https://user-images.githubusercontent.com/54018634/210303669-2a9c2689-2bf8-464e-a19f-d0fc2920b0ab.png">

**Comment by ic005k** [comment]
这个“.contentVisibility 文件”应该是你自己根据需要而生成的，它应该并不是OC的某个选项之一，而是一个文件。
当然我只是猜测而已，并没有实践过。

**Comment by iferret** [comment]
您好， opencore 发布的 0.8.8 版本中存在 .contentVisibility  文件 并且添加 .contentVisibility  文件后，会隐藏 opencore EFI分区，反之则显示 opencore EFI 分区 （当然这都是我这个小白 观察到的）, 我想是否可以 将  .contentVisibility 加入到  升级Opencore 和Kexts  页面中  ，这样更方便一些，再次感谢
<img width="869" alt="截屏2023-01-03 20 20 20" src="https://user-images.githubusercontent.com/54018634/210356265-230616c1-a7c6-4b
<img width="1221" alt="截屏2023-01-03 20 21 04" src="https://user-images.githubusercontent.com/54018634/210356352-efe51378-d3a7-4a46-b269-cf0b1931e266.png">
09-a4e5-4e2dc5f77fd6.png">

**Comment by iferret** [comment]
您好， opencore 发布的 0.8.8 版本中存在 .contentVisibility 文件 并且添加 .contentVisibility 文件后，会隐藏 opencore EFI分区，反之则显示 opencore EFI 分区 （当然这都是我这个小白 观察到的）, 我想是否可以 将 .contentVisibility 加入到 升级Opencore 和Kexts 页面中 ，这样更方便一些，再次感谢
<img width="869" alt="截屏2023-01-03 20 20 20" src="https://user-images.githubusercontent.com/54018634/210356566-e81aba75-ed66-4a2d-b298-0addeaae5373.png">

<img width="1207" alt="截屏2023-01-03 20 23 04" src="https://user-images.githubusercontent.com/54018634/210356632-927c4c2b-cd97-46f0-98ac-070be0bae7f1.png">

**Comment by iferret** [comment]
好吧 .contentVisibility 内容 仅为 "Disabled"
<img width="495" alt="截屏2023-01-03 20 25 13" src="https://user-images.githubusercontent.com/54018634/210357021-6e2dd7fa-f700-46cd-9bad-eef0e8b7bf8a.png">

**Comment by ic005k** [comment]
> 我想是否可以 将 .contentVisibility 加入到 升级Opencore 和Kexts 页面中 ，这样更方便一些

可以考虑，但不是很紧急，因为这个文件非常简单，而且可能并不是每个人都需要。
无论如何，感谢反馈！
