### ISSUE TITLE
Sync OC Drivers Didn't Reflect what's on https://github.com/acidanthera/OcBinaryData/tree/master/Drivers contained

### ISSUE THREAD

**Issue by feryw** [ic005k/OCAuxiliaryTools#324]
According to [acidanthera/bugtracker#2190](https://github.com/acidanthera/bugtracker/issues/2190), using latest OC version we must update [HfsPlusLegacy.efi](https://github.com/acidanthera/OcBinaryData/blob/master/Drivers/HfsPlusLegacy.efi), but when doing OC sync in DEV mode using OCAuxiliaryTools we found that  HfsPlusLegacy.efi replaced by the old version.

Can we make OCAuxiliaryTools automatically also update the OC drivers ? Thankyou.

**Comment by ic005k** [comment]
Currently, this content is not automatically updated, please update it manually, and note that when synchronizing OC, please uncheck the "include resource directory" check box.
For later versions, I would consider upgrading them automatically, or manually updating these drivers periodically.
Thanks for the advice.

**Comment by feryw** [comment]
> For later versions, I would consider upgrading them automatically, or manually updating these drivers periodically.
> Thanks for the advice.

Good to know it will be available in the future.

**Comment by ic005k** [comment]
These drivers have been updated, please upgrade OCAT to the latest version.
Also, it is best to delete the $HOME/.ocat directory and open the latest version of OCAT to get the latest driver files.

**Comment by feryw** [comment]
Great, thankyou @ic005k for quick response make it more convinience.
