### ISSUE TITLE
希望适配ARM64

### ISSUE THREAD

**Issue by bimizx** [ic005k/OCAuxiliaryTools#328]
我觉得用着Mac帮别人装黑苹果的人挺多的，希望尽快迁移到≥QT6.2，并适配arm64。

**Comment by JackWu2006** [comment]
其实吧，MV也能正常运行，这个软件也不需要啥运行效率

**Comment by ic005k** [comment]
> 希望尽快迁移到≥QT6.2，并适配arm64

抱歉，目前暂无此计划，因为arm64也完全可以正常运行目前的OCAT

**Comment by ic005k** [comment]
> 其实吧，M1也能正常运行，这个软件也不需要啥运行效率

是的，工具软件更重要的是兼容旧系统，如果升级开发工具，至少macos10.12等老系统就没法使用OCAT了
