### ISSUE TITLE
Mounting Disk

### ISSUE THREAD

**Issue by S1lv3rsur73r** [ic005k/OCAuxiliaryTools#329]
I'm new and finally got MacOS installed. But now I want to edit some things in the config.plist. When I try to mount the disk and enter the password nothing happens.

**Comment by JackWu2006** [comment]
Can you please check your finder settings? If you don't check the first option, ESP won't show.
<img width="489" alt="Screen Shot 2023-01-08 at 18 31 42 PM" src="https://user-images.githubusercontent.com/98635189/211191313-a0acbc78-2e7f-4eb5-85e5-b50624bca0bb.png">

**Comment by JackWu2006** [comment]
Otherwise, you can upload a screen recoding to show the problem.

**Comment by S1lv3rsur73r** [comment]
Thank you very very much. Worked perfectly fine.
