### ISSUE TITLE
Download link for Kext upgrade Error

### ISSUE THREAD

**Issue by feryw** [ic005k/OCAuxiliaryTools#333]
Hi, @ic005k , after you remove the option for crawling github web, currently i often get warning about file creation failed. It's because we are now limited from just accessing github API. 
When i select another mirror , still the same.

Any other workaround for this ? Thankyou.

![Screenshot 2023-01-10 at 09 53 59](https://user-images.githubusercontent.com/15924436/211453324-84d37581-955d-47b7-a9b7-2d6781658d77.png)

**Comment by ic005k** [comment]
> after you remove the option for crawling github web,

This option has been defunct for a long time, and Github has officially banned downloading links from the web's source code.
So, your glitch has nothing to do with this option.

**Comment by ic005k** [comment]
The only possibility is that access to Github will be restricted in certain countries or regions, such as the following link:

https://raw.githubusercontent.com/dortania/build-repo/builds/config.json

In this case, there is no good way to access Github, and you may need to use some special tools such as VPN.

Anyway, I'll keep an eye on it, and if you have anything, feel free to leave a message.

**Comment by feryw** [comment]
Ok, thankyou for some clarifications.
