### ISSUE TITLE
OC validate 提示没有加载OpenRuntime.efi，实际上加载了。

### ISSUE THREAD

**Issue by cytown** [ic005k/OCAuxiliaryTools#334]
<img width="1018" alt="image" src="https://user-images.githubusercontent.com/148625/211707821-c069fe30-9051-447d-985d-7595dce2f2f4.png">

参看上面截图。
我打开config.plist，也是正常.

<img width="927" alt="image" src="https://user-images.githubusercontent.com/148625/211708136-ce46d09f-0b25-41d7-8d46-7272fb63bc83.png">

version: 20230005
os: 11.6.6

**Comment by ic005k** [comment]
同步OC（升级OC）之后，首先保存一下，这样可以消除绝大多数错误。

“LoadEarly”应该不需要勾选吧？去掉之后再保存试试看？

**Comment by cytown** [comment]
> 同步OC（升级OC）之后，首先保存一下，这样可以消除绝大多数错误。
> 
> “LoadEarly”应该不需要勾选吧？去掉之后再保存试试看？

这样是可以，不过这个按理说也应该是个bug。

**Comment by ic005k** [comment]
> 不过这个按理说也应该是个bug

这个就不清楚了，不过你可以随时向OC官方提交此bug，因为OCAT使用的验证工具完全采用OC官方的成品文件，并不属于OCAT自己开发的验证工具
至于“LoadEarly”到底有什么作用，其实我也不知道，呵呵

**Comment by cytown** [comment]
OK, 多谢了。

**Comment by JackWu2006** [comment]
> > 同步OC（升级OC）之后，首先保存一下，这样可以消除绝大多数错误。
> > “LoadEarly”应该不需要勾选吧？去掉之后再保存试试看？
> 
> 这样是可以，不过这个按理说也应该是个bug。

你错了，OCAT检查是通过当前实际文件状态来检查的，如果你没有保存，那当前Config的文件检查确实就是不通过的。
