### ISSUE TITLE
[Content] Updated Intel Base Config Templates

### ISSUE THREAD

**Issue by 5T33Z0** [ic005k/OCAuxiliaryTools#336]
Hi, here are updated Intel Bace Config templates. Some of them had the wrong SMBIOS pre-selected.

[BaseConfigs.zip](https://github.com/ic005k/OCAuxiliaryTools/files/10475308/BaseConfigs.zip)

## Affected Templates:
- Desktop_01stGen_Clarkdale_iMac11,2.plist
- Desktop_01stGen_Lynnfield_Clarkdale_MacPro6,1.plist
- Desktop_04thGen_Haswell_iMac15,1.plist
- Desktop_08th-9thGen_Coffee_Lake_iMac19,2.plist
- Desktop_08th-9thGen_Coffee_Lake_iMac19,2_Z390.plist
- HEDT_X59_Nehalem+Westmere_MacPro6,1.plist
- HEDT_X59_Nehalem+Westmere_MacPro6,1_Dell.plist
- HEDT_X59_Nehalem+Westmere_MacPro6,1_HP.plist
- Appended "_iMacPro1,1" to  the following:
  - HEDT_X299_Skylake-XW_Cascade_Lake-XW_Dell_iMacPro1,1.plist
  - HEDT_X299_Skylake-XW_Cascade_Lake-XW_HP_iMacPro1,1.plist
  - HEDT_X299_Skylake-XW_Cascade_Lake-XW_iMacPro1,1.plist

Greetings,
5T33Z0

**Comment by ic005k** [comment]
Thank you, the database has been updated, please upgrade OCAT to the latest version.
