### ISSUE TITLE
Feature suggestion: Save OCAT Sync window size to avoid resizing on next launch

### ISSUE THREAD

**Issue by superbogie** [ic005k/OCAuxiliaryTools#344]
Have OCAT save the "Sync" window size when closing it/quitting the app. The app will currently revert back to the default window size which can pinch the entries in either panel (kexts and OpenCore) depending on the number of items listed in each.

**Comment by ic005k** [comment]
It has been updated. Please feel free to let me know if you have any questions or suggestions. Thank you.

**Comment by superbogie** [comment]
Thanks. It's admittedly a minor issue but appreciated, nonetheless. 👏🏼👍🏼
