### ISSUE TITLE
DeviceProperties: Add bool as data type option

### ISSUE THREAD

**Issue by t0niX** [ic005k/OCAuxiliaryTools#346]
Hello,

first of all: Thanks for creating this great tool, it makes my life much easier handling OpenCore configs!

My issue is about the following topic:
For disabling my dGPU I added a custom entry in DeviceProperties. The code looks something like this: 
```
<key>DeviceProperties</key>
<dict>
	<key>Add</key>
	<dict>
		<key>PciRoot(0x0)/Pci(0x1,0x0)/Pci(0x0,0x0)</key>
		<dict>
			<key>disable-gpu</key>
			<true/>
		</dict>
	</dict>
	<key>Delete</key>
	<dict/>
</dict>
```

I had to add this entry manually in the config.plist due to OCAuxiliaryTools is not able to set a bool as data type option from inside the tool. Sadly the manually added entry gets manipulated/changed every time I save the config from inside OCAT.

Could you please add the option to use bool as data type option for DeviceProperties?

Thanks a lot!

**Comment by ic005k** [comment]
Here's a first look at the question:

https://github.com/ic005k/OCAuxiliaryTools/issues/295

Second, the solution is:
Use the Data type and set the value to 01000000 (true) or 00000000 (false).

Please note the above content, if you have any questions or suggestions, please feel free to leave a message.

**Comment by t0niX** [comment]
Thanks, I'll try that out!

Happy that you replied so quickly! :)
