### ISSUE TITLE
使用最新版本的OCAT检查0.8.8的simple.plist存在错误

### ISSUE THREAD

**Issue by ycg31** [ic005k/OCAuxiliaryTools#347]
0.8.8版本的OCAT检查0.8.8版本的simple.plist,还会提示配置文件有多余和缺少的项目。
<img width="893" alt="截屏2023-02-11 10 49 00" src="https://user-images.githubusercontent.com/21292117/218235192-9b25bc26-f9d1-4f92-85ae-e9141e6f6d6b.png">

**Comment by ic005k** [comment]
0.8.8版本的OCAT？？没太明白你说的意思。
OCAT不存在和OC版本挂钩的问题，你在OCAT里面获取最新的OC版本，再打开plist文件看看？
关注中...

**Comment by ic005k** [comment]
另外，OCAT是智能检测OC版本并且在保存配置文件的时候，自动修正相关参数，请知悉。

**Comment by ycg31** [comment]
那我换个说法，最新版的OCAT加载完的efi打开plist显示0.8.8，实际上也是0.8.8的opencore ， 检查配置文件提示OCS: No schema for CustomPciSerialDevice at 4 index, context <Quirks>!    我的配置文件中有这一项，opencore的simple文件中也有这一项。

**Comment by ycg31** [comment]
我猜想OCAT正常识别了OC的版本，但是在检查配置文件时使用的对比文件不是最新的simple.plist

**Comment by ic005k** [comment]
> 在检查配置文件时使用的对比文件不是对应版本的simple.plist

正确，对比文件是SampleCustom，而不是简化的Sample，简化的Sample往往会缺失一些内容。
无论如何，你保存一下就正常了。

**Comment by ycg31** [comment]
之前的版本点击保存就可以了，这个版本不行，点了还是有红感叹号，我的环境是13.2， OCAT版本是20230014

**Comment by ic005k** [comment]
> 之前的版本点击保存就可以了，这个版本不行，点了还是有红感叹号，我的环境是13.2， OCAT版本是20230014

请贴下OC验证的提示内容，我看看。

**Comment by ycg31** [comment]
OCS: No schema for CustomPciSerialDevice at 4 index, context <Quirks>! OCS: No schema for ForceAquantiaEthernet at 11 index, context <Quirks>! OCS: No schema for HibernateSkipsPicker at 2 index, context <Boot>! OCS: No schema for LogModules at 5 index, context <Debug>! OCS: Missing key SerialInit, context <Debug>! OCS: Missing key AllowNvramReset, context <Security>! OCS: Missing key AllowToggleSip, context <Security>! OCS: No schema for Serial at 5 index, context <Misc>! OCS: No schema for FullNvramAccess at 5 index, context <Tools>! OCS: No schema for FullNvramAccess at 5 index, context <Tools>! OCS: No schema for FullNvramAccess at 5 index, context <Tools>! OCS: Missing key LegacyEnable, context <NVRAM>! OCS: No schema for PointerDwellClickTimeout at 5 index, context <AppleInput>! OCS: No schema for PointerDwellDoubleClickTimeout at 6 index, context <AppleInput>! OCS: No schema for PointerDwellRadius at 7 index, context <AppleInput>! OCS: No schema for LoadEarly at 3 index, context <Drivers>! OCS: No schema for LoadEarly at 3 index, context <Drivers>! OCS: No schema for LoadEarly at 3 index, context <Drivers>! OCS: No schema for LoadEarly at 3 index, context <Drivers>! Serialisation returns 19 errors!  Completed validating /Volumes/EFI/EFI/OC/config.plist in 1 ms. Found 19 issues requiring attention.

**Comment by ic005k** [comment]
第一行呢？我要看看你目前的OC版本，比如：NOTE: This version of ocvalidate is only compatible with OpenCore version 0.8.9!

**Comment by ic005k** [comment]
或者你上传你的config.plist,我这边打开看看？

**Comment by ycg31** [comment]
![image](https://user-images.githubusercontent.com/21292117/218238781-d22e391f-d839-4b02-9abe-5515c1e48db1.png)
这已经是第一行了

**Comment by ycg31** [comment]
[config.plist.zip](https://github.com/ic005k/OCAuxiliaryTools/files/10712588/config.plist.zip)

**Comment by ic005k** [comment]
你的配置文件没问题呀，可能是你没有同步到OC0.8.8，你同步一下就应该没问题了。

NOTE: This version of ocvalidate is only compatible with OpenCore version 0.8.8!


Completed validating /Users/hz/Downloads/config.plist in 2 ms. No issues found.


验证通过！

**Comment by ic005k** [comment]
保险起见，你先获取OC的最新版，也就是目前的0.8.8，再同步，就应该OK了。

**Comment by ycg31** [comment]
为啥我的日志就没有NOTE: This version of ocvalidate is only compatible with OpenCore version 0.8.8! 这个呢， 就算我的不是0.8.8，也应该有提示啊， 再说我在hacktools里面显示的是0.8.8  。   
随便说一下，OCAT 更新提示网络错误或者是api超过60每小时了

**Comment by ycg31** [comment]
要我下一个版本试试

**Comment by ycg31** [comment]
我制作13.2的安装盘就是用这个整的啊   咋个到了13.2里面   反而还有问题了  奇怪

**Comment by ic005k** [comment]
> 随便说一下，OCAT 更新提示网络错误或者是api超过60每小时了

在设置里面换个代理看看？比如 https://ghproxy.com/https://github.com/
还是不行的话，就等等看（一个小时之后），github的API访问有次数限制，每小时60次，网页访问没有任何限制，只是API接口有限制，请注意！

我觉得你那边出现的奇怪问题，主要存在下面两点：
1.OCAT的数据库是否在线更新到了0.8.8
2.是否同步了最新的0.8.8（也就是升级你的EFI到0.8.8）
除此之外，貌似也没有别的原因了。

当然，如果你那边访问github有障碍，需要施展轻功，这个只能请你自行解决了，呵呵。。。
若解决了，请告知一下原因，谢谢。

**Comment by ic005k** [comment]
> 为啥我的日志就没有NOTE: This version of ocvalidate is only compatible with OpenCore version 0.8.8! 这个呢， 就算我的不是0.8.8，也应该有提示啊， 再说我在hacktools里面显示的是0.8.8 。

这没关系，可能是OC验证的机制问题，OCAT只是调用OC官方的ocvalidate程序进行验证并打印结果，并不是自创的验证体系，你可以单独使用ocvalidate验证你的配置文件看看，结果应该是完全一致的。
欢迎发现更多的问题。

**Comment by ycg31** [comment]
问题解决了！ 获取最新版本的就ok了，把设置里面的代理去掉，github直连就ok了。   后面更新OC版本就好了，我都没同步，因为我的efi里本来就是0.8.8的了。
还是有个问题不理解， 我下载后OCAT里面数据库已经显示是0.8.8 进入文件夹查看simple.plist也是0.8.8的了，因为有的键值只有0.8.8才有，为啥非要找同步这里获取opencore最新版本才可以正常对比呢

**Comment by ycg31** [comment]
那这个验证机制就在配置文件前必须要获取对应的OC到databse的efi文件夹中，如果能直接从加载config.plist的efi中进行对比就好了

**Comment by ic005k** [comment]
> 还是有个问题不理解， 我下载后OCAT里面数据库已经显示是0.8.8 进入Baseconfigs文件夹查看simple.plist也是0.8.8的了，因为有的键值只有0.8.8才有，为啥非要找同步这里获取opencore最新版本才可以正常对比呢

这个问题问得很好，其实这个内置的OC版本也可能是滞后的，它来自一个贡献者的PR，具体在这里：https://github.com/ic005k/OCAuxiliaryTools/pull/339

但这个内置的0.8.8版本是不是最新等等，并没有用户去验证它，也没必要去验证它，用户一般都是在线获取最新版或OC的某个版本，根本不用考虑内置的OC版本。

**Comment by ic005k** [comment]
> 那这个验证机制就在配置文件前必须要获取对应的OC到databse的efi文件夹中

是的，必须先更新OCAT的数据库（这个验证程序存在于OCAT的数据库中）以获取相应版本的OC验证程序文件。

> 如果能直接从加载config.plist的efi中进行对比就好了

同上，如果没有OC官方的验证程序支撑，是没法完成验证的，因为你的EFI中不可能再放这些额外的验证程序，当然即便你愿意在你的EFI中放一个OC的验证程序，但别的用户不一定愿意放这些额外的东西，所以OCAT是没办法统一去调取用户的EFI里面的验证程序的，只能使用OCAT自身数据库里的验证程序。

**Comment by ic005k** [comment]
抱歉，我检查了一下这个PR https://github.com/ic005k/OCAuxiliaryTools/pull/339/files ，貌似并没有更新OC验证程序，这可能是主要原因。
请原谅我没有认真审核这个PR，如果是这样的话，我将在下个OCAT版本更新相应的文件。

**Comment by ycg31** [comment]
最新版的ok了，更新挺快
