### ISSUE TITLE
连多显示器后无法打开

### ISSUE THREAD

**Issue by lhx-nlxbc** [ic005k/OCAuxiliaryTools#348]
有一次把ocat窗口放到了另一个显示器中，现在断开了，但是窗口不显示了

**Comment by ic005k** [comment]
有可能是ocat自动记忆了窗口位置导致的。
删除.config/OCAuxiliaryTools目录看看？

**Comment by lhx-nlxbc** [comment]
已解决，谢谢！

**Comment by Sauvio** [comment]
原来如此，我下载了你仓库里的3个不同应用都是打不开，删除.config解决了。
