### ISSUE TITLE
ocvalidate version?

### ISSUE THREAD

**Issue by D-an-W** [ic005k/OCAuxiliaryTools#352]
Hi, I did a fresh install of OCAT this morning and when checking the Config.plist that was ok last night I see the warning in the screenshot, is the just me doing something wrong or an issue please?

![Screenshot 2023-02-15 at 06 37 12](https://user-images.githubusercontent.com/2243883/218951929-2788893b-3e55-4794-93bb-4e3650190210.png)

**Comment by ic005k** [comment]
OCAT currently has a built-in OC version of 0.8.8, which may not be consistent with the current OC version used by users.
So, please choose an OC that is consistent with your EFI version and update the database.

**Comment by D-an-W** [comment]
Thanks, I am on 0.8.9, will do as you mentioned.
