### ISSUE TITLE
Update KextUrl.txt

### ISSUE THREAD

**Issue by Baio1977** [ic005k/OCAuxiliaryTools#356]
https://github.com/Baio1977/OCAuxiliaryTools/blob/master/Database/preset/KextUrl.txt

Add :
VoodooRMI.kext | https://github.com/VoodooSMBus/VoodooRMI
VoodooSMBus.kext | https://github.com/VoodooSMBus/VoodooRMI
GenericCardReaderFriend.kext | https://github.com/0xFireWolf/GenericCardReaderFriend
YogaSMC.kext | https://github.com/zhen-zen/YogaSMC

**Comment by ic005k** [comment]
Thanks for providing the above content, has been updated.
