### ISSUE TITLE
mac版ocat无法检查开发版opencore更新和开发版kext更新，但可以检查非开发版的更新

### ISSUE THREAD

**Issue by HuaZoffice** [ic005k/OCAuxiliaryTools#365]
![截屏2023-04-25 17 23 44](https://user-images.githubusercontent.com/74406139/234233733-1f1207e0-a9ef-4277-8f47-77c8a0cf9e40.png)
如图，当我检查开发版opencore以及开发版kext时就会出现这个，我很确定我是可以访问github的，但是当我检查非开发版的kext更新或者非官方版opencore时是没有问题的。

**Comment by ic005k** [comment]
这个原因是因为你那边并不能非常全面地访问github，问题还是出在github的访问上面。（正式版的OC和开发版的OC位于github的不同节点）

OCAT内置的镜像服务器比如：https://ghproxy.com/https://github.com/ 最近貌似也出了问题，截止目前还没有恢复。

所以这个问题OCAT本身是没法解决的，必须通过一些其它途径来解决全面访问github的问题，比如施展轻功等等。

另外：能访问github和能否全面访问github是有区别的，注意“全面”这两个字眼。

**Comment by HuaZoffice** [comment]
> 这个原因是因为你那边并不能非常全面地访问github，问题还是出在github的访问上面。（正式版的OC和开发版的OC位于github的不同节点）
> 
> OCAT内置的镜像服务器比如：https://ghproxy.com/https://github.com/ 最近貌似也出了问题，截止目前还没有恢复。
> 
> 所以这个问题OCAT本身是没法解决的，必须通过一些其它途径来解决全面访问github的问题，比如施展轻功等等。
> 
> 另外：能访问github和能否全面访问github是有区别的，注意“全面”这两个字眼。

好的，我挂上代理就解决了
