### ISSUE TITLE
0.9.3测试版报错

### ISSUE THREAD

**Issue by ghsssss** [ic005k/OCAuxiliaryTools#369]
NOTE: This version of ocvalidate is only compatible with OpenCore version 0.9.3!

UEFI->Output->InitialMode is illegal (Can only be Auto, Text, or Graphics)!
CheckUefi returns 1 error!

Completed validating /Volumes/EFI/EFI/OC/config.plist in 1 ms. Found 1 issue requiring attention.

**Comment by ghsssss** [comment]
@ic005k i

**Comment by iferret** [comment]
<img width="907" alt="截屏2023-05-10 15 05 38" src="https://github.com/ic005k/OCAuxiliaryTools/assets/54018634/75852d5a-78ca-4b1d-80da-db1055569854">配置一下就行了

**Comment by SashonIT** [comment]
Set the InitialMode to AUTO.... Then ist Flawless.
