### ISSUE TITLE
[CONTENT] Updated Intel Config Templates

### ISSUE THREAD

**Issue by 5T33Z0** [ic005k/OCAuxiliaryTools#370]
Hi.

Attached you find updated config.plist templated for Intel CPU families

**Changes**
- Updated Configs to support OC 092+
- Created `#Info` Dictionary with updated Details about the config
- Added ResetNvramEntry.efi driver
- Fixed some config issus
- Renamed `X59` presets to `X58`  since x59 Chipset doesn't exist (best delete all templates named "HEDT_X59…") 

Greetings,
5T33Z0

[BaseConfigs_INTEL.zip](https://github.com/ic005k/OCAuxiliaryTools/files/11524133/BaseConfigs_INTEL.zip)

**Comment by ic005k** [comment]
The latest version makes these configuration templates available online, so you can simply update them on your home page. Thank you for your dedication.

**Comment by ic005k** [comment]
This can also bring you some traffic, let more users know and pay attention to you, thank you.

**Comment by 5T33Z0** [comment]
This change is really bad for genrating working EFI folders from templates. For several reasons:

1. You are locking users out of entering the database by placing a link to my repo in the pop-up instead of just opening the database. This makes no sense.
2. When placing a link on a popup instead of opening the database to load a config template, you are killing the option to generate an EFI folder because:
   - Right-clicking a .plist in a webbrowser to save it from the repo creates an invalid plis file which can't be edited
   - Since OCAT cannot import raw text, users would have to open the plis as raw text, manually copy the content to paste it in another plist editor, then save it and then edit it in OCAT. This makes no sense
3. On top of that, you left the old Templates in the database's BaseConfigs folder instead of using the updated ones

So you are basically crippling a unique feature of OCA this way.
