### ISSUE TITLE
⚠️ Instructions for generating EFI folder from config template result in invalid plist file!

### ISSUE THREAD

**Issue by 5T33Z0** [ic005k/OCAuxiliaryTools#372]
In your [latest release](https://github.com/ic005k/OCAuxiliaryTools/releases/tag/20230020) of OCAT, you removed direct user access to the database from within the App for generating pre-configured EFIs for Intel Systems. Instead, you redirect users to my repo via URL:

![Bildschirmfoto 2023-05-23 um 09 59 12](https://github.com/ic005k/OCAuxiliaryTools/assets/76865553/18e1b559-dcab-4d98-930f-654cbdc9407c)

In order to generate an EFI, you suggest the following in the changelog popup window:

![Changelig](https://github.com/ic005k/OCAuxiliaryTools/assets/76865553/625a4615-4008-441e-b5cf-f7f988980c9d)

These instructions are wrong! Downloading an plist via right-clicking in a browser changes it's fileheader and results in an invalid file:

![Bildschirmfoto 2023-05-23 um 09 55 42](https://github.com/ic005k/OCAuxiliaryTools/assets/76865553/8153a56d-eee1-4f63-afc2-530083fdc0b5)

In order for users to use this feature they would have to import the raw text into OCAT, which it does not support. So users would have to copy the raw text into ProperTree save the config, then open it in OCAT again in order to be able to generate and populate the EFI fodler. I don't think this is a desireable workflow. 

My suggestion is to revert this setting and let users access the database again.

**Comment by ic005k** [comment]
Please refer to my latest reply in your previous question.
