### ISSUE TITLE
gh.flyinbug.top失效了，导致无法在线更新

### ISSUE THREAD

**Issue by hkbase** [ic005k/OCAuxiliaryTools#373]
软件版本：https://github.com/ic005k/OCAuxiliaryTools/releases/download/20230020/OCAT_Mac.dmg)
遇到的问题：无法在线同步更新。
故障原因：
软件内置的加速代理gh.flyinbug.top ，这个加速站点失效了，导致无法在线同步更新

日志如下：
05/26 14:47:25 [[1;32mNOTICE[0m] Downloading 1 item(s)
2023-05-26 14:47:25.244725 [INFO] [../../../src/AsyncNameResolverMan.cc:83] CUID#7 - Resolving hostname gh.flyinbug.top

2023-05-26 14:47:25.313779 [ERROR] [../../../src/AbstractCommand.cc:351] CUID#7 - Download aborted. URI=https://gh.flyinbug.top/gh/https://github.com/ic005k/OCAuxiliaryTools/releases/download/20230020/OCAT_Mac.dmg
Exception: [../../../src/AbstractCommand.cc:351] errorCode=19 URI=https://gh.flyinbug.top/gh/https://github.com/ic005k/OCAuxiliaryTools/releases/download/20230020/OCAT_Mac.dmg
  -> [../../../src/AbstractCommand.cc:792] errorCode=19 CUID#7 - Name resolution for gh.flyinbug.top failed:Domain name not found

05/26 14:47:25 [[1;31mERROR[0m] CUID#7 - Download aborted. URI=https://gh.flyinbug.top/gh/https://github.com/ic005k/OCAuxiliaryTools/releases/download/20230020/OCAT_Mac.dmg
Exception: [../../../src/AbstractCommand.cc:351] errorCode=19 URI=https://gh.flyinbug.top/gh/https://github.com/ic005k/OCAuxiliaryTools/releases/download/20230020/OCAT_Mac.dmg
  -> [../../../src/AbstractCommand.cc:792] errorCode=19 CUID#7 - Name resolution for gh.flyinbug.top failed:Domain name not found

2023-05-26 14:47:25.313927 [NOTICE] [../../../src/RequestGroupMan.cc:427] Download GID#9e63f9455e6d1c50 not complete: 

05/26 14:47:25 [[1;32mNOTICE[0m] Download GID#9e63f9455e6d1c50 not complete: 

Download Results:
gid   |stat|avg speed  |path/URI
======+====+===========+=======================================================
9e63f9|ERR |       0B/s|https://gh.flyinbug.top/gh/https://github.com/ic005k/OCAuxiliaryTools/releases/download/20230020/OCAT_Mac.dmg

Status Legend:
(ERR):error occurred.

aria2 will resume download if the transfer is restarted.
If there are any errors, then see the log file. See '-l' option in help/man page for details.

**Comment by hkbase** [comment]
建议使用这个加速站点：
https://ghproxy.com/

我已经稳定使用很多年了。

**Comment by hkbase** [comment]
建议使用这个加速站点：
https://ghproxy.com/

我已经稳定使用很多年了。

**Comment by hkbase** [comment]
建议使用 ghproxy.com 替换掉内置的 gh.flyinbug.top

**Comment by ic005k** [comment]
这些镜像都是时好时坏，你选择一个适合自己的就可以了。

另外https://ghproxy.com/https://github.com/ 已在镜像服务器的下拉列表中，只不过不是默认的镜像，你改过来就可以了。

注意：镜像列表既可以自行输入（自定义，当所有的内置镜像都不起作用时，你可以自己弄一个镜像），也可以通过编辑框右边的向下箭头按钮（下拉列表）进行其他镜像的选择。

**Comment by ic005k** [comment]
之前有部分用户不太清楚下拉列表编辑框的用法，认为这个编辑框只能输入文本，不知道有下拉列表的功能，那个最右边的向下箭头就是下拉列表，这是Windows等操作系统的标准控件，大家应该都十分熟悉的。

**Comment by ic005k** [comment]
点击“文件”菜单选“设置”，在设置界面的“杂项”标签页即可自行修改或选择镜像服务器，旁边的“测试”按钮可供你测试该镜像服务器是否工作正常，过程非常简单。

**Comment by ic005k** [comment]
这些设置都是自动记忆的，下次使用无需重复设置。

**Comment by hkbase** [comment]
ok,已经通过调整设置，问题解决了，谢谢老大的回复。
