### ISSUE TITLE
String in DeviceProperties doesn't show

### ISSUE THREAD

**Issue by xCuri0** [ic005k/OCAuxiliaryTools#374]
![image](https://github.com/ic005k/OCAuxiliaryTools/assets/29529557/8c07979e-3b1b-46cc-805e-82341ddee9d9)

My DeviceProperties `PciRoot(0x0)/Pci(0x1f,0x0)`, I added the two `fan#-pwm` keys using ProperTree.

```xml
<key>PciRoot(0x0)/Pci(0x1f,0x0)</key>
<dict>
	<key>fan0-control</key>
	<data>Ag==</data>
	<key>fan2-hide</key>
	<data>AQ==</data>
	<key>fan3-hide</key>
	<data>AQ==</data>
	<key>fan4-hide</key>
	<data>AQ==</data>
	<key>fan0-pwm</key>
	<string>928,0|928,17|928,34|928,51|928,68|928,85|928,102|1004,119|1118,136|1199,153|1303,170|1383,187|1471,204|1531,221|1603,238|1675,255|</string>
	<key>fan1-pwm</key>
	<string>936,48|970,49|990,50|1004,51|1029,52|1047,53|1063,54|1075,55|1094,56|1114,57|1129,58|1148,59|1162,60|1178,61|1193,68|1493,85|1762,102|2003,119|2220,136|2428,153|2596,170|2778,187|2961,204|3111,221|3261,238|3293,255|</string>
</dict>
```

Additionally if I save my config.plist using OCAT I lose those 2 keys.

**Comment by ic005k** [comment]
This problem may be the cause of the symbol "|", later I'll analysis, thank you for feedback.

**Comment by ic005k** [comment]
The issue has been fixed, please download the test here:

https://github.com/ic005k/OCAuxiliaryTools/actions/runs/5117296545

**Comment by xCuri0** [comment]
@ic005k It works, thanks for fixing this!

![image](https://github.com/ic005k/OCAuxiliaryTools/assets/29529557/e4bc7b8c-8151-4d43-a35d-70426c8a2b06)

**Comment by wangyangege** [comment]
why not update
