### ISSUE TITLE
Would like to be able to open two copies of OCAT to compare different plists

### ISSUE THREAD

**Issue by cypherstream** [ic005k/OCAuxiliaryTools#382]
Ive been struggling to take bits and pieces from one or two different plists into a new list because OCAuxiliaryTools on mac does not allow you to open multiple instances.  I've painstakingly copied a lot of stuff to notes or taken screen shots then have to close a list and open another and paste things or adjust things / and compare.

The tool makes it easier.  I've done the text edit copy and pastes but its prone to error if you don't get all of your opening and closing tags right, or in the right sections.

Not sure if you can open multiple instances and I'm just not aware, but at least on my system, Mac OS Ventura, it only opens one instance.

**Comment by ic005k** [comment]
Very simply, select "New Window" below the "File" main menu.

**Comment by cypherstream** [comment]
Wow what a timesaver!  Thanks this can be closed.

User ignorance 😁
