### ISSUE TITLE
About NootedRed.kext

### ISSUE THREAD

**Issue by laobamac** [ic005k/OCAuxiliaryTools#386]
Hello！A new lilu plugin named [NootedRed.kext]('https://github.com/NootInc/NootedRed') has appeared for a few days,but OCAT kexts database hasn't included this kext.Could you add it in next version？Many thanks.

ps:If project need,it's ok to use my repo of NootedRed-Releases(only for releases).
The homepage has declared that the owner of this project is NootInc and its members, and this repository is only used for storing compiled versions for the supplier's convenience. Please be aware.

**Comment by dawalishi0821** [comment]
That's great,I think this idea is very meaningful. This plugin is very important and Perhaps many users want it to be included,this eliminates the need for manual addition steps.

**Comment by ChefKissInc** [comment]
I (ChefKiss Inc), legal copyright holder of [NootedRed], hereby explicitly forbid distribution of [NootedRed] source code and binaries in any shape or form under copyright law, unless otherwise exempt by direct signed statement or usage of [NootedRed] falls under Fair Use, as explicitly described by Section 107 of the Copyright Act

**Comment by chriswayg** [comment]
@VisualEhrmanntraut 
> I (ChefKiss Inc), legal copyright holder of [NootedRed], hereby explicitly forbid distribution of [NootedRed] source code and binaries in any shape or form under copyright law, unless otherwise exempt by direct signed statement or usage of [NootedRed] falls under Fair Use, as explicitly described by Section 107 of the Copyright Act

Actually, you _ChefKiss Inc_, appear to be contradicting your own published license in the comment you made above. Did you change your mind since you made that comment? Could you please clarify what license conditions are the current ones as of April 2024?

> Licensed under the Thou Shalt Not Profit License version 1.5
> 
> 1) Grant of Copyright License. Licensor grants You a worldwide, royalty-free, non-exclusive, sublicensable license, for the duration of the copyright, to do the following:
> 
> c) to distribute or communicate copies of the Original Work and Derivative Works to the public, with the proviso that copies of Original Work or Derivative Works that You distribute or communicate shall be licensed under this Thou Shalt Not Profit License;

**Comment by VisualEhrmanntraut** [comment]
No contradictions here. It is fair use if you use it under the license conditions. The license explicitly states that distribution of the work must retain the copyright notice and reuse the TSNPL v1.5 license. Therefore, all binary or source code distributions must be licensed under the same license and retain the copyright notice.
