### ISSUE TITLE
Sonoma 14.0 OCAuxiliaryTools 挂载 EFI 会风火轮

### ISSUE THREAD

**Issue by cheneyxx** [ic005k/OCAuxiliaryTools#391]
退出软件无效 只能重启解决

**Comment by ic005k** [comment]
已记录，目前没有安装Sonoma14.0,暂时还无法测试，感谢反馈。

**Comment by cheneyxx** [comment]
> 已记录，目前没有安装Sonoma14.0,暂时还无法测试，感谢反馈。

估计是系统问题或者是 OpenCore 的问题 目前不会风火轮了
