### ISSUE TITLE
“Mount and open Config.plist” seems not working

### ISSUE THREAD

**Issue by wxxsfxyzm** [ic005k/OCAuxiliaryTools#394]
when I click the “Mount and open Config.plist configuration file” button, Mac shows a prompt which asks for my password. After entering password, it only mounts the esp partition but not opening the file, I have to find the file by myself, is it a normal behavior ?

**Comment by ic005k** [comment]
The reason for this problem could be:
You have not set a volume label for the Mac disk.

**Comment by wxxsfxyzm** [comment]
> The reason for this problem could be: You have not set a volume label for the Mac disk.

Problem solved, thx.
