### ISSUE TITLE
BUG - Misc - Security - SecurbootMode

### ISSUE THREAD

**Issue by Baio1977** [ic005k/OCAuxiliaryTools#395]
![Screenshot 2023-12-23 alle 13 36 46](https://github.com/ic005k/OCAuxiliaryTools/assets/59058746/aefd9723-bfe0-426e-9827-3d735062d29a)

I set it like this with OCAT but when I save and reopen the config.plist

![Screenshot 2023-12-23 alle 13 38 16](https://github.com/ic005k/OCAuxiliaryTools/assets/59058746/53598d6d-26f5-423a-b64e-c22b138d9aa7)

come back like this.
If anyone can verify, THANK YOU

**Comment by ic005k** [comment]
Received,I will fix it in the next version,thanks.
