### ISSUE TITLE
无法获取opencore最新版本

### ISSUE THREAD

**Issue by lienting885** [ic005k/OCAuxiliaryTools#396]
点击“获取opencore最新版本”后，进度条卡住
![image](https://github.com/ic005k/OCAuxiliaryTools/assets/132539157/8ac16c81-1dbb-4c36-ae93-e45596de0af4)

**Comment by y010204025** [comment]
我也出线了这个问题，即使开代理也没办法获取到更新。

**Comment by ic005k** [comment]
近期github的镜像服务貌似全线崩溃，在镜像服务器设置里面选择第一个“github.com”（不采用镜像，直接访问github），然后施展轻功看看

**Comment by y010204025** [comment]
已按此方法测试成功，这条issue可以关闭了，或者保持开放状态，避免别人继续开新的issue
