### ISSUE TITLE
能否添加 使用 个人Github 账号授权功能, 解决 API 访问限制问题呢

### ISSUE THREAD

**Issue by iferret** [ic005k/OCAuxiliaryTools#403]

**Comment by ic005k** [comment]
这个和你个人github账号授权关系不大，主要跟各个kext的开发者是否对其项目进行了相应的认证，以提高单位时间内别人通过API访问其项目的次数，具体你可以看下github的相关内容，记得在之前的问题回复中提到过相应的链接，你可以翻下之前的问题回复。

**Comment by iferret** [comment]
谢谢
