### ISSUE TITLE
Plist error: This version of ocvalidate is only compatible with OpenCore version 1.0.2!

### ISSUE THREAD

**Issue by lucaspmarra** [ic005k/OCAuxiliaryTools#411]
Following the complete tutorial for downloading the plist, I get the following error: This version of ocvalidate is only compatible with OpenCore version 1.0.2!

The thing is:
1 - I've just downloaded OCAuxiliaryTools (fresh install);
2 - I've just downloaded the correct configuration file (fresh install);
3 - Nothing happens when I try to update the Kexts;
4 - The tutorial for downloading the plist is out of date and may be providing files from 1 year ago;
5- After clicking on “Start Sync”, nothing happens;
6 - The file contained in the “Actions” tab is expired and it is not possible to download the latest build;

![image](https://github.com/user-attachments/assets/07e89623-2034-4098-86b4-200f5278bf51)

![image](https://github.com/user-attachments/assets/5c395b3b-52e5-4638-b2da-d86b2b413161)

![image](https://github.com/user-attachments/assets/9d6f87f8-8292-48a2-9283-177c40be39b1)

**Comment by ic005k** [comment]
1. The plist file you open does not appear to come from an EFI structured folder, which will cause kexts to be lost (non-existent).
2. When the verification error is prompted, please try to "save" (Save button on the toolbar) plist file, OCAT will automatically fix the error.

**Comment by ic005k** [comment]
If you want to create your own EFI from a template plist file, please refer to here:


https://github.com/5T33Z0/OC-Little-Translated/tree/main/F_Desktop_EFIs/Config_Templates

**Comment by lucaspmarra** [comment]
> 1. The plist file you open does not appear to come from an EFI structured folder, which will cause kexts to be lost (non-existent).

What do you mean by that? I downloaded it following the tutorial on the page (the same one you sent).



![image](https://github.com/user-attachments/assets/f811a9b2-2878-41de-b54e-b9d0d6ee80a9)

**Comment by lucaspmarra** [comment]
>     2. When the verification error is prompted, please try to "save" (Save button on the toolbar) plist file, OCAT will automatically fix the error.

That solved the problem, the errors are gone!
![image](https://github.com/user-attachments/assets/ff1d97b3-7de5-4644-b986-71e16a951dba)

But it's still impossible to update the Kexts, there's no feedback, nothing just happens

![image](https://github.com/user-attachments/assets/95540a30-b11a-41be-8bc1-097b41945d5b)
